Refactor to add QCMetric class and list of URLs for reference images/figures
AllenNeuralDynamics/aind-data-schema pull request #1037
Opened 2024-08-26 22:44 UTC by dbirman

2024-08-27 23:45 UTC, saskiad commented on examples/quality_control.json
> +                  "Video_1_num_frames": 662,
I guess I thought that each metrics would be a separate instance of `qc_metrics`, is that not the idea?

2024-08-27 23:45 UTC, saskiad commented on src/aind_data_schema/core/quality_control.py
> +    description: Optional[str] = Field(None, title="Metric description")
add the `default=` for the optional fields.

2024-08-27 23:45 UTC, saskiad requested changes
fix the defaults. Also a quick question on how you envision using it

2024-08-28 15:39 UTC, dbirman commented on examples/quality_control.json
> +                  "Video_1_num_frames": 662,
Oh I see what you were imagining, so the evaluation here would have two metrics (video 1 frames / video 2 frames) and then the evaluation is passed/failed based on whether they match? (let me know if that's wrong). I'll change the example.

2024-08-28 15:41 UTC, dbirman commented on examples/quality_control.json
> +                  "Video_1_num_frames": 662,
For evaluations that have rules like this, do we need a place to put that? I feel like "Notes" doesn't imply that there should be a description of the evaluation rule.

2024-08-29 18:45 UTC, dbirman commented
Added quality_control.Stage per discussion, and modified examples to better reflect our concept. Also added name to QCEvaluation and made descriptions optional, to separate stage/name/desc from each other.

2024-08-30 03:19 UTC, saskiad commented on src/aind_data_schema/core/quality_control.py
> +    evaluation_desc: Optional[str] = Field(default=None, title="Evaluation description")
can we make this `evaluation_description` - I'm reluctant to shorten things, even obvious things.

2024-08-30 03:19 UTC, saskiad commented on src/aind_data_schema/core/quality_control.py
> +    qc_metrics: List[QCMetric] = Field(title="QC metrics")
I think this needs the `...` in the Field

2024-08-30 03:20 UTC, saskiad requested changes
super minor things, but otherwise I think it's good.

2024-08-30 18:06 UTC, saskiad approved these changes

2024-08-30 18:07 UTC, merged