536 add compute resource usage to processingjson
AllenNeuralDynamics/aind-data-schema pull request #1063
Opened 2024-09-13 16:21 UTC by dbirman

2024-09-23 02:58 UTC, saskiad commented on src/aind_data_schema/core/processing.py
> +    timestamp: date = Field(..., title="Timestamp")
do we want this to be datetime rather than date?

2024-09-23 02:59 UTC, saskiad commented on src/aind_data_schema/core/processing.py
> +    file_io_usage: Optional[List[ResourceTimestamped]] = Field(default=None, title="File I/O usage")
add a `usage_unit` field with default of percent.

2024-09-23 03:00 UTC, saskiad commented on src/aind_data_schema/core/processing.py
> +    file_io_usage: Optional[List[ResourceTimestamped]] = Field(default=None, title="File I/O usage")
we have percent in the unit options in the models ...

2024-09-23 03:02 UTC, saskiad commented on src/aind_data_schema/core/processing.py
> +    ram_usage: Optional[List[ResourceTimestamped]] = Field(default=None, title="RAM usage (%)")
add a `usage_unit` field with a default of percent. You can use the `UnitlessUnit.PERCENT` class in the unit.py of models.

2024-09-23 03:02 UTC, saskiad requested changes
couple questions

2024-09-23 16:29 UTC, dbirman commented on src/aind_data_schema/core/processing.py
> +    timestamp: date = Field(..., title="Timestamp")
we sure do!

2024-09-25 05:15 UTC, saskiad commented on src/aind_data_schema/core/processing.py
> +    timestamp: datetime = Field(..., title="Timestamp", default_factory=datetime.now)
let's use the `AwareDatetimeWithDefault` to be consistent with rest of schema (and handle time zones appropriately)

2024-09-26 04:22 UTC, camilolaiton requested changes

2024-09-26 04:22 UTC, camilolaiton commented on src/aind_data_schema/core/processing.py
> +    memory: Optional[MemoryValue] = Field(default=None, title="System memory")
Sorry, what do you specifically mean with memory? Slow access memory such as hard drives or other types of compartments? I ask because I see a slot for RAM with MemoryValue as dtype.

2024-09-26 05:04 UTC, dbirman commented on src/aind_data_schema/core/processing.py
> +    memory: Optional[MemoryValue] = Field(default=None, title="System memory")
Yes HDD/SSD. Irrelevant for virtual machines linked to S3 buckets, but for people running on real hardware this might be relevant.

2024-09-26 16:30 UTC, camilolaiton commented on src/aind_data_schema/core/processing.py
> +    memory: Optional[MemoryValue] = Field(default=None, title="System memory")
I would recommend a different name then since it could get confused with RAM memory if you don't see the other property of the class.

2024-09-29 05:33 UTC, saskiad commented on src/aind_data_schema/core/processing.py
> +    file_io_unit: Optional[MemoryUnit] = Field(default=None, title="File I/O unit")
unit can't be optional. It's annoying to have units for fields that are empty, but I'm more worried that someone will provide the value and not provide the unit since it is optional. So all units are required, but not all values.

2024-09-29 05:34 UTC, saskiad commented on src/aind_data_schema/core/processing.py
> +from aind_data_schema_models.units import MemoryUnit, MemoryValue, UnitlessUnit
I believe we discussed undoing the unit_with_value thing before we merge? do I recall correctly?

2024-09-29 05:37 UTC, saskiad commented on src/aind_data_schema/core/processing.py
> +    file_io_usage: Optional[List[ResourceTimestamped]] = Field(default=None, title="File I/O usage")
I don't really know what file i/o usage means. Which isn't necessarily a problem, but I wonder if others will understand? Would a description help or am I just out of the loop?

2024-09-29 05:38 UTC, saskiad requested changes
we wanted to change the value_with_unit thing, right? couple other small things as well

2024-09-30 17:09 UTC, dbirman commented on src/aind_data_schema/core/processing.py
> +    file_io_usage: Optional[List[ResourceTimestamped]] = Field(default=None, title="File I/O usage")
Removed

2024-10-03 21:29 UTC, saskiad approved these changes

2024-10-03 21:33 UTC, camilolaiton approved these changes

2024-10-03 21:34 UTC, merged