1072 qc automate state properties in qualitycontrol and evaluation based on metric states
AllenNeuralDynamics/aind-data-schema pull request #1074
Opened 2024-09-23 16:05 UTC by dbirman

This PR refactors the `overall_status` and `evaluation_status` fields to built from the status of the `QCMetric` objects in each evaluation. The complication to this PR is that it would require people to build QualityControl objects to use these features, if you dump to JSON and you don't re-validate as a model you can only access the `_history` lists indirectly. You can still use the schema without building the classes you just don't get access to the convenience functions that are defined using the `@property` tags.

I'll walk through the tests to explain how this works:

```
        test_eval = QCEvaluation(
            evaluation_name="Drift map",
            evaluation_modality=Modality.ECEPHYS,
            evaluation_stage=Stage.PROCESSING,
            qc_metrics=[
                QCMetric(
                    name="Multiple values example",
                    value={"stuff": "in_a_dict"},
                    metric_status_history=[
                        QCStatus(evaluator="Bob", timestamp=datetime.fromisoformat("2020-10-10"), status=Status.PASS)
                    ],
                ),
                QCMetric(
                    name="Drift map pass/fail",
                    value=False,
                    description="Manual evaluation of whether the drift map looks good",
                    reference="s3://some-data-somewhere",
                    metric_status_history=[
                        QCStatus(evaluator="Bob", timestamp=datetime.fromisoformat("2020-10-10"), status=Status.PASS)
                    ],
                ),
            ],
        )

        q = QualityControl(
            evaluations=[test_eval, test_eval],
        )

``` 

This object has status set for the metrics, but not for the evaluation or the full quality control object. If you now call:

```
        q.evaluate_status()
```

You'll find that `self.assertEqual(q.overall_status.status, Status.PASS)`

If you append a metric to one of the evaluations that is set to `Status.PENDING` or `FAIL` the evaluation status and the overall status will subsequently resolve to that state:

```
        # Add a pending metric to the first evaluation
        q.evaluations[0].qc_metrics.append(
            QCMetric(
                name="Drift map pass/fail",
                value=False,
                description="Manual evaluation of whether the drift map looks good",
                reference="s3://some-data-somewhere",
                metric_status_history=[
                    QCStatus(
                        evaluator="Automated", timestamp=datetime.fromisoformat("2020-10-10"), status=Status.PENDING
                    )
                ],
            )
        )

        q.evaluate_status()
        self.assertEqual(q.overall_status.status, Status.PENDING)
```

2024-09-25 04:42 UTC, saskiad commented on src/aind_data_schema/core/quality_control.py
> +    timestamp: datetime = Field(..., title="Status date", default_factory=datetime.now)
let's use the `AwareDatetimeWithDefault` consistent with rest of schema.
(I should have pointed this out earlier)

2024-09-25 04:43 UTC, saskiad commented on src/aind_data_schema/core/quality_control.py
> +    timestamp: datetime = Field(..., title="Status date", default_factory=datetime.now)
I also don't know the the default to now should be in the schema but rather in the qc app

2024-09-25 04:44 UTC, saskiad commented on src/aind_data_schema/core/quality_control.py
> +        return self.metric_status_history[-1]
this assumes that the list will maintain a chronological order. Do we know if this behavior is true? I feel like JSON moves things into weird orders. But if the python list is in the right order, then json doesn't matter...

2024-09-25 04:47 UTC, saskiad requested changes
let's use the same datetime that we use throughout the schema. 

I'm still a little confused by the structure overall - I might have you explain it for me again (or look with fresh eyes in the morning)

2024-09-25 14:43 UTC, dbirman commented on src/aind_data_schema/core/quality_control.py
> +        return self.metric_status_history[-1]
I'm not sure if they do, but I'll add a test that does the round trip (pydantic -> json -> pydantic) and confirms that they stay in the same order.

If we ever have issues I'll add a check here that sorts to find the last timestamp

2024-09-26 21:01 UTC, dbirman commented
After discussion:

- [ ] Add to QCEvaluation an option to allow fails
- [ ] Add to app a display that says "3 Evaluations, 1 Passed with Failures"

2024-09-30 17:27 UTC, dbirman commented
Closes #1085

2024-10-01 21:59 UTC, dbirman commented
This PR now also closes two other issues that involved adding `asset_id` fields to QCEvaluation and adding a validator to QCMetric to make sure that a `QCStatus` object is included when pushed (and not just an empty list in metric_status_history)

2024-10-03 02:57 UTC, saskiad commented on src/aind_data_schema/core/quality_control.py
> +    allow_failed_metrics: bool = Field(default=False, title="Allow metrics to fail")
can we add a description that explains what this is for a bit - I think it will be confusing to people.

2024-10-03 02:58 UTC, saskiad commented on src/aind_data_schema/core/quality_control.py
> +    asset_id: Optional[str] = Field(default=None, title="DocDB asset ID that this evaluation is associated with")
Let's remove this from this PR. I have reservations about using asset_id in the metadata - largely because it's not something that exists in the schema. I'd prefer to resolve that separately from the rest of this

2024-10-03 03:00 UTC, saskiad requested changes
I want to deal with the asset id separately. Otherwise I think it looks good.

2024-10-03 23:11 UTC, saskiad approved these changes

2024-10-03 23:11 UTC, merged