1047 qc docs
AllenNeuralDynamics/aind-data-schema pull request #1075
Opened 2024-09-23 17:44 UTC by dbirman

This PR does two things:

1. Adds .md file support with myst-parser
2. Adds the QC documentation draft, it doesn't include an example workflow because that's blocked by the automated status PR. I'll add that later

2024-09-25 04:51 UTC, saskiad commented on docs/source/quality_control.md
> +The QC object reflects the state of the entire data asset and its status is set based on the worst status of its evaluations.
this means the overall status is set by the worst status of all the evaluations. but I don't think we want this. We can decide that some evaluations have different priorities. E.g. the tail video can fail but the data asset as a whole can pass.

2024-09-25 04:54 UTC, saskiad commented on docs/source/quality_control.md
> +## QC Portal
This should maybe be in a `Questions for AIND users` section as we do for some of the other sections (e.g. the Procedures)

2024-09-25 04:55 UTC, saskiad requested changes
I think the overall status needs a little more clarity - or perhaps I do, but want to resolve this before we publicize it as such.

2024-09-25 14:49 UTC, dbirman commented on docs/source/quality_control.md
> +The QC object reflects the state of the entire data asset and its status is set based on the worst status of its evaluations.
This is what I was suggesting in our meeting last week with the idea of "fail" vs "critical fail", where only a critical fail causes the parent evaluation/qc object to also fail. 

Other people have suggested other words for it like "flag" "warning" etc but it seems like we're converging on needing this concept in the status.

2024-09-25 19:10 UTC, dbirman commented
- [ ] Need to add more information about Reference URLs

2024-10-03 03:12 UTC, saskiad commented on docs/source/quality_control.md
> +- If any metric fails the evaluation fails (except when the `allow_failed_metrics` flag is set)
I think it would be valuable to unpack how we expect to use `allow_failed_metrics` - I anticipate people making wild assumptions about this and using it in different ways than we intend.

2024-10-03 03:14 UTC, saskiad commented on docs/source/quality_control.md
> +Make sure to annotate `QCEvaluation`s with the `Stage` and `Modality` they are related to.
This sounds like a suggestion while these are required fields, so phrase this along the lines of: 
Each `QCEvaluation` applies to a specific data `Modality` and `Stage` (e.g. raw data acquisition or different data processing steps) as specified.

2024-10-03 03:16 UTC, saskiad commented on docs/source/quality_control.md
> +Metrics have a status which is set by a rule, usually some function of the metric value. The rule should be encoded in the metric description. Metrics can be evaluated multiple times, in which case t
`description` - make it clear you mean in this field rather than in the name of the metric.

2024-10-03 03:17 UTC, saskiad commented on docs/source/quality_control.md
> +Metrics have a status which is set by a rule, usually some function of the metric value. The rule should be encoded in the metric description. Metrics can be evaluated multiple times, in which case t
maybe use `QCMetric` rather than metric - make it clear you are refering to the field/class rather than a broad concept.

2024-10-03 03:22 UTC, saskiad commented on docs/source/quality_control.md
> +If need to build evaluations for a _different_ data asset, for example making evaluations for a primary data asset that you are derived from, but need to be attached to that original asset, then you
I think this needs to be much clearer. What kind of evaluations of primary data come from derived results? I'm VERY VERY worried this is going to be abused, so if we don't establish what this is for, it is going to be chaotic.

I also wonder whether the `asset_id` (and I'm not stoked on using asset_id, and we can discuss separately) should be in the evaluation itself. Can it be somethign in the QCportal that points the evaluation without ending up in the evaluation itself? (A big part of my concern is that there's no asset_id information. So if I see a QC evaluation in a file that says it's for a given asset_id, I have no idea whether that asset_id is the asset I'm looking at or is a derived asset from the one I'm looking at or something else. I'd rather use asset name - that's at least in the schema. 
BUT my gusenseess this is so the QCportal attaches the evaluation to the right asset, and can be part of the process without being in the evaluation itself.

2024-10-03 03:24 UTC, saskiad requested changes
a few places need a smidge more clarity.

2024-10-03 21:27 UTC, saskiad approved these changes

2024-10-03 21:27 UTC, merged