Support multi session quality control by tracking metric provenance
AllenNeuralDynamics/aind-data-schema pull request #1106
Opened 2024-10-16 03:36 UTC by dbirman

This PR adds a new Stage "MULTI_ASSET" and `provenance` field that differentiate QC that is about this data asset from QC that was calculated in a way that depended on some external data asset. The names of those assets are expected to be included in the provenance list.

We can change the names multi_asset and provenance if we decide we don't like them.

2024-10-16 18:10 UTC, jeromelecoq commented
I think this makes senes. I would try to distinguish "multi-asset" for "multi-modalies" somehow. I think you are thinking about "multi_sessions"?

2024-10-16 18:12 UTC, dbirman commented
> I think this makes senes. I would try to distinguish "multi-asset" for "multi-modalies" somehow. I think you are thinking about "multi_sessions"?

Yeah this would be multi-session. Multi-modal could be supported by changing the QCEvaluation modality to a list. I'll put that in this same PR and we'll see what people think

2024-10-16 18:25 UTC, seanmcculloch commented
I like this addition, and think it is a great way to document the relationship of data-assets on a per-metric basis.

To be clear, these QCMetrics will reside only in this multi-asset quality_control.json and will not get added to the respective single-asset quality_control.jsons, correct?

2024-10-16 18:29 UTC, bjhardcastle commented
In the title of `provenance` it says 
> "List of asset names that this metric depends on",

I think this would have to be asset IDs, no? 
AFAIK asset names aren't unique.

2024-10-16 18:34 UTC, dbirman commented
> In the title of `provenance` it says
> 
> > "List of asset names that this metric depends on",
> 
> I think this would have to be asset IDs, no? AFAIK asset names aren't unique.

The reason to prefer name is that it's human understandable and easier to search for, and also shared across the data asset on S3 and the record in DocDB. I think the intention is that names should be unique by the way (and we're going back and fixing names that are not unique!)

2024-10-16 19:24 UTC, saskiad commented on src/aind_data_schema/core/quality_control.py
> +        default=None,
Should the default be an empty List?

2024-10-16 19:26 UTC, saskiad commented on src/aind_data_schema/core/quality_control.py
> +        default=None,
is it worth having a validator so that when the stage is multi-asset it makes sure the list has length>1?

2024-10-16 19:28 UTC, saskiad commented on src/aind_data_schema/core/quality_control.py
> +        default=None,
and I'm not sure I like `provenance` as the name for this field. I think of provenance as the history of an asset or result. Maybe `evaluated_assets` or `related_assets`?

2024-10-16 19:28 UTC, saskiad requested changes
couple comments on `provenance`

2024-10-16 19:57 UTC, dbirman commented on src/aind_data_schema/core/quality_control.py
> +        default=None,
Yeah a validator is a good idea, I'll add that. I'll probably keep the default to None so that when the stage is not multi-asset the field is guaranteed to be blank.

2024-10-21 16:41 UTC, saskiad commented on src/aind_data_schema/core/quality_control.py
> +    MULTI_SESSION = "Multi-session"
no, this should be multi-asset.

2024-10-21 16:42 UTC, saskiad requested changes
stage should be multi-asset

2024-10-21 16:51 UTC, dbirman commented on src/aind_data_schema/core/quality_control.py
> +    MULTI_SESSION = "Multi-session"
Whoops thought we had discussed this and decided to change it, just a confusion

2024-10-21 16:55 UTC, saskiad commented on src/aind_data_schema/core/quality_control.py
> +    def validate_multi_session(cls, v):
validate_multi_asset

2024-10-21 16:55 UTC, saskiad commented on src/aind_data_schema/core/quality_control.py
> +                            f"Metric '{metric.name}' is in a single-session QCEvaluation"
asset

2024-10-21 16:55 UTC, saskiad requested changes
few more places

2024-10-21 17:21 UTC, saskiad approved these changes

2024-10-21 17:22 UTC, merged