Feat 69 default filename
AllenNeuralDynamics/aind-data-schema pull request #114
Opened 2022-12-10 02:14 UTC by mekhlakapoor

closes #69

2022-12-10 04:23 UTC, dyf requested changes
I'd like the examples to be very simple, so let's not include the stuff about checking dirpath.

2022-12-10 04:23 UTC, dyf commented on examples/aind_smartspim_instrument.py
> +inst.write_to_json(dir_path, "aind_smartspim")
Can we have the examples just do `write_to_json()`?

2022-12-10 04:23 UTC, dyf commented on src/aind_data_schema/base.py
> +    def write_to_json(cls, dir=os.getcwd(), optional_name=''):
Let's have `dir` default to `'.'`, I think.

2022-12-19 17:36 UTC, mekhlakapoor commented on examples/aind_smartspim_instrument.py
> +inst.write_to_json(dir_path, "aind_smartspim")
sure, but it wont create the example files as expected in the examples directory (for ex the extra naming)

2022-12-21 18:19 UTC, jtyoung84 approved these changes

2022-12-21 18:39 UTC, dyf approved these changes

2022-12-21 18:39 UTC, merged