Feat 1147 interoception
AllenNeuralDynamics/aind-data-schema pull request #1190
Opened 2024-12-09 22:16 UTC by saskiad

closes #1147

2024-12-10 21:35 UTC, saskiad commented on src/aind_data_schema/core/procedures.py
> +    pantent: bool = Field(default=True, title="Catheter patent")
patency = not patent, patent, only push, only pull

2024-12-10 21:40 UTC, saskiad commented on src/aind_data_schema/core/procedures.py
> +    injection: List[IntraperitonealInjection] = Field(..., title="IP injections")
remove injection fields

2024-12-15 01:10 UTC, saskiad commented on src/aind_data_schema/core/procedures.py
> +    where_performed: Annotated[Union[Organization.AIND, Organization.JAX],
https://github.com/AllenNeuralDynamics/aind-data-schema-models/pull/116

2024-12-17 23:23 UTC, dyf requested changes

2024-12-17 23:23 UTC, dyf commented on src/aind_data_schema/core/procedures.py
> +    procedure_time: Optional[AwareDatetimeWithDefault] = Field(default=None, title="Collection time")
title is wrong

2024-12-17 23:23 UTC, dyf commented on src/aind_data_schema/core/procedures.py
> +    start_date: date = Field(..., title="Start date")
maintenance only has a start date? feel like it should be `procedure_time` or something.

2024-12-17 23:23 UTC, dyf commented on src/aind_data_schema/core/procedures.py
> +    start_date: date = Field(..., title="Start date")
should this be `procedure_time` instead of `start_date`?

2024-12-17 23:23 UTC, dyf commented on src/aind_data_schema/core/procedures.py
> +    collection_time: AwareDatetimeWithDefault = Field(..., title="Collection time")
`procedure_time`?

2024-12-17 23:23 UTC, dyf commented on src/aind_data_schema/core/procedures.py
> +    start_date: date = Field(..., title="Start date")
`procedure_time`?

2024-12-17 23:41 UTC, saskiad commented on src/aind_data_schema/core/procedures.py
> +    collection_time: AwareDatetimeWithDefault = Field(..., title="Collection time")
it's a sub-procedure. It could just be `time` if you prefer

2024-12-17 23:42 UTC, saskiad commented on src/aind_data_schema/core/procedures.py
> +    start_date: date = Field(..., title="Start date")
it's the date.

2024-12-18 00:14 UTC, saskiad commented on src/aind_data_schema/core/procedures.py
> +    start_date: date = Field(..., title="Start date")
we only have date resolution on implants - especially when they are done offsite

2025-01-06 16:53 UTC, dyf commented on src/aind_data_schema/core/procedures.py
> +class BloodCollection(AindModel):
Should we call this `SampleCollection`? Seems like it would be useful for any volume-based collection.

2025-01-06 16:53 UTC, dyf commented on src/aind_data_schema/core/procedures.py
> +class BloodCollection(AindModel):
There could be a `SampleType` enum, maybe.

2025-01-06 16:53 UTC, dyf commented on src/aind_data_schema/core/procedures.py
> +    targeted_vessel: MouseAnatomicalStructure.BLOOD_VESSELS = Field(..., title="Targeted blood vessel")
on the off chance we want to do catheter implants in other structures in the future, maybe we call this field `target` or `targeted_structure`?

2025-01-06 19:52 UTC, dyf approved these changes

2025-01-06 19:56 UTC, merged