feat: use "tag" reusable workflow for autobump
AllenNeuralDynamics/aind-data-schema pull request #124
Opened 2022-12-20 21:17 UTC by aricAI

2022-12-21 19:37 UTC, jtyoung84 commented on .github/workflows/tag.yml
> +      SERVICE_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
I think this might need to be set to `secrets.SERVICE_TOKEN`?

2022-12-21 19:39 UTC, jtyoung84 requested changes
The publishing step might need to be modified to pull in the changes pushed to the main branch. Something like:
```
 publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull latest changes
        run: git pull origin main
...
```

2022-12-22 21:04 UTC, aricAI commented on .github/workflows/tag.yml
> +      SERVICE_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
Fixed

2022-12-22 21:05 UTC, aricAI commented
Added pull on publish

2022-12-23 00:11 UTC, jtyoung84 commented
> Added pull on publish

You might need to push the change to the remote repo

2022-12-23 00:17 UTC, jtyoung84 approved these changes

2022-12-23 00:17 UTC, merged