updates to image acquisition
AllenNeuralDynamics/aind-data-schema pull request #132
Opened 2022-12-22 05:57 UTC by dyf

resolves #129

2022-12-22 06:22 UTC, dyf commented
@adamkglaser @saskiad I tried a different way of handling units so they show up in the JSON. Free to say no.

2022-12-22 18:44 UTC, adamkglaser commented
These updates look good to me. 
* I think it is good for human readability to dump units into the JSON. 
* Where is this being handled -> in the base class? Laser power should also have a unit associated with it -> mW.
* For the "DAQ" parameters since these will differ (or be non-existent) for some other imaging datasets, we can just have _unit at the end of the variable name for the units? These will not need to be ingested by any post-processing codes. Tracking these is more for completeness and for debugging purposes if needed.
* Should we stick with having the axis letter first in variable names? So size_x -? x_size etc.?
* Is it needed to specify how the axes are physically being used? For all SPIM systems I think this would break down into "slow tiling axis", "fast tiling axis", "scanning axis".
* I agree with your comment that lets just stick with X, Y, Z in the acquisition mapping to X, Y, Z in the instrument schema. And let's just ignore our remapping of hardware stage lettered axes to the X, Y, Z in the instrument schema. It can maybe be mentioned in the notes of the motorized stages of the instrument schema.
* I agree with @miketaormina that immersion medium should be captured in the acquisition schema. Perhaps as an added field in Acquisition(). This could be a ```str``` for the medium name, and perhaps also a ```float``` for the measured RI of the medium.
* For the smartSPIM as well, since there are potentially multiple objective lenses, we should also add a field for the objective lens used for this particular acquisition. What is the best way to handle this to map consistently with the instrument schema?
* Thinking forward to the diSPIM, we should add a field for the angle between the light-sheet and the "scanning axis" defined above. For the exaSPIM/smartSPIM this is 90 deg. but is 45 deg for the diSPIM. Presumably we'd want to capture this in such a way that it could be pulled by post-processing code to know how to apply deskewing. Based on this I think we should add a field to Tile() for light_sheet_angle (?) in units of deg.

2022-12-22 19:15 UTC, adamkglaser commented
Looking ahead towards integrating with OME-Zarr. We should:

1. Make sure that our ```Axis``` definition has enough information to unambiguously enable definition of axes as specified by OME-NGFF. https://ngff.openmicroscopy.org/latest/#axes-md.
2. Make sure that our ```TilePosition``` definition similar can map onto the ```Translation``` coordinate transform specified by OME-NGFF. https://ngff.openmicroscopy.org/latest/#trafo-md.
3. Make sure that our ```VoxelSize``` definition can map onto the ```Scale``` coordinate transform specified by OME-NGFF. https://ngff.openmicroscopy.org/latest/#trafo-md.
4. We can then store the rest of our acquisition JSON file with a ```layout``` we decide upon, similar to the scheme proposed by bioformats. https://ngff.openmicroscopy.org/latest/#bf2raw.

2023-01-03 17:43 UTC, miketaormina approved these changes
This all looks reasonable to me.

Edit: I would have restricted approval if I had known only one of us was required. ExaSPIM edits should be approved by Adam.

2023-01-03 21:08 UTC, adamkglaser approved these changes
Looks good to me as well!

2023-01-07 00:40 UTC, saskiad commented on examples/exaspim_acquisition.py
> +                laser_wavelength=488,
this needs units. same with laser_power below

2023-01-07 00:40 UTC, saskiad commented on examples/exaspim_acquisition.py
> +                laser_wavelength=488,
oh - or not? this is the .py file.

2023-01-07 00:42 UTC, saskiad commented on src/aind_data_schema/imaging/acquisition.py
> +        title="List of objectives used in this acquisition. If null, all objectives in instrument were used.",
I really am opposed to secret codes. If all objectives are used, there should be a list of all objectives.

2023-01-07 00:44 UTC, saskiad commented on src/aind_data_schema/imaging/acquisition.py
> -    x_start_um: float
did this info move somewhere else that I don't see?

2023-01-07 00:44 UTC, saskiad commented on src/aind_data_schema/imaging/acquisition.py
> -    tile_overlap_x: Optional[float] = Field(None, title="Tile overlap x (percent)", ge=0, le=100)
ditto this section? are we just not using it anymore? Don't we need it?

2023-01-07 00:51 UTC, saskiad commented on src/aind_data_schema/imaging/acquisition.py
> +    """3D scale transform"""
these classes need better descriptions to explain what they are

2023-01-07 00:52 UTC, saskiad commented on src/aind_data_schema/imaging/acquisition.py
> +    scale: conlist(float, min_items=3, max_items=3) = Field(..., title="3D scale parameters")
add units

2023-01-07 00:56 UTC, saskiad requested changes
minor changes

2023-01-07 06:48 UTC, dyf commented on src/aind_data_schema/imaging/acquisition.py
> +    scale: conlist(float, min_items=3, max_items=3) = Field(..., title="3D scale parameters")
scale is unitless. The `Axis` model has units.

2023-01-07 06:55 UTC, dyf commented on src/aind_data_schema/imaging/acquisition.py
> +        title="List of objectives used in this acquisition. If null, all objectives in instrument were used.",
deal

2023-01-07 06:55 UTC, dyf commented on src/aind_data_schema/imaging/acquisition.py
> +    """3D scale transform"""
done

2023-01-07 06:56 UTC, dyf commented on src/aind_data_schema/imaging/acquisition.py
> -    tile_overlap_x: Optional[float] = Field(None, title="Tile overlap x (percent)", ge=0, le=100)
this is handled by coordinate transformations now

2023-01-08 20:15 UTC, saskiad approved these changes

2023-01-09 16:07 UTC, merged