Bug 136 snakecase
AllenNeuralDynamics/aind-data-schema pull request #137
Opened 2022-12-24 03:05 UTC by mekhlakapoor

closes #136

2022-12-26 20:08 UTC, jtyoung84 commented on src/aind_data_schema/base.py
> +        for base in cls.__bases__:
It doesn't look like you need a for loop here. If it's assumed that AindCoreModel will eventually be the only item in the list, you can rewrite this as something like:
```
bases = cls.__bases__
if not bases:
  # Handle weird case where this degenerates to an empty list
  # log a warning or error and return cls?
elif AindCoreModel is bases[0]:
  return cls
else:
  return self._get_direct_subclass(bases[0])
```
This function is small and simple enough to leave it as it is. There are a lot of considerations when using recursion though (look up tail recursion for example and max iterations for recursion in python). This function would be easier to maintain if it was written as a while loop though. It'd have the added benefit of being a static method and returning a string instead of class.

2022-12-26 20:14 UTC, jtyoung84 commented on tests/test_base.py
> +        rd = RawDataDescription.construct()
Can you add several more test cases? You can loop through them like:
```
test_models = [(RawDataDescription, "data_description.json"), (Subject, "subject.json"),...]
for model, expected_name in test_models:
   m = model.construct()
   actual_name = m._get_default_filename()
   self.assertEqual(expected_name, actual_name)
```

2022-12-26 20:16 UTC, jtyoung84 requested changes
Add more examples in the unit test.
Handle edge case where list might be empty in `_get_default_filename()`
Reconsider using recursion, although I'll probably approve it if you don't want to change it.

2022-12-28 20:42 UTC, jtyoung84 commented on src/aind_data_schema/base.py
>      def _get_default_filename(self):
It'd be nice if this was a static method so that it can be called without constructing an instance.

2023-01-04 01:20 UTC, jtyoung84 approved these changes

2023-01-04 04:10 UTC, dyf requested changes
small comment about log message

2023-01-04 04:10 UTC, dyf commented on src/aind_data_schema/base.py
> +            logging.error(f"Unable to construct filename for {pydantic_class}")
this should probably more like "Unable to find direct AindCoreModel subclass" or something.

2023-01-04 18:54 UTC, dyf approved these changes
LGTM!

2023-01-04 18:54 UTC, merged