Consolidate device classes; update ephys schemas
AllenNeuralDynamics/aind-data-schema pull request #138
Opened 2022-12-30 23:45 UTC by jsiegle

Lots of changes here, happy to chat more about any of them! Since there are also some changes to `ophys_rig.py` and `instrument.py`, the ophys and imaging teams should be consulted before merging.

### Consolidating classes across projects

There were a number of classes (e.g. `Laser`, `Camera`) that were duplicated across modules. I moved these to `devices.py` and made sure they contained all of the original fields were present in the merged version. This should help ensure that schema are more consistent across projects. I would recommend putting each device type in a separate file (e.g. `lasers.py`, `cameras.py`), but I didn't want to make that change yet. There are also some classes that will be needed across projects that still live in the ephys rig schema (e.g. `HarpDevice`, `MousePlatform`). We should probably move these out sooner rather than later.

### Updated DAQ conventions

Rather than linking each device to one DAQ channel, I've changed it so each DAQ channel is associated with one device. I think this is better because there are some devices (e.g. lenses) that don't have DAQ channels, and some devices that have multiple DAQ channels. Ideally there could be some validation step to ensure that each DAQ channel refers to a device that exists elsewhere in the rig description, but this may be tricky.

### Device-specific manufacturer enums

Each device type in `devices.py` now has a separate manufacturer enum. This is not strictly necessary, but it will make it much easier to manually enter new devices. After many years of adding devices to rigs, the list of all manufacturers will become quite long.

### Naming devices

Devices such as probes and cameras are now named using open-ended strings rather than enums, because I don't think consecutive letter-based naming conventions are going to give us sufficient flexibility. This requires that whoever is creating the session JSON checks that data stream names match devices in the rig JSON. Eventually, it would be great if the form could ingest the rig JSON and display all of the valid stream names.

### Other changes

I tried to avoid using `type` as a field name, because this is a Python built-in function. Same with `filter`, but I didn't change that yet.

### Example files

Here are two example JSON files I generated with the latest changes:

[ephys_rig.json](https://github.com/AllenNeuralDynamics/aind-data-schema/files/10326500/ephys_rig.txt)
[ephys_session.json](https://github.com/AllenNeuralDynamics/aind-data-schema/files/10326501/ephys_session.txt)

2023-01-04 00:23 UTC, saskiad commented on src/aind_data_schema/ephys/ephys_session.py
> +    RF_MAPPING = "Receptive field mapping"
is this a data stream?

2023-01-04 04:46 UTC, dyf reviewed
Saskia is approver, added some thoughts.

2023-01-04 04:46 UTC, dyf commented on src/aind_data_schema/device.py
>  class DeviceBase(AindModel):
@jsiegle I think the refactor of DAQ channels would mean that `Device` can be deleted and `DeviceBase` renamed to `Device`.  Is that correct?

2023-01-04 04:46 UTC, dyf commented on src/aind_data_schema/device.py
> +    optimized_wavelength_range: Optional[str] = Field(
do we want this to be a string?

2023-01-04 04:46 UTC, dyf commented on src/aind_data_schema/device.py
> +    device_name: Optional[str] = Field(None, title="Device name")
I don't think `name` is a keyword - can we just use `name` throughout, unless a model has multiple names to keep track of?

2023-01-04 04:46 UTC, dyf commented on src/aind_data_schema/device.py
> +    THORLABS = "Thorlabs"
Wondering if we can refer to `Manufacturer.THORLABS` here and other places where the same manufacturer is in multiple enums to reduce number of spelling mistakes.

2023-01-04 04:46 UTC, dyf commented on src/aind_data_schema/ephys/ephys_session.py
> +    cameras: List[Camera] = Field(..., title="Cameras", unique_items=True)
This is just a list of names.  Let's just make `Stream.cameras` it a list of strings and get rid of `ephys_session.Camera`?

2023-01-04 17:14 UTC, saskiad commented on src/aind_data_schema/ephys/ephys_session.py
> +    start_time: datetime = Field(..., title="Stream start time")
I think we still need to differentiate stream start time and session start time. Same for stop time. While it should be clear because this is within the stream class, I think it's better to disambiguate them

2023-01-04 17:17 UTC, saskiad commented on src/aind_data_schema/ephys/ephys_session.py
> -    tip_targeted_structure: str
why are we removing the tip targeted structure?

2023-01-04 17:19 UTC, saskiad commented on src/aind_data_schema/ephys/ephys_session.py
> +class DAQ(AindModel):
I'm a little confused about why we're adding this here. there is no session specific configuration information, just which daq (and camera) is used. Correct? And that already lives in the rig schema. No?

2023-01-04 17:19 UTC, saskiad commented on src/aind_data_schema/ephys/ephys_session.py
> +    daqs: List[DAQ] = Field(..., title="DAQs", unique_items=True)
see above comment

2023-01-04 17:20 UTC, saskiad commented on src/aind_data_schema/ephys/ephys_session.py
> +class LaserModule(ManipulatorModule):
this is missing wavelength and power

2023-01-04 17:31 UTC, saskiad commented on src/aind_data_schema/device.py
> +    """Camera manufacturer"""
Lens manufacturer?

2023-01-04 17:32 UTC, saskiad commented on src/aind_data_schema/device.py
> +    SMF = "SMF"
what is SMF and MMF?

2023-01-04 17:33 UTC, saskiad commented on src/aind_data_schema/device.py
> +    camera_manufacturer: CameraManufacturer = Field(..., title="Camera manufacturer")
manufacturer already is part of the device class

2023-01-04 17:38 UTC, saskiad commented on src/aind_data_schema/device.py
> +    sample_rate: Optional[float] = Field(-1.0, title="DAQ channel sample rate (Hz); -1 = event-based sampling", units="Hz")
we need a different way to indicate event based samplling.

2023-01-04 19:16 UTC, jsiegle commented on src/aind_data_schema/device.py
> +    sample_rate: Optional[float] = Field(-1.0, title="DAQ channel sample rate (Hz); -1 = event-based sampling", units="Hz")
How about adding a boolean field for `event_based_sampling`?

2023-01-04 19:21 UTC, jsiegle commented on src/aind_data_schema/device.py
> +    """Camera manufacturer"""
Yep, that's a mistake

2023-01-04 19:24 UTC, jsiegle commented on src/aind_data_schema/ephys/ephys_session.py
> +class LaserModule(ManipulatorModule):
This info is in the rig JSON (there is a list of Lasers associated with each LaserModule)

2023-01-04 19:25 UTC, saskiad commented on src/aind_data_schema/device.py
> +    camera_manufacturer: CameraManufacturer = Field(..., title="Camera manufacturer")
oh I see ... this way it points to a specific list... hmmm

2023-01-04 19:27 UTC, jsiegle commented on src/aind_data_schema/ephys/ephys_session.py
> +class DAQ(AindModel):
The idea is that the rig JSON contains information about all the physical connections on the rig, and the session JSON indicates which devices are being recorded in each Stream. So the DAQ/Camera/EphysProbe class in the session JSON just provide an ID that can be used to look up the relevant hardware info in the rig JSON.

2023-01-04 19:28 UTC, saskiad commented on src/aind_data_schema/ephys/ephys_session.py
> +class LaserModule(ManipulatorModule):
I think the rig json has maximum power, which is different from the actual power used. Wavelength is in both, but is optional in the rig for situations where it is tunable.

2023-01-04 19:28 UTC, jsiegle commented on src/aind_data_schema/ephys/ephys_session.py
> +    start_time: datetime = Field(..., title="Stream start time")
That's fine, I can make this change

2023-01-04 19:30 UTC, jsiegle commented on src/aind_data_schema/ephys/ephys_session.py
> +    cameras: List[Camera] = Field(..., title="Cameras", unique_items=True)
I think that's fine for now. The reason to make it a class would be if the session JSON creator might eventually ingest the rig JSON and provide a list of device-type-specific names for the user to choose from.

2023-01-04 19:32 UTC, jsiegle commented on src/aind_data_schema/device.py
>  class DeviceBase(AindModel):
I think so. I kept it as `DeviceBase` was to encourage people to make more specific classes for different device types.

2023-01-04 19:33 UTC, jsiegle commented on src/aind_data_schema/device.py
> +    optimized_wavelength_range: Optional[str] = Field(
I copied this from `ophy_rig.py` – we should consult with the ophys team about this, but it may be better to make this a list of `ints` (or perhaps have separate fields for upper + lower bounds)

2023-01-04 19:34 UTC, jsiegle commented on src/aind_data_schema/device.py
> +    device_name: Optional[str] = Field(None, title="Device name")
Yeah, that should simplify things

2023-01-04 19:37 UTC, jsiegle commented on src/aind_data_schema/device.py
> +    THORLABS = "Thorlabs"
When I was creating the rig JSON using the web interface, it was annoying to search through a long list of manufacturer names for every device. Not that terrible in the scheme of things, but having a shorter list would improve the user experience. If we do split it up, I agree with David that we should use existing `enum` values if possible.

2023-01-04 19:38 UTC, saskiad commented on src/aind_data_schema/device.py
> +    sample_rate: Optional[float] = Field(-1.0, title="DAQ channel sample rate (Hz); -1 = event-based sampling", units="Hz")
yeah that works

2023-01-04 19:38 UTC, jsiegle commented on src/aind_data_schema/ephys/ephys_session.py
> +class DAQ(AindModel):
As David pointed out above, the ones in the session JSON don't necessarily have to be separate classes

2023-01-04 19:39 UTC, jsiegle commented on src/aind_data_schema/device.py
> +    camera_manufacturer: CameraManufacturer = Field(..., title="Camera manufacturer")
I made this a separate field so we could use a camera-specific device `enum`. But it sounds like it's possible to just use a subset of the existing manufacturer `enum` instead.

2023-01-04 19:43 UTC, saskiad commented on src/aind_data_schema/device.py
> +    THORLABS = "Thorlabs"
I'm mostly worried about maintaining different lists and adding Thorlabs to Filters but forgetting to add it to lenses, etc. But a long list is also a pain...

2023-01-04 19:44 UTC, saskiad commented on src/aind_data_schema/device.py
> +class FilterManufacturer(Enum):
if we do keep these separate, each list needs an Other option

2023-01-04 19:57 UTC, saskiad commented on src/aind_data_schema/device.py
> +    sensor_format: Optional[str] = Field(None, title='Size of the sensor (e.g. 1/2.9")')
what are the units for size?

2023-01-04 19:58 UTC, saskiad commented on src/aind_data_schema/device.py
>  class DAQ(DeviceBase):
Can we call this "DAQDevice" or something? Calling it "DAQ" implies to me that it is the DAQ itself, rather than a device that is connected via the DAQ.

2023-01-04 21:06 UTC, jsiegle commented on src/aind_data_schema/device.py
> +    THORLABS = "Thorlabs"
It looks like there is an easy way to define a field as a subset of a larger `enum`: https://github.com/pydantic/pydantic/discussions/4232

I will make this change and see if it works

2023-01-04 21:07 UTC, jsiegle commented on src/aind_data_schema/ephys/ephys_session.py
> +    cameras: List[Camera] = Field(..., title="Cameras", unique_items=True)
Actually, I think we should keep these as separate classes, because they may need to hold session-specific metadata (e.g. camera exposure time)

2023-01-04 21:09 UTC, jsiegle commented on src/aind_data_schema/device.py
> +    sensor_format: Optional[str] = Field(None, title='Size of the sensor (e.g. 1/2.9")')
There is not a standard unit here...e.g. 1/2.9" and 35 mm sensors are both common

2023-01-04 21:21 UTC, jsiegle commented
@saskiad and @dyf, the most recent commit addresses many of the issues you raised, please take a look at the latest code

2023-01-05 01:12 UTC, saskiad commented on src/aind_data_schema/device.py
> +    device_name: Optional[str] = Field(None, title="Device name")
device_name is going to be a really tricky part to implement cleanly. I'm anticipating situations where we have "camera_1" and "camerab" and really messy/confusing names floating around. And this organization of having the list of DAQ channels (rather than specify the DAQ channel(s) within the device) really hinges on that. I think this is why I prefer putting the DAQ channels in the device instead - and we can definitely flesh that out so it's more detailed.

2023-01-05 01:26 UTC, jsiegle commented on src/aind_data_schema/device.py
> +    device_name: Optional[str] = Field(None, title="Device name")
Can we chat about this after the workshop planning meeting tomorrow? I think sketching out the dependencies on a whiteboard would be helpful

2023-01-05 23:45 UTC, saskiad commented on src/aind_data_schema/device.py
> +    sensor_format: Optional[str] = Field(None, title='Size of the sensor (e.g. 1/2.9")')
we need to add a units filed for this then - we can do it after the PR

2023-01-05 23:46 UTC, saskiad commented on src/aind_data_schema/device.py
> +    sample_rate: Optional[float] = Field(-1.0, title="DAQ channel sample rate (Hz); -1 = event-based sampling", units="Hz")
Can you add this boolean field?

2023-01-05 23:49 UTC, jsiegle commented on src/aind_data_schema/device.py
> +    sample_rate: Optional[float] = Field(-1.0, title="DAQ channel sample rate (Hz); -1 = event-based sampling", units="Hz")
Done!

2023-01-05 23:53 UTC, saskiad commented on src/aind_data_schema/ephys/ephys_session.py
> +    subject_id: Optional[int] = Field(1, title="Subject ID; 1 = Test subject")
remove the Test subject. I'm really against having secret codes hidden in there.

2023-01-05 23:54 UTC, saskiad commented on src/aind_data_schema/ephys/ephys_session.py
> +    stream_start_time: datetime = Field(..., title="Session start time")
this appears backwards - this should be session start time, right?

2023-01-05 23:56 UTC, saskiad requested changes
There are a couple of small things to fix - all super minor

2023-01-06 00:19 UTC, jsiegle commented
Fixed!

2023-01-06 00:35 UTC, saskiad commented on src/aind_data_schema/ephys/ephys_session.py
> +    subject_id: Optional[int] = Field(1, title="Subject ID; 1 = Test subject")
I'm confused how the subject ID was removed...

2023-01-06 00:36 UTC, saskiad commented on src/aind_data_schema/ephys/ephys_session.py
> +    subject_id: Optional[int] = Field(1, title="Subject ID; 1 = Test subject")
nevermind - github was hiding that section from me.

2023-01-06 00:36 UTC, saskiad approved these changes

2023-01-06 01:10 UTC, merged