Ephys example scripts
AllenNeuralDynamics/aind-data-schema pull request #143
Opened 2023-01-08 20:22 UTC by jsiegle

Add examples scripts and generated JSON files for `ephys_session` and `ephys_rig`

2023-01-09 16:11 UTC, dyf requested changes

2023-01-09 16:11 UTC, dyf commented on examples/ephys_session.py
> +with open("ephys_session.json", "w") as outfile:
Can you replace this with `session.write_standard_file()`?

2023-01-09 16:11 UTC, dyf commented on examples/ephys_session.py
> +from aind_data_schema.ephys.ephys_session import *
Can you `import ... as es` instead to be consistent with the other examples?

2023-01-09 16:11 UTC, dyf commented on examples/ephys_rig.py
> +with open("ephys_rig.json", "w") as outfile:
Can you replace this with `rig.write_standard_file()`?

2023-01-09 16:12 UTC, dyf commented on examples/ephys_session.py
> +from aind_data_schema.ephys.ephys_session import *
(the `import *` is why the CI is breaking right now)

2023-01-09 19:07 UTC, dyf commented
@jsiegle almost there - now you need to regenerate your .json files.

2023-01-09 23:41 UTC, jsiegle commented
Hmm...I regenerated but it's still failing. And the expected vs. actual JSON strings look the same. Can you tell what the difference is?

2023-01-10 01:14 UTC, dyf commented
@jsiegle It's a couple things.  
1) the datetimes don't match because you are using `datetime.now()`.  Can you fix the time like this? https://github.com/AllenNeuralDynamics/aind-data-schema/blob/83de3c9b189e7a5fd425af385bf79b3287ddb74b/examples/subject.py#L6
2) subject ID should be a string, not an integer.  I'm not sure why that's rendering out as an integer locally and a string in the CI.

2023-01-10 18:13 UTC, jsiegle commented
Thanks, it's passing now!

2023-01-10 20:51 UTC, dyf approved these changes

2023-01-10 20:51 UTC, merged