Make MRI a separate acquisition session and removed from procedures
AllenNeuralDynamics/aind-data-schema pull request #199
Opened 2023-03-05 17:55 UTC by saskiad

address issue #198

2023-03-06 19:34 UTC, dyf requested changes

2023-03-06 19:34 UTC, dyf commented on src/aind_data_schema/ephys/mri_session.py
> +class MriScan(AindModel):
call this `MriSession` to match the file name. also, make it inherit from `AindCoreModel`. Then delete `describedBy` - it comes for free when you inherit from `AindCoreModel`.

2023-03-06 19:34 UTC, dyf commented on src/aind_data_schema/ephys/mri_session.py
> +    scan_sequence: MriScanSequence = Field(..., title="Scan sequence")
add a `scanner` Device here?

2023-03-07 22:09 UTC, dyf requested changes

2023-03-07 22:09 UTC, dyf commented on src/aind_data_schema/ephys/mri_session.py
> +    resolution: float = Field(..., title="Resolution")
add `resolution_unit`, presumably mm.

2023-03-07 22:09 UTC, dyf commented on src/aind_data_schema/ephys/mri_session.py
> +    start_date: date = Field(..., title="Start date")
should these be `session_start_time` and `session_end_time` to match `ephys_session`?

2023-03-08 01:58 UTC, saskiad commented on src/aind_data_schema/ephys/mri_session.py
> +    resolution: float = Field(..., title="Resolution")
added axes from imaging acquisition that has the unit included

2023-03-08 18:14 UTC, dyf approved these changes

2023-03-08 18:14 UTC, merged