adds new modalities
AllenNeuralDynamics/aind-data-schema pull request #219
Opened 2023-03-14 17:02 UTC by dyf

resolves #218

2023-03-14 17:12 UTC, saskiad commented on src/aind_data_schema/data_description.py
> +    FIP = "FIP"
Can you define was FIP is?

2023-03-14 17:12 UTC, saskiad commented on src/aind_data_schema/data_description.py
> +    HSFP = "HSFP"
same here - it would be good to have some of these acronyms unpacked a bit more.

2023-03-14 17:16 UTC, saskiad requested changes
I want to clean up some of our acronyms when they aren't obvious. Can you define these modalities?

2023-03-15 21:03 UTC, dyf commented
@saskiad can we add these now and handle adding long names in a separate PR.  This will impact our data entry form, I think, so will take some care to do properly.

2023-03-15 21:38 UTC, saskiad approved these changes

2023-03-15 21:38 UTC, merged