Adding opto stim to ophys session schema
AllenNeuralDynamics/aind-data-schema pull request #229
Opened 2023-03-22 20:48 UTC by saskiad

2023-03-22 20:49 UTC, saskiad commented
closes issue #227

2023-03-22 20:50 UTC, saskiad commented
My hunch is opto stim is more of a protocol than metadata, but I don't think it will work as a protocols.io protocol, so might as well add it here.

2023-03-22 20:52 UTC, mekhlakapoor approved these changes
looks good, thanks Saskia!

2023-03-22 21:59 UTC, saskiad commented
I'm going to make this something that can be used in ephys too

2023-03-23 02:20 UTC, saskiad commented
@dyf I'm going to move this into a place where we can use it for both ophys and ephys - should I make a stim class? or something else?

2023-03-23 15:33 UTC, dyf commented
> @dyf I'm going to move this into a place where we can use it for both ophys and ephys - should I make a stim class? or something else?

Yes, I think a generic stimulus class makes sense. Would presumably be a top-level thing. Is there an existing stimulus ontology we can crib from? NWB maybe has more now than it did back in the day.

2023-03-23 15:35 UTC, dyf commented
https://github.com/SciCrunch/NIF-Ontology/blob/estim/ttl/stimulation.ttl is what NWB's site points to.  They refer to a stimulus ontology working group: https://www.incf.org/sig/incf-working-group-electrophysiology-stimulation-ontology.

2023-03-23 15:45 UTC, dyf requested changes
see other comments re: stimulus model, and TimeUnit

2023-03-31 20:52 UTC, saskiad commented
Let's make a new issue about how to incorporate NIF ontology into this - also for the behavior schema. I think that's a bigger question - so let's start with this and make it better.

2023-03-31 22:00 UTC, dyf requested changes

2023-03-31 22:00 UTC, dyf commented on src/aind_data_schema/stimulus.py
> +    stimulus_name: str = Field(..., title="Stimulus name")
Should this rather be a base class and `OptoStim` a subclass?

2023-04-17 18:16 UTC, dyf requested changes

2023-04-17 18:16 UTC, dyf commented on src/aind_data_schema/ephys/ephys_session.py
> +    stimulus: OptoStim = Field(..., title="Stimulus")
might as well turn this into a union (even if it has just one option), since there will be other stims coming

2023-04-17 18:16 UTC, dyf commented on src/aind_data_schema/ephys/ephys_session.py
> +    stimulus: Optional[List[Stim]] = Field(None, title="Stimulus")
Does this need to be per stream? I had assumed it would be per session.

2023-04-17 18:16 UTC, dyf commented on src/aind_data_schema/ophys/ophys_session.py
> +    stimulus: Optional[List[Stim]] = Field(None, title="Stimulus")
I think NWB calls this `stimulus_presentations`

2023-04-17 18:16 UTC, dyf commented on src/aind_data_schema/ophys/ophys_session.py
> +    stimulus: OptoStim = Field(..., title="Stimulus")
make this a Union?

2023-04-17 19:00 UTC, saskiad commented
there's going to be a conflict in the procedures file - we don't want to lose the transcriptomics stuff.

2023-04-17 19:34 UTC, saskiad commented
I don't understand how the main got merged into feat_opto

2023-04-17 19:54 UTC, dyf requested changes

2023-04-17 19:54 UTC, dyf commented on src/aind_data_schema/ophys/ophys_session.py
> +class Stim(AindModel):
Sorry, had one other thought.  Since this is duplicated in both of the sessions, how about we call this `StimulusPresentation` and move it into `../stimulus.py`?

2023-04-17 20:22 UTC, saskiad commented on src/aind_data_schema/ophys/ophys_session.py
> +class Stim(AindModel):
why be logical?!?

2023-04-18 19:13 UTC, dyf approved these changes

2023-04-18 20:22 UTC, merged