Small ophys updates
AllenNeuralDynamics/aind-data-schema pull request #264
Opened 2023-04-20 23:42 UTC by saskiad

closes #263

2023-04-20 23:50 UTC, saskiad commented
camera assembly name already being used to specify the purpose - eg. Eye Camera vs Body Camera. BUT, I think it would be helpful to have a specific field with an ENUM that can be better used to identify cameras

2023-04-21 00:04 UTC, saskiad commented
Until I have other field to add for microscope, I'm not adding it as a specific class and it will need to be an additional device. If there are other fields, then we can add it.

2023-04-21 15:49 UTC, dyf requested changes

2023-04-21 15:49 UTC, dyf commented on src/aind_data_schema/device.py
> +class CameraTarget(Enum):
I recently polled for behavior videos, if you want to update the Enum:
![image](https://user-images.githubusercontent.com/1854389/233679973-ddfa527a-4c45-4d7b-b0e3-9099395d2062.png)

2023-04-21 15:53 UTC, dyf commented on src/aind_data_schema/device.py
> +class CameraTarget(Enum):
I think the only additions would be side vs body and tongue.

2023-04-21 16:03 UTC, saskiad commented on src/aind_data_schema/device.py
> +class CameraTarget(Enum):
Thanks. This allows confirms the need to have this field as relying on names won't yield useful searches!

2023-04-21 16:22 UTC, dyf approved these changes

2023-04-21 16:33 UTC, merged