Feat 2p rig schema update
AllenNeuralDynamics/aind-data-schema pull request #266
Opened 2023-04-21 20:56 UTC by arielleleon

@saskiad @dyf  @DowntonCrabby 

Added a few components to the device module and created an assembly module to group device components. The assembly classes have not been added to the rig b/c we would like your feedback before getting too far.

2023-04-21 22:00 UTC, dyf reviewed
Some preliminary thoughts.  @saskiad should review further.

2023-04-21 22:00 UTC, dyf commented on src/aind_data_schema/device.py
> +class Computer(AindModel):
I'm not sure we need this class. Perhaps just `DAQDevice.computer_name = str` would suffice.

2023-04-22 00:49 UTC, saskiad requested changes
I'm generally not fully sure having a separate assembly.py file makes sense. I'm happy to discuss to think it through together, but my instinct right now (also, my brain is a little fried from a long day) is to keep these in device.py

2023-04-22 00:49 UTC, saskiad commented on src/aind_data_schema/assembly.py
> +class RelativePosition(AindModel):
why not import this from device.py? we try to avoid redefining things in multiple places to help keep things aligned

2023-04-22 00:49 UTC, saskiad commented on src/aind_data_schema/assembly.py
> +    solenoid_part: str = Field(..., title="Solenoid Part number")
should solenoid be a device?

2023-04-22 00:49 UTC, saskiad commented on src/aind_data_schema/assembly.py
> +    stage_type: str = Field(..., title="Stage build type")
what is stage_type? (I'm just unclear what this is)

2023-04-22 00:49 UTC, saskiad commented on src/aind_data_schema/assembly.py
> +    spout_diameter: str = Field(..., title="Spout diameter", units="mm")
need a spout_diameter_unit as a separate field using SizeUnit. Add (mm) to the title. See some of the other unit fields around as examples (or ask me and I can help)

2023-04-22 00:49 UTC, saskiad commented on src/aind_data_schema/assembly.py
> +    calibration: dict = Field(..., title="Water calibration values")
water_calibration_values: Dict[str, Any] = Field(..., title="Water calibration values")
-> add Dict to the typing imports. Also Any

We try to have the field name and the title close to the same

2023-04-22 00:49 UTC, saskiad commented on src/aind_data_schema/assembly.py
> +    track_wheel: Union[Tube, Treadmill, Disc] = Field(..., title="Track wheel type")
track_wheel isn't a good name here. None of these are wheels. Maybe we can call a disc a wheel... sure. But Tubes don't even allow running - by design.

2023-04-22 00:49 UTC, saskiad commented on src/aind_data_schema/assembly.py
> +class BehaviorPlatform(AindModel):
I share David's thought here.
I'm also unclear why these are grouped in this way. These are all the behavior equipment for your experiments? Do they need to be grouped this way? I might prefer to have these all as devices... But let me consider this some more ...

2023-04-22 00:49 UTC, saskiad commented on src/aind_data_schema/assembly.py
> +    stage_software: Optional[Software] = Field(None, title="Stage software")
this is the software that controls the stage for the water delivery? Is that correct? (stage is an common term, so we might need to add a modifier) If so, can we add this to the water delivery class directly?

2023-04-22 00:49 UTC, saskiad commented on src/aind_data_schema/assembly.py
> +class VisualStimulusDisplayAssembly(AindModel):
I'm unclear why this is here - it inherits all of these fields from Monitor.

2023-04-22 00:49 UTC, saskiad commented on src/aind_data_schema/device.py
> +class Driver(Enum):
what kind of Drivers are these? graphics? Add to the name

2023-04-22 00:49 UTC, saskiad commented on src/aind_data_schema/device.py
> -class RelativePosition(AindModel):
moving this to assembly.py outright assumes that all devices are part of assemblies, which is not true. This needs to be in device.py
The question I have is do we need a separate assembly.py file? I'm not sure we do

2023-04-22 00:49 UTC, saskiad commented on src/aind_data_schema/device.py
> +    software_name: str = Field(..., title="Software on computer")
agreed

Though ... there might be code vs software? Eg. using ScanImage might not permit pointing to a code_url.

2023-04-22 00:49 UTC, saskiad commented on src/aind_data_schema/device.py
> +    configuration: Optional[dict] = Field(..., title="Software configuration")
see the syntax for parameters in the snippet David posted above to get the Dict right. And maybe sure Dict is imported.
Can we call configuration parameters?

2023-04-22 00:49 UTC, saskiad commented on src/aind_data_schema/device.py
> -    viewing_distance: float = Field(..., title="Viewing distance (cm)", units="cm")
why remove these from the device?

2023-04-24 22:41 UTC, arielleleon commented on src/aind_data_schema/assembly.py
> +class BehaviorPlatform(AindModel):
The MousePlatform is a base class for all surfaces that a mouse runs on (Disc, Tube, Treadmill). We were thinking that one could represent the entire behavior assembly (track wheel, water deliver, cameras, etc) as it's own system. After discussing this with Clark, we are going to remove the concept of a BehaviorPlatform to keep assemblies from becoming too nested.

2023-04-24 22:43 UTC, arielleleon commented on src/aind_data_schema/device.py
> +    description: str = Field(..., title="Description of where and how software are used")
We could make this optional. Out of curiosity, why do you think this is unnecessary?

2023-04-24 22:48 UTC, arielleleon commented on src/aind_data_schema/device.py
> +    software_name: str = Field(..., title="Software on computer")
I agree with @saskiad latest comment. The software I am referring to is software used to manipulate hardware/acquire data and is typically versioned and in either PyPi, aibsdevpi (Engineering hosted server), or other 3rd party SW. What do you think about describing this better in the docstring associated with the class so folks can delineate processing vs hardware control software?

2023-04-24 22:48 UTC, arielleleon commented on src/aind_data_schema/device.py
> +    analog: Optional[bool] = Field(None,description="analog or digital electronics")
Yes

2023-04-24 22:56 UTC, arielleleon commented on src/aind_data_schema/device.py
> +class Computer(AindModel):
I agree that we can remove it. It is only used in DAQDevice now. If a computer_name is used in multiple locations further down the line it would be nice to have a computer base class. That can be added later.

2023-04-24 23:48 UTC, saskiad commented on src/aind_data_schema/device.py
> +    software_name: str = Field(..., title="Software on computer")
I think I want a software class that has similar things to what we're tracking for the processing code:
software, version, parameters

2023-04-25 19:52 UTC, arielleleon commented on src/aind_data_schema/device.py
> +    software_name: str = Field(..., title="Software on computer")
@saskiad  Ok, we left the software class in device and renamed the keys to 'name', 'version' and 'configuration'. I removed the 'description' per earlier advice.

2023-04-25 19:57 UTC, arielleleon commented on src/aind_data_schema/assembly.py
> +class RelativePosition(AindModel):
Agreed and moving.

2023-04-25 20:10 UTC, arielleleon commented on src/aind_data_schema/assembly.py
> +    spout_diameter: str = Field(..., title="Spout diameter", units="mm")
We can do that and there is a built in unit option in PyDantic I thought was useful. Out of curiosity, why is that not used?

2023-04-25 20:12 UTC, arielleleon commented on src/aind_data_schema/assembly.py
> +    calibration: dict = Field(..., title="Water calibration values")
Got it and done

2023-04-25 20:13 UTC, arielleleon commented on src/aind_data_schema/device.py
> +class Driver(Enum):
These are device drivers or firmware. Changed name to DeviceDriver

2023-04-25 20:14 UTC, arielleleon commented on src/aind_data_schema/device.py
> -class RelativePosition(AindModel):
Correct, we do not need an assembly.py file and it's being removed.

2023-04-25 20:26 UTC, arielleleon commented on src/aind_data_schema/device.py
> +    configuration: Optional[dict] = Field(..., title="Software configuration")
I use the term configuration because you configure software with a set of parameters. Happy to change it though

2023-04-25 20:28 UTC, arielleleon commented on src/aind_data_schema/device.py
> -    viewing_distance: float = Field(..., title="Viewing distance (cm)", units="cm")
We removed this because we added it to an assembly instance. It has been added back to Monitor

2023-04-25 21:53 UTC, saskiad commented on src/aind_data_schema/assembly.py
> +    spout_diameter: str = Field(..., title="Spout diameter", units="mm")
because it doesn't show up in the json. Originally that's how we were doing the units, but they just live in the schema code and don't show up in the json. So that's why we switched the the cumbersome parameter_value and parameter_value_unit system we have now. 
We actually have an open issue (#262 ) to streamline this a little bit - I'll give you a heads up when we implement that

2023-05-06 03:55 UTC, saskiad commented on src/aind_data_schema/device.py
> +    spout_diameter_units_mm: SizeUnit = Field(..., title="")
spout_diameter_unit: SizeUnit = Field(SizeUnit.MM, title="Spout diameter unit")

2023-05-06 03:55 UTC, saskiad commented on src/aind_data_schema/device.py
> +    spout_diameter: str = Field(..., title="Spout diameter")
Add (mm) to the title for Spout diameter.

2023-05-06 03:56 UTC, saskiad commented on src/aind_data_schema/device.py
> +    stage_type: str = Field(..., title="Stage build type")
what is stage_type? Should this be an ENUM of possible types?

2023-05-06 03:57 UTC, saskiad commented on src/aind_data_schema/device.py
> +    spout_placement: RelativePosition = Field(..., title="Spout stage placement")
can we call this spout_position? (and adjust title too)

2023-05-06 03:58 UTC, saskiad commented on src/aind_data_schema/device.py
> +class BehaviorPlatform(AindModel):
I'm unclear why this is BehaviorPlatform instead of the MousePlatform we currently have. Especially since Tube is decidedly not a behavior platform.

2023-05-06 03:58 UTC, saskiad commented on src/aind_data_schema/device.py
> +    track_wheel: Union[Tube, Treadmill, Disc] = Field(..., title="Track wheel type")
likewise, this really should not be track wheel when only one is (arguably) a wheel

2023-05-06 03:59 UTC, saskiad commented on src/aind_data_schema/device.py
> +    stage_software: Optional[Software] = Field(None, title="Stage software")
I'm confused what the stage software is - this controls the water spout?

2023-05-06 04:01 UTC, saskiad commented on src/aind_data_schema/device.py
> +    material: Optional[str] = Field(None, title="Material type")
Should this be an ENUM? What are the material types this could be?

2023-05-06 04:01 UTC, saskiad commented on src/aind_data_schema/device.py
> +    replacement_date: Optional[datetime] = Field(None, title="In use since")
can we make the title be Replacement date? I assume this is a part that degrades with time and it's function changes this with time?

2023-05-06 04:03 UTC, saskiad commented on src/aind_data_schema/device.py
> +    solenoid_part: str = Field(..., title="Solenoid Part number")
This will be in the solenoid device class, we don't need it here as well, right?

2023-05-11 20:51 UTC, arielleleon commented on src/aind_data_schema/device.py
> +    spout_diameter_units_mm: SizeUnit = Field(..., title="")
Done

2023-05-11 20:54 UTC, arielleleon commented on src/aind_data_schema/device.py
> +    spout_placement: RelativePosition = Field(..., title="Spout stage placement")
Done

2023-05-11 20:56 UTC, arielleleon commented on src/aind_data_schema/device.py
> +class BehaviorPlatform(AindModel):
Done - changed to MousePlatform

2023-05-11 21:01 UTC, arielleleon commented on src/aind_data_schema/device.py
> +    track_wheel: Union[Tube, Treadmill, Disc] = Field(..., title="Track wheel type")
@saskiad  Is the tube more analogous to the head frame than it is to the treadmill/disc? If that's the case I would argue that the tube be separated from two. What do you think?

2023-05-11 21:02 UTC, arielleleon commented on src/aind_data_schema/device.py
> +    stage_software: Optional[Software] = Field(None, title="Stage software")
This is the firmware associated with the stage. Is it necessary? If so, I should rename it to firmware.

2023-05-11 21:04 UTC, arielleleon commented on src/aind_data_schema/device.py
> +    material: Optional[str] = Field(None, title="Material type")
@saskiad  I'm thinking of removing this since it's most likely going to be aluminum. Also the material type is listed in the part number. I do think the replacement date should stay though. You OK if I remove it?

2023-05-11 21:06 UTC, arielleleon commented on src/aind_data_schema/device.py
> +    solenoid_part: str = Field(..., title="Solenoid Part number")
True. Removing

2023-05-11 21:13 UTC, arielleleon commented on src/aind_data_schema/device.py
> +    replacement_date: Optional[datetime] = Field(None, title="In use since")
I think so but now I am second guessing myself and I am checking with systems engineers on Colin's team. I may remove this device if found stable, otherwise, I will change the title according to your suggestion.

2023-05-11 22:47 UTC, saskiad commented on src/aind_data_schema/device.py
> +    track_wheel: Union[Tube, Treadmill, Disc] = Field(..., title="Track wheel type")
no, it's a literal tube that holds the mouse, so it's more like the treadmill or disc - except it largely prevents the mouse from running rather than enables it.

2023-05-11 23:12 UTC, saskiad commented on src/aind_data_schema/device.py
> +    track_wheel: Union[Tube, Treadmill, Disc] = Field(..., title="Track wheel type")
![Screen Shot 2023-05-11 at 4 11 11 PM](https://github.com/AllenNeuralDynamics/aind-data-schema/assets/3857958/564eb04f-1f30-44f9-9f28-ca0c7180a9aa)

2023-05-12 02:42 UTC, saskiad commented on src/aind_data_schema/device.py
> +    material: Optional[str] = Field(None, title="Material type")
sounds good

2023-05-12 02:44 UTC, saskiad commented on src/aind_data_schema/device.py
> +    stage_software: Optional[Software] = Field(None, title="Stage software")
my confusion is more about "stage" - I think of stage as being a platform and being controlled by the data acquisition software, so I'm more confused what this software controls. I think I just don't know what the stage is.

2023-05-12 18:55 UTC, arielleleon commented on src/aind_data_schema/device.py
> +    replacement_date: Optional[datetime] = Field(None, title="In use since")
After checking with systems engineers they did say it's the fittings that need to be replaced not the solenoid itself. I will remove this.

2023-05-12 21:18 UTC, arielleleon commented on src/aind_data_schema/device.py
> +    track_wheel: Union[Tube, Treadmill, Disc] = Field(..., title="Track wheel type")
@saskiad What about mobility_aid?

2023-05-12 21:28 UTC, DowntonCrabby commented on src/aind_data_schema/device.py
> +    stage_type: str = Field(..., title="Stage build type")
Arielle and I just talked about this a bit- we were thinking the stage is basically the motorized platform that moves the thing the mouse is on in to place. 

Perhaps we can change the title, or make a more general device as I think there are multiple of these types of stages, for example on the scientifica its the microscope that's on a stage that moves in to place, on the mesoscope both the microscope and the animal are on stages that move. The lickspout also has a motorized stage that moves it in to place.

2023-05-12 21:33 UTC, DowntonCrabby commented on src/aind_data_schema/device.py
> +    track_wheel: Union[Tube, Treadmill, Disc] = Field(..., title="Track wheel type")
mouse ambulation context ?

2023-05-12 21:35 UTC, DowntonCrabby commented on src/aind_data_schema/device.py
> +    stage_software: Optional[Software] = Field(None, title="Stage software")
See the comment I left above about what we were thinking a stage is. In that context I think there's a lot of things on stages that move around in the behavior enclosure like the lick spout, the actual thing that the wheel/disc etc sits on that moves in to place, etc.  Sometimes that acquisition software controls it and sometimes not- each of these could have their own hardware with it's own firmware/software.

2023-05-13 02:45 UTC, saskiad commented on src/aind_data_schema/device.py
> +    stage_type: str = Field(..., title="Stage build type")
thanks - this helps! I think I understand better! I think motorized stage might be the the thing to use - I think we have that in the imaging instruments (the SPIMs) so perhaps we can leverage that.

But then I would expect this to be outside of Behavior Platform class - since sometimes it's the microscope that's on the stage and sometimes its the mouse.

2023-05-13 02:47 UTC, saskiad commented on src/aind_data_schema/device.py
> +    track_wheel: Union[Tube, Treadmill, Disc] = Field(..., title="Track wheel type")
Again, one context is specifically non-ambulatory or mobile. Is there a specific reason you don't want Mouse Platform?

2023-05-19 21:57 UTC, DowntonCrabby commented
@saskiad we went through and tried to fix all the linting errors associated with our work. It looks like there are still some failures but those are related to items that we didn't touch so we weren't sure how to proceed.

2023-05-21 04:59 UTC, saskiad commented
Changes to the DAQ device are going to impact a bunch of ephys and imaging things, I'll work on that.

2023-05-25 14:58 UTC, dyf requested changes

2023-05-30 17:12 UTC, dyf approved these changes

2023-05-30 17:20 UTC, saskiad approved these changes

2023-05-30 17:20 UTC, merged