Add first pass at behavior rig
AllenNeuralDynamics/aind-data-schema pull request #283
Opened 2023-05-06 04:22 UTC by saskiad

added a simple behavior rig schema, and made a behavior folder

2023-05-06 04:32 UTC, saskiad commented
Something we need to think about is whether the behavior "rig" is something that gets inherited into ephys and ophys rigs? Or if it should just be a parallel for a behavior only context. We can discuss later - I think that's beyond the scope of this PR

2023-05-06 04:43 UTC, saskiad commented
closes #284

2023-05-07 22:21 UTC, dyf requested changes

2023-05-07 22:21 UTC, dyf commented on src/aind_data_schema/behavior/behavior_rig.py
> +    describedBy: str = Field(
you can remove `describedBy`.  It's automatically included by inheriting from `AindCoreModel`.

2023-05-07 22:21 UTC, dyf commented on src/aind_data_schema/behavior/behavior_session.py
> +    describedBy: str = Field(
ditto

2023-05-07 23:33 UTC, saskiad commented on src/aind_data_schema/behavior/behavior_rig.py
> +    describedBy: str = Field(
Ah! excellent. Let's remove these from other schemas - I'll make an issue

2023-05-08 18:47 UTC, dyf approved these changes

2023-05-08 20:12 UTC, merged