Feat 248 erd generator
AllenNeuralDynamics/aind-data-schema pull request #299
Opened 2023-05-12 00:49 UTC by Sun-flow

Adding script to automatically generate ERD diagrams of all classes using AindCoreModel

2023-05-13 02:41 UTC, saskiad approved these changes
I think it looks good. Make sure @jtyoung84 sees it before merging.
There are some things missing(ish) in some of the erdantic diagrams, that I think is a erdantic thing, and perhaps we can dig into that in a future issue. But I'm excited to even have this!

2023-05-16 05:48 UTC, dyf requested changes
A few nitpicks, but otherwise looking good.

2023-05-16 05:48 UTC, dyf commented on src/aind_data_schema/utils/test.ipynb
Can you remove this test notebook?

2023-05-16 05:48 UTC, dyf commented on src/aind_data_schema/utils/erd_diagram_generator.py
> +        # os.environ["PATH"] += os.pathsep + 'C:/Program Files/Graphviz/bin/'
go ahead an remove this comment

2023-05-16 05:48 UTC, dyf commented on pyproject.toml
> +    'erdantic',
Let's make this an optional dependency, I think.  `erdantic` brings `pygraphviz` which is pretty heavy.

2023-05-17 17:40 UTC, Sun-flow commented on src/aind_data_schema/utils/test.ipynb
Yes, it will be removed before merge. Right now I am waiting to work with Jon on Unit tests, so it's not quite close yet

2023-05-17 17:41 UTC, Sun-flow commented on src/aind_data_schema/utils/erd_diagram_generator.py
> +        # os.environ["PATH"] += os.pathsep + 'C:/Program Files/Graphviz/bin/'
Right now this line is necessary for functionality, Jon and I are looking for workarounds.

2023-05-17 17:41 UTC, Sun-flow commented on pyproject.toml
> +    'erdantic',
Great. I will see what doing that would require.

2023-05-21 22:59 UTC, dyf approved these changes

2023-05-21 23:00 UTC, merged