Adding visual stim class
AllenNeuralDynamics/aind-data-schema pull request #306
Opened 2023-05-13 17:23 UTC by saskiad

2023-05-13 17:23 UTC, saskiad commented
closes #305

2023-05-15 17:33 UTC, dyf commented on src/aind_data_schema/stimulus.py
> +    stimulus_template_name: Optional[List[str]] = Field(
is this supposed to be a list?

2023-05-15 17:40 UTC, dyf requested changes
This looks like it's meant to cover multiple stimuli at once, but if you link to it from a `StimulusPresentation` (which I think is meant to describe which stimulus was used for a given trial), then there's no way to know which stimulus and which parameters were used.  So, whatever is linked to in `StimulusPresentation` should refer to a specific "stimulus condition," I think, rather than a class of stimuli.

2023-05-15 19:44 UTC, dyf approved these changes

2023-05-15 21:07 UTC, merged