Adding stack class
AllenNeuralDynamics/aind-data-schema pull request #349
Opened 2023-05-26 18:57 UTC by saskiad

closes #345

2023-05-26 21:22 UTC, KasparP commented on src/aind_data_schema/ophys/ophys_session.py
> +    magnification: str = Field(..., title="Magnification")
magnification is a bit unclear and archaic for laser scanning. Is pixel size not sufficient?

2023-05-26 21:29 UTC, KasparP reviewed
Maybe add 
dimension order, number of channels 
as fields?

2023-05-30 17:19 UTC, dyf requested changes

2023-05-30 17:19 UTC, dyf commented on src/aind_data_schema/ophys/ophys_session.py
> +    step_size: float = Field(SizeUnit.UM, title="Step size")
Should probably be `Field(..., title="Step size")`

2023-05-30 17:19 UTC, dyf commented on src/aind_data_schema/ophys/ophys_session.py
> +    step_size: float = Field(SizeUnit.UM, title="Step size")
assuming that `depth_unit` applies to this field.

2023-06-23 23:07 UTC, saskiad commented on src/aind_data_schema/ophys/ophys_session.py
> +    step_size: float = Field(SizeUnit.UM, title="Step size")
anticipating valuewithunit coming soon, I'm keeping these separate since one is an int and one is a float

2023-06-23 23:53 UTC, saskiad commented on src/aind_data_schema/ophys/ophys_session.py
> +    magnification: str = Field(..., title="Magnification")
I'm going to keep this and make it optional - I think the mesoscope team uses it

2023-06-24 00:23 UTC, saskiad commented
I've added a channel concept to both rig and the stack session. I kept detectors and filters in the rig outside of the channel concept to be safe, but we can probably remove the detector list in the rig schema. 
I've only added the channel to the stack session type - we might want to add it to the TwoPhotonOphysSession or FOV classes as well...

2023-06-26 22:01 UTC, KasparP approved these changes
thanks for addressing my comments

2023-06-27 15:27 UTC, dyf requested changes

2023-06-27 15:27 UTC, dyf commented on src/aind_data_schema/ophys/ophys_rig.py
> +class Channel(AindModel):
Should we consider combining this with `imaging.tile.Channel`?

2023-09-07 20:54 UTC, saskiad commented
closes #430

2023-09-08 04:36 UTC, dyf requested changes
I am wondering if the right way to model this is instead to say that there is an OphysSession, and an OphysSession can have:
- planar fields of view
- stacks (which are fields of view with depth and step size and repeats)
- patch coords and coupling arrays

2023-09-08 04:36 UTC, dyf commented on src/aind_data_schema/ophys/ophys_rig.py
> +    channels: Optional[List[Channel]] = Field(None, title="Channels", unique_items=True)
I think we decided channels are in session only.

2023-09-12 23:22 UTC, saskiad commented
> I am wondering if the right way to model this is instead to say that there is an OphysSession, and an OphysSession can have:
> 
> * planar fields of view
> * stacks (which are fields of view with depth and step size and repeats)
> * patch coords and coupling arrays

I think I want to hold off doing this for when we merge the sessions across everything - I worry this will disrupt current ingest things, and I'd prefer to do that as few times as possible.

2023-09-15 19:25 UTC, saskiad commented
replaced by #479

2023-09-15 19:25 UTC, closed without merging