Fix 372 write file path
AllenNeuralDynamics/aind-data-schema pull request #374
Opened 2023-06-14 22:20 UTC by Louise-X10

close #372

2023-06-14 23:41 UTC, jtyoung84 commented on src/aind_data_schema/base.py
> +        elif str(prefix)[-1] == "/" or str(prefix)[-1] == "\\":
I think it'll be better to add an Optional output directory such that the function signature looks like:
`def write_standard_file(self, output_directory: Optional[Path] = None, prefix=None)`

2023-06-14 23:42 UTC, jtyoung84 requested changes
See comments

2023-06-16 21:44 UTC, Louise-X10 commented on src/aind_data_schema/base.py
> +        elif str(prefix)[-1] == "/" or str(prefix)[-1] == "\\":
Do we want to continue using Path or usual strings for directories? The ticket seems to show that they should be strings, but the unit test uses Path. The issue with Path is that they strip off the trailing slashes, so you would have to add them back manually. It may be easier if we could assume the directory argument is a string, and convert Path to strings in the unit tests.

2023-06-16 21:46 UTC, jtyoung84 commented on src/aind_data_schema/base.py
> +        elif str(prefix)[-1] == "/" or str(prefix)[-1] == "\\":
Assume the input directory is a Path object. The "prefix" is supposed to a string

2023-06-19 23:28 UTC, jtyoung84 reviewed
Looks good to me. Double-check with @dyf that this is the desired behavior.

2023-06-19 23:28 UTC, jtyoung84 approved these changes

2023-06-20 18:24 UTC, merged