Doc 343 manufacturer ror i ds
AllenNeuralDynamics/aind-data-schema pull request #377
Opened 2023-06-20 16:07 UTC by Sun-flow

closes #343 

Expanding all Manufacturer names to implement BaseName/PIDName, and adding ROR IDs that we know of.

2023-06-21 04:41 UTC, saskiad commented on src/aind_data_schema/device.py
> +        name=BaseName(name="Materials Processing, Inc", abbreviation="MPI"),
I'm not actually sure that's the name, let's leave it as MPI

2023-06-21 04:42 UTC, saskiad commented on src/aind_data_schema/device.py
> +        registry_identifier="01j1gwp17"
this is the ID for FLIR.

2023-06-21 04:44 UTC, saskiad commented on src/aind_data_schema/device.py
> +    CUSTOM = PIDName(
can we have CUSTOM not be a PIDName? such as how we do OTHER? Because Custom is not a company, it means the device was custom built.

2023-06-21 04:45 UTC, saskiad commented on src/aind_data_schema/device.py
> +        registry_identifier=""
Thorlabs rorid = 04gsnvb07

2023-06-26 17:48 UTC, saskiad commented on src/aind_data_schema/device.py
> +"
Fix this end quote - looks like it got bumped to the next line. I think this is causing the test/lint errors

2023-06-26 17:48 UTC, saskiad requested changes
fix the end quote for Olympus id

2023-06-27 19:23 UTC, jtyoung84 commented on src/aind_data_schema/base.py
> +    name: str = Field(..., title="name")
This field get's inherited from BaseName

2023-06-27 19:24 UTC, jtyoung84 commented on src/aind_data_schema/device.py
> +    OTHER = "OTHER"
OTHER and CUSTOM also need to be a PIDName

2023-06-27 19:25 UTC, Sun-flow commented on src/aind_data_schema/device.py
> +    OTHER = "OTHER"
@saskiad requested that this not be a PIDName, as it will never have an RORID. I don't mind to change it, either way is fine for me.

2023-06-29 16:37 UTC, saskiad approved these changes

2023-06-29 16:37 UTC, merged