Feat imaging calibration
AllenNeuralDynamics/aind-data-schema pull request #379
Opened 2023-06-21 19:09 UTC by miketaormina

# Purpose
To accommodate a calibration of the type: `(excitation power set point, excitation power measured at objective)`.
Set point allows `percent` as a unit for the set point, which is what the SmartSPIM logs in it's instrument-created metadata.
There is a bit more discussion in [Issue 272](https://github.com/AllenNeuralDynamics/aind-data-schema/issues/272), but generally speaking, the power set point on a laser is very different from the power that makes it to a sample, and can vary across instruments and time.

## Scope
Added to `acquisition.py` schema, added example of a stand-alone calibration measurement. Schema additions are `Optional`, so should not create conflicts in main.

2023-08-03 23:48 UTC, saskiad commented on src/aind_data_schema/imaging/acquisition.py
> +    light_source: Lightsource = Field(..., title="Light Source")
can light_source be light_source_name? That way don't have to include all the specs of the device that are in the rig but have the name to link between them?

2023-08-03 23:49 UTC, saskiad requested changes
Rather than include the full light_source device, it would be cleaner to use the name of the light_source to link between the device and the calibration

2023-08-04 00:14 UTC, dyf commented on src/aind_data_schema/imaging/acquisition.py
> +    light_source: Lightsource = Field(..., title="Light Source")
+1

2023-08-04 00:16 UTC, dyf requested changes

2023-08-04 00:16 UTC, dyf commented on src/aind_data_schema/imaging/acquisition.py
> +class PowerUnit(Enum):
please move this to `utils/units.py`

2023-08-07 21:12 UTC, miketaormina commented on src/aind_data_schema/imaging/acquisition.py
> +    light_source: Lightsource = Field(..., title="Light Source")
I agree as well. I think this was my initial idea, but the light sources didn't have names. Looking at the instrument configurations, this is only because `name` is an optional field that wasn't filled in, so I will need to also alter the instrument JSON files for this to work. I think I will use the convention `Ex_<Lightsource.wavelength>`, since that is how the instrument names acquisition files.

2023-08-07 22:20 UTC, camilolaiton commented
Hello @miketaormina, I have updated your branch to use a generic calibration class I included in this [branch](https://github.com/AllenNeuralDynamics/aind-data-schema/blob/feat-imaging-generic-calibration/src/aind_data_schema/device.py#L620).

I noticed that the [LightSourcePowerCalibration](https://github.com/AllenNeuralDynamics/aind-data-schema/blob/feat-imaging-calibration/src/aind_data_schema/imaging/acquisition.py#L111) class is in the `acquisition.py` script. Should we move that one as well to `device.py`? If so, there are circular dependencies that we will have to fix @dyf.

2023-08-08 17:53 UTC, saskiad commented
Ideally LightSourcePowerCalibration will use the generic calibration class. I imagine this should stay in the acquisition file - @miketaormina this is likely something you want to run before each imaging session? If so, acquisition file is the place that makes most sense.

2023-08-08 18:03 UTC, miketaormina commented
That's right, @saskiad . My thinking was that it would happen at most once per day, but maybe even once per week. In either case, one calibration would be associated with several acquisitions. We may need to do this once per imaging day until we know how stable the values are on that time scale.

How I imagined this working would be generating calibration files in a standard location on the acquisition machine and then ingesting the most recent one when the data sets are prepared for transfer. This is similar to how I have been grabbing the instrument json, but I think it belongs in the acquisition file, since it would be used to establish the actual laser power in milliwatts for that particular imaging run (since the device currently only reports this value as a percentage of maximum).

I just need a day or so to sort out what's needed on the updated branch.

2023-08-08 20:50 UTC, miketaormina commented on src/aind_data_schema/imaging/acquisition.py
> +class PowerUnit(Enum):
added PowerUnit and PowerValue to `utils/units.py`

2023-08-09 13:44 UTC, dyf approved these changes
Looks fine.

2023-08-09 16:20 UTC, saskiad commented on src/aind_data_schema/device.py
> +    LASER = "laser"
please use sentence case: LASER = "Laser

2023-08-09 16:21 UTC, saskiad commented on src/aind_data_schema/device.py
> +class Calibration(AindModel):
This class need the device name that the calibration is for. This is a key field

2023-08-09 16:23 UTC, saskiad commented on examples/smartspim_power_calibrations.json
> +          "name": null,
please add names to your devices so that we can actually link to them from the acquisition file

2023-08-09 17:56 UTC, miketaormina commented on src/aind_data_schema/imaging/acquisition.py
> +class LightSourcePowerCalibration(Calibration):
I guess it's only because there wasn't a generic class when I started. I don't think there is a reason that it couldn't just be an instance of `Calibration`,  are the dictionaries on this unrestricted (the example json would be the only place where it is defined)?

2023-08-09 17:58 UTC, miketaormina commented on examples/smartspim_power_calibrations.json
> +          "name": null,
I guess I forgot about this file. I've given both aibs and aind light source devices name in the instrument json and will add one here. I can also make a script that generates this example file, to match the rest of the examples.

2023-08-09 22:53 UTC, saskiad commented
sorry to add a monkey wrench at this point, but I think that cleaning a chamber isn't a calibration event so much as a maintenance event.

2023-08-10 00:54 UTC, miketaormina commented
>I feel like we aren't aligned on how we want to use the calibration class

@saskiad I agree and think it takes some more thought. Although a calibration should be associated with an instrument and one or more acquisitions, it doesn't seem to fit neatly into one or the other schemas. It often will be generated separately from an acquisition, so if it goes into `acquisition.json`, it needs to be ingested, which I think is a pattern we are trying to avoid in this workflow (correct me if I'm wrong). If it goes into `instrument.json`, that file will be updated much more often than I think we'd like. Does this mean we need an `instrument_maintenance.json` with calibrations and cleanings? I suspect that we don't like that either.

Can we:
Make `class CalibrationSet(AindCoreModel)` be a list of `Calibration` of the same type and use a convention of including the `CalibrationType` in the file name? 
E.g., 
```
class CalibrationSet(AindCoreModel):
    calibration_type: ...
    instrument_id: ...
    calibrations: List(Calibration)

c = CalibrationSet(. . . , calibrations=[cal0, cal1, cal2])
c.write_standard_file(prefix=f"{c.calibration_type}") 

```
outputs `laser_calibration.json` or `monitor_calibration.json`, which consist of lists of calibrations of the same type (and performed at the same time)? Then raw data gets packaged with the most recent version of locally available calibrations. This gets around the acquisition vs. device/instrument but spreads the information over more files.

Am I overcomplicating this?

2023-08-10 16:16 UTC, saskiad commented
I think you are overcomplicating it. I imaging in the acquisition schema there is a list of calibrations. The list uses a class called Calibration which is being added to the device schema in this PR. That class needs a field for the name of the device that was calibrated. Date of calibration. A dictionary of input variables (e.g. laser power settings) and a dictionary of output variables (e.g. measured power). 
I think making separate classes for each device calibration is going to get very bloated very fast. Already for the behavior schema we have about 5 devices that need regular calibration. 
So then in the acquisition schema you create a list of all the calibrations for the instrument that you need.

Separate from this I suggest we create a class called Maintenance which is for things like cleaning the chamber where it isn't a calibration per se and doesn't have the input/output dictionaries.

2023-08-21 21:53 UTC, camilolaiton commented
Hello! I just wanted to follow up on this @dyf @saskiad @miketaormina, I would like to have these changes in the main branch to update the SmartSPIM data transfer scripts. Thanks!

2023-08-22 18:40 UTC, saskiad commented
do you want me to take a pass at how I would structure this? I can probably do that tonight. That okay @miketaormina ?

2023-08-22 19:32 UTC, miketaormina commented
> do you want me to take a pass at how I would structure this? I can probably do that tonight. That okay @miketaormina ?

Okay with me, for sure!

2023-08-23 16:44 UTC, dyf reviewed
Quick question re: Maintenance.

2023-08-23 16:44 UTC, dyf commented on src/aind_data_schema/device.py
> +    reagents: Optional[List[Reagent]] = Field(None, title="Reagents")
Does `Maintenance` need reagents?

2023-08-23 17:45 UTC, saskiad commented on src/aind_data_schema/device.py
> +    reagents: Optional[List[Reagent]] = Field(None, title="Reagents")
Does it require reagents? I expect not - there can be maintenance that doesn't have reagents. But it sounds like there are some that do - eg. cleaning chambers.

2023-08-23 23:31 UTC, miketaormina reviewed
This looks good to me, if you need me to update one of the smartspim examples to include calibrations and/or maintenance, let me know.

2023-08-23 23:31 UTC, miketaormina commented on examples/exaspim_acquisition.py
> +            input={"power setting": 1},
Does the Calibration object here need to use `PowerValue`, as in `tests/test_imaging.py` below? Or is the schema built such that any valid dictionary is okay? Asking becuase `PowerValue` would require units on these numbers.

Not asking about schema validation, but rather if the example should indicate what is expected (not necessarily required).

2023-08-24 22:29 UTC, saskiad commented on examples/exaspim_acquisition.py
> +            input={"power setting": 1},
dictionary can take anything, but agree that example should demonstrate how we want to use it and I really like having units. I can update this

2023-08-25 01:36 UTC, saskiad approved these changes

2023-08-25 01:36 UTC, merged