Feat 381 objective
AllenNeuralDynamics/aind-data-schema pull request #382
Opened 2023-06-22 00:08 UTC by saskiad

closes #381

2023-06-22 20:29 UTC, dyf requested changes

2023-06-22 20:29 UTC, dyf commented on src/aind_data_schema/device.py
> +    center_wavelength: SizeUnit = Field (SizeUnit.NM, title = "Center wavelength unit")
I think this wants to be `center_wavelength_unit`.  

Do we want to replace the three wavelength unit fields with a single `wavelenth_unit`?

2023-06-22 20:35 UTC, saskiad commented on src/aind_data_schema/device.py
> +    center_wavelength: SizeUnit = Field (SizeUnit.NM, title = "Center wavelength unit")
yes and yes

2023-06-23 23:05 UTC, dyf approved these changes

2023-06-23 23:59 UTC, merged