Feat fip
AllenNeuralDynamics/aind-data-schema pull request #392
Opened 2023-06-30 23:20 UTC by dyf

closes #391

2023-07-01 04:36 UTC, saskiad commented on src/aind_data_schema/device.py
> +    FACE_BOTTOM = "Face side"
First, this needs to be "Face bottom"
Second, if we have face bottom and face side, what is face?

2023-07-01 04:38 UTC, saskiad commented on examples/fip_ophys_rig.py
> +                "SpinViewSettings - Binning:4*4, Binning mode: Additive, Crop: 200*200 pixels, Pixel Format: Mono 16"
if you're updating ophys rig already, let's add these to the detectors. This is one of the things waiting on my ability to use git.

2023-07-01 04:43 UTC, saskiad requested changes
couple of things need to be fixed

2023-07-03 22:52 UTC, dyf commented on src/aind_data_schema/device.py
> +    FACE_BOTTOM = "Face side"
We could get rid of `FACE`?

2023-07-05 23:04 UTC, saskiad commented on examples/fip_ophys_rig.py
> +            bin_width=4,
bin needs a unit. pixels?

2023-07-05 23:04 UTC, saskiad commented on examples/fip_ophys_rig.py
> +            crop_width=200,
crop needs a unit too

2023-07-05 23:05 UTC, saskiad requested changes
just need units for the new fields

2023-07-05 23:07 UTC, saskiad approved these changes

2023-07-05 23:18 UTC, merged