Feat: added create_derived_data_description() function and tests
AllenNeuralDynamics/aind-data-schema pull request #400
Opened 2023-07-06 16:12 UTC by alejoe91

fixes #399

2023-07-06 16:43 UTC, jtyoung84 commented on pyproject.toml
> +    'packaging',
We can probably avoid adding another package to the dependencies list. I think you can parse version numbers using the built-in:
```
>>> from pkg_resources import parse_version
>>> parse_version('0.13.0') < parse_version('1.0.0')
True
>>> parse_version('1.13.0') < parse_version('1.0.0')
False
```

2023-07-06 16:45 UTC, jtyoung84 commented on tests/resources/ephys_data_description/data_description_0.6.2.json
> +        "Galen Lynch",
We've been making an effort to scrub out names and using stuff "John Doe" or "Mary Smith"

2023-07-06 16:47 UTC, jtyoung84 commented on src/aind_data_schema/utils/aind_utils.py
> +def create_derived_data_description(
It'd be better if this was moved in the DerivedDataDescription class as an alternate class constructor instead of a method in the aind_utils package

2023-07-06 16:48 UTC, jtyoung84 commented on src/aind_data_schema/utils/aind_utils.py
> +    input_data_name: str | None = None,
You can import Optional and List from the typing module. This then becomes `input_data_name: Optional[str] = None`

2023-07-06 16:49 UTC, jtyoung84 commented on src/aind_data_schema/utils/aind_utils.py
> +    subject_id: str = None,
This should be `Optional[str]`

2023-07-06 16:50 UTC, jtyoung84 commented on src/aind_data_schema/utils/aind_utils.py
> +    investigators: list = [],
It isn't recommended to use mutable data types as defaults. One way to circumvent the warnings is to do something like:
```
investigators: Optional[List] = None
```
and then in the code:
```
investigators = [] if investigators is None else investigators
```

2023-07-06 16:53 UTC, jtyoung84 commented on src/aind_data_schema/utils/aind_utils.py
> +    existing_data_description: str | Path | DataDescription | None = None,
I'm not a huge fan of mixing data types like this in function args. You may want to consider creating different class constructors on the DerivedDataDescription class: from_data_description and from_data_description_path

2023-07-06 17:02 UTC, jtyoung84 commented on tests/test_utils.py
> +        from aind_data_schema.data_description import DataDescription, DerivedDataDescription, ExperimentType, Modality
It should be fine to add these to the imports at the top

2023-07-06 17:06 UTC, jtyoung84 requested changes
Left a few notes. I'd recommend moving the code into the DerivedDataDescription class instead of putting it as a utils method.

2023-07-06 17:34 UTC, alejoe91 commented on tests/test_utils.py
> +            data_description = DataDescription.construct(**data_description_dict)
Parse obj will fail for old schema versions! So this is on purpose and mismatches are handled later. That's why I added old files to test with.

2023-07-06 17:34 UTC, alejoe91 commented on src/aind_data_schema/utils/aind_utils.py
> +    subject_id: str = None,
done

2023-07-06 17:34 UTC, alejoe91 commented on src/aind_data_schema/utils/aind_utils.py
> +    existing_data_description: str | Path | DataDescription | None = None,
I made two separate args ;)

2023-07-06 17:35 UTC, alejoe91 commented on pyproject.toml
> +    'packaging',
done

2023-07-10 14:22 UTC, alejoe91 commented
@jtyoung84 ready to review ;)

2023-07-10 14:23 UTC, alejoe91 commented on src/aind_data_schema/utils/aind_utils.py
> +    existing_data_description: str | Path | DataDescription | None = None,
done, split in `from_data_description`, `rom_data_description_file`, `from_scratch`

2023-07-10 18:49 UTC, jtyoung84 commented on src/aind_data_schema/data_description.py
> +    @staticmethod
I think it might be better to make this a classmethod instead of a staticmethod. The return would be `cls(name=..., subject_id=..., etc.)`

2023-07-10 18:50 UTC, jtyoung84 commented on src/aind_data_schema/data_description.py
> +        derived_data_description = DerivedDataDescription(process_name=process_name, **derived_data_description_dict)
I don't think process_name is a field or property of DerivedDataDescription

2023-07-10 18:53 UTC, jtyoung84 commented on src/aind_data_schema/data_description.py
> +    def from_scratch(
I'm not sure how this is different than the standard class constructor

2023-07-10 18:56 UTC, jtyoung84 commented on src/aind_data_schema/data_description.py
> +        existing_data_description_dict = data_description.dict()
It might be less complicated to use the DataDescription attributes directly instead of converting everything to a dictionary

2023-07-10 18:57 UTC, jtyoung84 commented on src/aind_data_schema/data_description.py
> +    skip_existing_data_description_keys = [
This is duplicated on line 408

2023-07-10 19:01 UTC, jtyoung84 commented on src/aind_data_schema/data_description.py
> +    def from_data_description_file(
I think it should be simple enough for a user to open a file and parse it into a model. I'm not sure if we want to add a method in this repo that does that. If so, we should create a generic method in the base class.

2023-07-10 19:03 UTC, jtyoung84 commented on src/aind_data_schema/data_description.py
> +    base_data_description_dict["creation_time"] = now.time()
I feel like we should just set defaults in the pydantic model rather than creating a method in the python module

2023-07-11 08:06 UTC, alejoe91 commented on src/aind_data_schema/data_description.py
> +        derived_data_description = DerivedDataDescription(process_name=process_name, **derived_data_description_dict)
It's needed by the constructor to make the label: https://github.com/AllenNeuralDynamics/aind-data-schema/blob/main/src/aind_data_schema/data_description.py#L305-L308

2023-07-11 08:06 UTC, alejoe91 commented on src/aind_data_schema/data_description.py
> +    def from_scratch(
good point

2023-07-11 08:13 UTC, alejoe91 commented on src/aind_data_schema/data_description.py
> +    base_data_description_dict["creation_time"] = now.time()
not sure how one would set the `datetime.now()` as default in the pydantic model...

2023-07-11 08:21 UTC, alejoe91 commented on src/aind_data_schema/data_description.py
> +        existing_data_description_dict = data_description.dict()
We need the dict later to skip some keys. Not sure how to do it with the DataDescription object

2023-07-11 08:26 UTC, alejoe91 commented on src/aind_data_schema/data_description.py
> +    skip_existing_data_description_keys = [
removed

2023-07-11 08:26 UTC, alejoe91 commented on src/aind_data_schema/data_description.py
> +    def from_data_description_file(
removed

2023-07-12 02:46 UTC, jtyoung84 commented
@dyf I set the `investigators` field to default to an empty list. Is that cool with you?
@alejoe91 This tries to parse info from a DataDescription model. I didn't want to override the defaults with AIND specific stuff though. It's possible to explicitly set fields that you don't want to pull though.

2023-07-12 07:59 UTC, alejoe91 commented
@jtyoung84 looking great! Thanks for working on it and extending the tests :)

2023-07-12 19:39 UTC, dyf requested changes
Can we define these functions elsewhere? Say, some sort of legacy.py module? We can still import them to be validators here, but they make the schema hard to read.

2023-07-13 16:05 UTC, jtyoung84 approved these changes

2023-07-13 16:05 UTC, merged