Feat behavior
AllenNeuralDynamics/aind-data-schema pull request #425
Opened 2023-07-22 22:29 UTC by saskiad

closes #352

2023-07-24 16:15 UTC, dyf requested changes
Some small things.  Does this affect Mekhla's FIP ophys metadata converter?

2023-07-24 16:15 UTC, dyf commented on src/aind_data_schema/device.py
>      viewing_distance: Decimal = Field(..., title="Viewing distance (cm)", units="cm")
replace w unit+value?

2023-07-24 16:15 UTC, dyf commented on src/aind_data_schema/device.py
> +    spout_diameter: float = Field(..., title="Spout diameter (mm)")
unit+value

2023-07-24 16:15 UTC, dyf commented on src/aind_data_schema/device.py
> +    stimulus_type: str = Field("Water delivery", title="Stimulus type")
should this be a constant?

2023-07-24 16:15 UTC, dyf commented on src/aind_data_schema/device.py
> +    minimum_impedance: float = Field(..., title="Minimum impedance (ohms)", units="ohms")
unit+value for `minimum_impedance`, `rated_noise_power`, `sensitivity`, and `test_spectrum_bandwidth`

2023-07-24 16:26 UTC, saskiad commented on src/aind_data_schema/device.py
>      viewing_distance: Decimal = Field(..., title="Viewing distance (cm)", units="cm")
until that's merged, I can't use it

2023-07-24 16:26 UTC, saskiad commented on src/aind_data_schema/device.py
> +    spout_diameter: float = Field(..., title="Spout diameter (mm)")
same

2023-07-24 16:27 UTC, saskiad commented on src/aind_data_schema/device.py
> +    stimulus_type: str = Field("Water delivery", title="Stimulus type")
yes. Since the stimulus in the session is a Union, we need something to indicate what the types of instances are.

2023-07-24 16:27 UTC, saskiad commented on src/aind_data_schema/device.py
> +    minimum_impedance: float = Field(..., title="Minimum impedance (ohms)", units="ohms")
same as above

2023-07-24 16:28 UTC, saskiad commented
> Some small things. Does this affect Mekhla's FIP ophys metadata converter?

How would I know if it affects it or not?

2023-07-24 21:52 UTC, mekhlakapoor commented
> Some small things. Does this affect Mekhla's FIP ophys metadata converter?

It should be an easy fix-- i just need to change StimulusPresentation to StimulusEpoch.

2023-07-28 15:14 UTC, dyf commented
@saskiad add `const=True` to the `Field(...)` declarations for `stimulus_type` and this is gtg.

2023-07-28 22:04 UTC, saskiad commented
> @saskiad add `const=True` to the `Field(...)` declarations for `stimulus_type` and this is gtg.

I'll do that. I have more things to change based on feedback from behavior people so they'll be new commits before I finish the PR. I'll make it a draft.

2023-08-05 00:06 UTC, saskiad commented on src/aind_data_schema/device.py
> +    stimulus_type: str = Field("Water delivery", title="Stimulus type")
Oh, it's possible we want a different name for this. This is in the rig, saying what kind of stimulus device it is. So maybe we call it something like "stimulus device" instead of stimulus type because that will be overloaded.

2023-08-05 00:09 UTC, saskiad commented on src/aind_data_schema/device.py
> +    minimum_impedance: float = Field(..., title="Minimum impedance (ohms)", units="ohms")
we've removed these fields

2023-09-05 19:49 UTC, dyf requested changes
let's pivot back to paired `x` and `x_unit` fields for now, since unit with value is paused.

2023-09-06 15:13 UTC, merged