Adding generic calibration class for acquisition
AllenNeuralDynamics/aind-data-schema pull request #436
Opened 2023-08-04 17:23 UTC by camilolaiton

Adding a generic calibration class for acquisition. I am adding this since John needs to track other metadata related to the microscope maintenance.

I included:

- Date of calibration
- Description
- Notes

I believe @miketaormina can use inherit this class in the `LightSourcePowerCalibration` here: https://github.com/AllenNeuralDynamics/aind-data-schema/pull/379

2023-08-04 18:11 UTC, dyf commented
@camilolaiton can you just update Mike's branch directly? https://github.com/AllenNeuralDynamics/aind-data-schema/tree/feat-imaging-calibration

2023-08-04 22:19 UTC, saskiad commented
I think for a generic class we should have input and output dictionaries. I know for the behavior calibrations and laser calibrations we will need this.
If we anticipate having solutions (e.g. cleaning agents as in the example here) then we should use the reagent class as an optional input

2023-08-04 22:28 UTC, saskiad commented
also given that we need this class for lots of different types of sessions, I would recommend putting this in core I think?

2023-08-04 22:30 UTC, saskiad commented on src/aind_data_schema/imaging/acquisition.py
> +    description: str = Field(..., title="Calibration description")
Instead of description, I would have "calibration_type" and make it an enum. Laser. Monitor. Speaker. Water valve. Chamber. Other

2023-08-04 22:32 UTC, saskiad commented on src/aind_data_schema/imaging/acquisition.py
> +    notes: Optional[str] = Field(..., title="Notes")
and input and output as dictionaries. Many calibrations involve testing different parameter settings and seeing the output.

2023-08-04 22:32 UTC, saskiad commented on examples/exaspim_acquisition.json
> +         "notes": "We used a special liquid XXX"
if we anticipate other calibrations to involve reagents we should add the reagent class as a optional field

2023-08-04 22:33 UTC, saskiad requested changes
see comments

2023-08-07 19:52 UTC, camilolaiton commented
Closing this merge to update Mike's branch. https://github.com/AllenNeuralDynamics/aind-data-schema/tree/feat-imaging-calibration

2023-08-07 19:52 UTC, closed without merging