add project class, deprecate `experiment_type`
AllenNeuralDynamics/aind-data-schema pull request #452
Opened 2023-08-14 19:49 UTC by dyf

2023-08-14 21:39 UTC, saskiad commented on src/aind_data_schema/data_description.py
> +    THP1 = BaseName(name="AIND Thalamus U19 - Project 1", abbreviation="th-p1")
I'd make the U19 TIM1, TIM2, TIM4. (TIM = Thalamus in the Middle - the name of the grant)

2023-08-14 21:40 UTC, saskiad commented on src/aind_data_schema/data_description.py
> +    EXASPIM = BaseName(name="Neural Dynamics - Glaser R00", abbreviation="exaspim")
is EXASPIM just the depmind collab or any exaspim data? Maybe it doesn't matter - but I'd maybe make a name that doesn't match modality so closely...

2023-08-14 21:42 UTC, saskiad commented on src/aind_data_schema/data_description.py
> +class Project(Enum, metaclass=BaseNameEnumMeta):
I think BCDC is missing

2023-09-12 18:09 UTC, saskiad commented on src/aind_data_schema/data_description.py
> +    # thalamus / medulla: what to do with these?
yeah, the thalamus/medulla is weird. 
And where is U19 TIM? Is that now divided across platforms? That doesn't feel right to me.

2023-09-12 18:11 UTC, saskiad commented on tests/test_data_description.py
> +            project="exaspim",
ditto. Or am I blind am not seeing it?

2023-09-15 23:08 UTC, saskiad commented on src/aind_data_schema/data_description.py
> +    HCR = BaseName(name="HCR platform", abbreviation="HCR")
can we say what HCR is in the name?

2023-09-15 23:15 UTC, saskiad requested changes
small tweaks - mostly for descriptions.

2023-09-15 23:15 UTC, saskiad commented on src/aind_data_schema/data_description.py
> +        f"^(?P<platform_abbreviation>.+?)_(?P<subject_id>.+?)_(?P<c_date>{RegexParts.DATE.value})_(?P<c_time>"
can we just call it platform? We use BaseName, which has a name and an abbreviation.

2023-09-15 23:15 UTC, saskiad commented on src/aind_data_schema/data_description.py
> +    """Abbreviated name for standardized data collection system."""
Just say name since we use BaseName

2023-09-15 23:15 UTC, saskiad commented on src/aind_data_schema/data_description.py
> +        description="Abbreviated name for standardized data collection system",
again, not abbreviated.
I'd maybe say this is the name of the primary data collection system.

2023-09-15 23:15 UTC, saskiad commented on src/aind_data_schema/data_description.py
>      project_id: Optional[str] = Field(
should we remove project_id? Do we have IDs?

2023-09-15 23:19 UTC, dyf commented on src/aind_data_schema/data_description.py
>      project_id: Optional[str] = Field(
yeah, `project_id` is lame

2023-09-15 23:20 UTC, dyf commented on src/aind_data_schema/data_description.py
> +        f"^(?P<platform_abbreviation>.+?)_(?P<subject_id>.+?)_(?P<c_date>{RegexParts.DATE.value})_(?P<c_time>"
this one I need to keep because it's for the regular expression (which can only match the abbreviation). the others I will change.

2023-09-21 00:00 UTC, jtyoung84 approved these changes

2023-09-26 17:21 UTC, saskiad commented on src/aind_data_schema/data_description.py
>      FIB = BaseName(name="Fiber photometry", abbreviation="fib")
How is FIB different from FIP?

2023-09-26 17:24 UTC, saskiad commented on src/aind_data_schema/data_description.py
>      OPHYS = BaseName(name="Optical physiology", abbreviation="ophys")
so we now have FIP, FIB, HSFP, SLAP and OPHYS? I'd feel better with a planar ophys modality since we use "Ophys" to refer to all of those modalities often so I'm not confident people will use it specifically. Or only have ophys and don't have fip, fib, hsfp, slap

2023-09-26 17:24 UTC, saskiad requested changes
two questions on modality names

2023-09-26 19:43 UTC, dyf commented on src/aind_data_schema/data_description.py
>      FIB = BaseName(name="Fiber photometry", abbreviation="fib")
woops, meant to have "fiber photometry" as a modality, and "FIP" as a platform.

2023-09-26 19:48 UTC, dyf commented on src/aind_data_schema/data_description.py
>      OPHYS = BaseName(name="Optical physiology", abbreviation="ophys")
I can imagine rigs that do multiple flavors of ophys, so I'll get rid of "ophys"

2023-09-26 19:57 UTC, saskiad approved these changes

2023-09-26 20:07 UTC, saskiad commented on src/aind_data_schema/data_description.py
> +    BVR_RECORD = BaseName(name="Behavior recording platform", abbreviation="bvr-record")
oh... I'm a little unclear on the difference between BVR_TRAIN and BVR_RECORD? why have these separate?

2023-09-26 20:52 UTC, merged