uploads schemas to new bucket
AllenNeuralDynamics/aind-data-schema pull request #473
Opened 2023-09-07 22:27 UTC by mekhlakapoor

closes #464

2023-09-07 22:33 UTC, jtyoung84 requested changes
We should switch to using repository variables instead of hardcoding the buckets. Give me a second to create the env vars.

2023-09-07 22:36 UTC, jtyoung84 commented on .github/workflows/tag.yml
> +      AWS_BUCKET_NEW: 'aind-data-schema-prod-o5171v'
I added these to the repo env vars. You should be able to access them like:
      AWS_BUCKET_OLD: ${{ vars.AWS_BUCKET_OLD }}
      AWS_BUCKET_NEW: ${{ vars.AWS_BUCKET_NEW }}

2023-09-08 16:10 UTC, yosefmaru approved these changes

2023-09-08 16:15 UTC, jtyoung84 approved these changes

2023-09-08 16:16 UTC, merged