Feat 456 bergamo
AllenNeuralDynamics/aind-data-schema pull request #477
Opened 2023-09-11 21:27 UTC by saskiad

closes 456

2023-09-11 21:58 UTC, saskiad commented
closes #456

2023-09-12 00:30 UTC, dyf requested changes
naming convention question

2023-09-12 00:30 UTC, dyf commented on src/aind_data_schema/stimulus.py
> +    stimulus: Union[OptoStim, VisualStim, BehaviorStim, PhotoStimulation] = Field(..., title="Stimulus")
Can we make this all either `<X>Stim` or `<X>Stimulation`?  I like spelling them out (e.g. `OpticalStimulation` instead of `OptoStim`).

2023-09-12 18:41 UTC, dyf approved these changes

2023-09-12 18:43 UTC, merged