New stack class
AllenNeuralDynamics/aind-data-schema pull request #479
Opened 2023-09-12 23:40 UTC by saskiad

closes #345  and closes #430

2023-09-12 23:45 UTC, saskiad commented
The new channel definition might impact SPIM acquisition ingest - who should we check with on that?

2023-09-13 20:51 UTC, saskiad commented
@camilolaiton @adamkglaser can you take a look at the new channel definition here (in the Tile.py file) and see if that's going to be a problem for your teams? I added some fields and changed the name (excitation wavelength instead of laser wavelength.)

2023-09-14 15:18 UTC, adamkglaser commented
No conflict on our end!

2023-09-14 16:25 UTC, camilolaiton approved these changes
I don't see any issues on our end as well. Thanks @saskiad!

2023-09-14 18:37 UTC, dyf requested changes
small change and a comment

2023-09-14 18:37 UTC, dyf commented on src/aind_data_schema/imaging/acquisition.py
> +    schema_version: str = Field("0.4.10", description="schema version", title="Version", const=True)
let's make this `0.5.0` since it breaks stuff

2023-09-14 18:37 UTC, dyf commented on src/aind_data_schema/ophys/ophys_session.py
> +class Stack(OphysSession):
Reminder that we will need to change this inheritance structure when we move to generic session. Will need to be that an OphysSession _has_  as stack rather than _is_ a stack.

2023-09-14 18:45 UTC, dyf approved these changes

2023-09-14 18:45 UTC, merged