feat-362-add-analysis-to-processing-schema
AllenNeuralDynamics/aind-data-schema pull request #482
Opened 2023-09-14 21:06 UTC by Sun-flow

closes #362 

Implements an analysis subtype of DataManipulation. Allows for tracking of processing separately from analysis in schema.

2023-09-15 19:17 UTC, saskiad commented on src/aind_data_schema/processing.py
> +        "0.2.5",
let's make this 0.3.0

2023-09-15 19:19 UTC, saskiad commented on src/aind_data_schema/processing.py
> +    person: str = Field(..., title="Person")
person should be in the pipelineProcess class.
And lets say "Person full name"? We need to indicate full name. Not sure if person is the right term....

2023-09-15 19:20 UTC, saskiad commented on src/aind_data_schema/processing.py
> +
here we want the person full name as well

2023-09-15 19:21 UTC, saskiad commented on src/aind_data_schema/processing.py
> +class DataManipulation(AindModel):
Do we need DataManipulation? Can we just use DataProcess?

2023-09-15 19:23 UTC, saskiad requested changes
A few changes - I'm not sure we need DataManipulation (or we can rename DataProcess to DataManipulation ... but it feels like it's just a wrapper of DataProcess

2023-09-19 16:56 UTC, Sun-flow commented on src/aind_data_schema/processing.py
> +class DataManipulation(AindModel):
Data process is a specific part of the pipeline, datamanipulation contains a set of these processes. This class is inhereted by both of our new pipeline classes, and is performing a different function than the DataProcess class is.

2023-09-19 18:07 UTC, saskiad commented on src/aind_data_schema/processing.py
> +    person: str = Field(..., title="Person")
Analyst Full name

2023-09-19 18:09 UTC, saskiad commented on src/aind_data_schema/processing.py
> +    processing_person: str = Field(
use "full name" instead of person to match how we do experimenter full name in procedures/sessions/etc

2023-09-19 18:10 UTC, saskiad commented on src/aind_data_schema/processing.py
> +class DataManipulation(AindModel):
I still don't understand - DataManipulation is a list of DataProcess. Why not just have a list of DataProcess in PipelineProcess and in AnalysisProcess?

2023-09-19 18:11 UTC, saskiad commented on src/aind_data_schema/processing.py
> +class DataManipulation(AindModel):
in fact right now DataProcess doesn't actually get used anywhere - or am I confused?

2023-09-20 20:46 UTC, Sun-flow commented on src/aind_data_schema/processing.py
> +class DataManipulation(AindModel):
Since DataManipulation is a parent class of both AnalysisPipeline and ProcessPipeline, it's effectively the same as having a list in either of them. But it maintains clarity of the shared structure, and reduces copy-paste code.

2023-09-20 20:46 UTC, Sun-flow commented on src/aind_data_schema/processing.py
> +class DataManipulation(AindModel):
> in fact right now DataProcess doesn't actually get used anywhere - or am I confused?

DataProcess is used within DataManipulation, which is inherited by ProcessPipeline and AnalysisPipeline.

2023-09-20 22:06 UTC, saskiad commented on src/aind_data_schema/processing.py
> +class PipelineProcess(DataManipulation):
oh I see. I think the problem is that the pipeline version applies to a list of processing steps. So having each step have pipeline version/url is not the right way. I think PipelineProcess(AindModel) can have the fields it has and then List[DataProcess].

2023-09-20 22:07 UTC, saskiad commented on src/aind_data_schema/processing.py
> +class AnalysisProcess(DataManipulation):
and then this just is a DataProcess instance and we don't need to have the duplicate DataManipulation calss

2023-09-20 22:08 UTC, saskiad requested changes
see new comments - I still think we only need DataProcess and not DataManipulation

2023-09-29 17:21 UTC, saskiad commented on src/aind_data_schema/processing.py
> +
remove this blank line

2023-09-29 17:23 UTC, saskiad commented on src/aind_data_schema/processing.py
> +
up in line 49 or 51 there's a version and then there's code_version. I think these are redundant. I'd keep the code_version and remove the version.

2023-09-29 17:24 UTC, saskiad commented on src/aind_data_schema/processing.py
> +    analysis: Optional[List[AnalysisProcess]] = Field(
let's make this analyses (since it will be a list and likely have multiple items)

2023-09-29 17:24 UTC, saskiad commented on src/aind_data_schema/processing.py
> +
will you just add a notes field (Optional[str]) to this PiplineProcess class for me? Thanks!

2023-09-29 17:26 UTC, saskiad requested changes
a couple of little things, but otherwise it's good

2023-09-29 19:22 UTC, Sun-flow commented on src/aind_data_schema/processing.py
> +
From what I gathered, version was like "the software used to run the script" and code version was like "the version of the script". That was just my assumption though? These terms were both already here, I did not add them afaik.

2023-10-02 20:31 UTC, saskiad commented on src/aind_data_schema/processing.py
> +
yeah, let's change 'version' to 'software_version' so it's clear

2023-10-02 20:31 UTC, saskiad requested changes
just change that one field name and it's gtg!

2023-10-03 00:15 UTC, dyf requested changes
Small change - let's make sure that `AnalysisProcess.name` is always `ProcessName.ANALYSIS`.

2023-10-06 16:50 UTC, dyf approved these changes

2023-10-06 16:53 UTC, saskiad approved these changes

2023-10-06 16:56 UTC, merged