Unified rig/session schema
AllenNeuralDynamics/aind-data-schema pull request #486
Opened 2023-09-15 23:33 UTC by saskiad

2023-09-28 04:48 UTC, dyf commented on src/aind_data_schema/session.py
> +    behavior: Optional[Behavior] = Field(None, title="Behavior")
Is it one `Behavior` per stream or, is it per `Session`?

2023-09-28 04:48 UTC, dyf commented on src/aind_data_schema/session.py
> +    camera_names: Optional[List[str]] = Field(None, title="Cameras", unique_items=True)
Do we need these to indicate they are active? If so, maybe `activate_camera_names`?

2023-09-28 04:48 UTC, dyf commented on src/aind_data_schema/session.py
> +    stream_modalities: List[Modality] = Field(..., title="Modalities")
My (potentially wrong) understanding is that a stream should only have one modality, since a session can have many streams.

2023-09-28 04:48 UTC, dyf commented on src/aind_data_schema/session.py
> +    camera_names: Optional[List[str]] = Field(None, title="Cameras", unique_items=True)
and if so, would it be simpler just to have `active_device_names: Optional[List[str]]`? Just a thought, maybe useful to keep them separate.

2023-09-28 04:50 UTC, dyf commented on src/aind_data_schema/rig.py
> +    additional_devices: Optional[List[Device]] = Field(None, title="Additional devices", unique_items=True)
one more: do you just want this to be `devices: Optional[List[...everything...]]`?

2023-09-28 04:51 UTC, dyf reviewed
one more comment

2023-09-28 16:36 UTC, saskiad commented on src/aind_data_schema/session.py
> +    stream_modalities: List[Modality] = Field(..., title="Modalities")
no, a stream is everything recorded at one time. So multiple modalities. A session can have multiple streams, but can also be one stream. Think of it more as we positioned the electrodes, recorded activity in response to stimulus A, then moved the electrodes to different positions, recorded activity in response to stimulus B.

2023-09-28 16:38 UTC, saskiad commented on src/aind_data_schema/session.py
> +    behavior: Optional[Behavior] = Field(None, title="Behavior")
Honestly, I can imagine use cases for both, but I think session is the one we want for now. thanks

2023-09-28 16:38 UTC, saskiad commented on src/aind_data_schema/session.py
> +    camera_names: Optional[List[str]] = Field(None, title="Cameras", unique_items=True)
the fact that they are listed in the session means that they are active.

2023-09-28 16:40 UTC, saskiad commented on src/aind_data_schema/session.py
> +    camera_names: Optional[List[str]] = Field(None, title="Cameras", unique_items=True)
I considered that - I was going to make it something that was device type and name, because people do a bad job of naming devices. Eg. If I trusted people to name things "Camera A" and "DAQ 1" I would be fine with just a list of names, but I think the schema will be much easier to understand if we know what device is what.

2023-09-28 16:41 UTC, saskiad commented on src/aind_data_schema/rig.py
> +    additional_devices: Optional[List[Device]] = Field(None, title="Additional devices", unique_items=True)
I think there's benefit in knowing what's what. But maybe that can go in the device classes? Device type?

2023-09-28 16:44 UTC, saskiad commented
The thing I'm stuck on is where stimulus epoch lives. It presently lives within the Behavior class, because that's where the stimulus side of the behavior gets specifed. But in passive experiments, the behavior class won't be instantiated, but there still needs to be a stimulus epoch field outside of behavior. And we could remove it from Behavior, but conceptually that is weird...

2023-09-28 19:52 UTC, saskiad commented on src/aind_data_schema/rig.py
> +    additional_devices: Optional[List[Device]] = Field(None, title="Additional devices", unique_items=True)
here's a question - we're going to need validators that say "if modality is ephys then ephys_assemblies and stick_microscopes can not be empty" etc. If we make the list of devices, my hunch is that validation will be harder. But I don't know the validators that well - what do you think?

2023-10-02 16:18 UTC, jsiegle requested changes
Overall this looks good, it will definitely streamline things. I assume this will deprecate `ephys_session` and `ephys_rig` once it's merged?

2023-10-02 20:35 UTC, saskiad commented on src/aind_data_schema/session.py
> +    stick_microscopes: Optional[List[DomeModule]] = Field(
But they aren't the same. The camera_names is the list of names of cameras - mostly the behavior cameras. Whereas stick_microscopes are DomeModules that have angle and position information. That will get lost if we remove this.

2023-10-02 20:36 UTC, saskiad commented on src/aind_data_schema/session.py
> +
moving to #505

2023-10-02 20:36 UTC, saskiad commented on src/aind_data_schema/session.py
> +    ephys_modules: Optional[List[EphysModule]] = Field(None, title="Ephys modules", unique_items=True)
Moving to #505

2023-10-02 20:37 UTC, saskiad commented on src/aind_data_schema/device.py
> +
moving to #505

2023-10-02 20:43 UTC, dyf commented on src/aind_data_schema/rig.py
> +    schema_version: str = Field("0.1.0", description="schema version", title="Version", const=True)
@jsiegle if we did this then `Rig` would be version-locked with the schema library as a whole, which means we wouldn't have a way to communicate how individual core models have changed.  Unless you are suggesting something else?

2023-10-02 20:43 UTC, saskiad commented on src/aind_data_schema/session.py
> +    stick_microscopes: Optional[List[DomeModule]] = Field(
I can move the 'stick_microscopes' to 'Stream' - I am torn on whether it belongs there or here.

2023-10-02 22:28 UTC, jsiegle commented on src/aind_data_schema/session.py
> +    stick_microscopes: Optional[List[DomeModule]] = Field(
My logic was that the stick microscope doesn't generate data on its own -- only the camera inside it does, and these cameras are associated with microscopes in `rig.json`. However, we do need to specify the arc and module angle of each microscope, so the `stick_microscopes` does need to go in `session.json`. But it's not technically a manipulator module, since it doesn't have a manipulator. I'm realizing that this is why we separated `DomeModule` and `ManipulatorModule` previously. We could either add back the `DomeModule` class, or make the `manipulator_coordinates` optional.

2023-10-04 00:02 UTC, dyf reviewed
Some minor comments, but otherwise I think all that's left is to update the example to use `Rigs` and `Session`.

2023-10-06 17:47 UTC, dyf approved these changes

2023-10-06 17:49 UTC, merged