Feat 24 coords
AllenNeuralDynamics/aind-data-schema pull request #52
Opened 2022-11-04 20:38 UTC by mekhlakapoor

Closes #24

2022-11-04 20:40 UTC, mekhlakapoor commented
generates schema to look like this for coords: 

<img width="468" alt="Screen Shot 2022-11-04 at 1 39 53 PM" src="https://user-images.githubusercontent.com/54870020/200070787-35b0ca88-9c09-4d6e-927c-efbc35c6ebdd.png">

2022-11-04 22:13 UTC, dyf requested changes
Looks good! A couple changes, please :).

2022-11-04 22:13 UTC, dyf commented on src/aind_data_schema/ephys/ephys_session.py
> +    X: float = Field(..., title="X (mm)", units="mm")
I think X/Y/Z/AP/DV/ML can be lower case

2022-11-04 22:13 UTC, dyf commented on src/aind_data_schema/ephys/ephys_session.py
>  class CcfCoords(BaseModel):
now that it's organized like this, let's move the `ccf_version` field off of `EphysRg` and put it as a field on `CcfCoords`.  it can be required, default to 'CCFv3'.

2022-11-04 22:13 UTC, dyf commented on src/aind_data_schema/ephys/ephys_session.py
>  class Field3dCoordinatesMm(BaseModel):
I've been thinking the name `Field3dCoordinatesMm` is a little hokey. Can you rename it to `Coordinates3d`?

2022-11-04 22:13 UTC, dyf commented on src/aind_data_schema/ephys/ephys_session.py
>  class Field3dCoordinatesMm(BaseModel):
I'm thinking we may want to make `units` a field at some point, but let's do that later.

2022-11-04 22:18 UTC, dyf commented on src/aind_data_schema/ephys/ephys_session.py
>  class CcfCoords(BaseModel):
(I guess it should actually default to `CcfVersion.CCFv3`

2022-11-04 22:57 UTC, jtyoung84 commented
Other than the "describedBy" field, we want to resolve the jsonschema keys in snake case. This may require something like:
https://stackoverflow.com/questions/67995510/how-to-inflect-from-snake-case-to-camel-case-post-the-pydantic-schema-validation

2022-11-04 22:59 UTC, dyf commented
> (Maybe this can be opened as a separate issue) Other than the "describedBy" field, we want to resolve the jsonschema keys in snake case. This may require something like: https://stackoverflow.com/questions/67995510/how-to-inflect-from-snake-case-to-camel-case-post-the-pydantic-schema-validation

Ah yeah, this is default behavior for the `pydantic` `BaseModel.schema_json` method.  Let's investigate this in another thread.

2022-11-04 23:26 UTC, saskiad commented on src/aind_data_schema/ephys/ephys_session.py
> +    targeted_lab_coordinates: Field3dCoordinatesMm = Field(
based on Josh's feedback we are removed the lab coordinates. I thought I had already removed that... did that get reverted? Either way, let's remove targeted_lab_coordinates.

2022-11-04 23:28 UTC, saskiad commented on src/aind_data_schema/ephys/ephys_session.py
> +    targeted_lab_coordinates: Field3dCoordinatesMm = Field(
same here for lab coordinates. We can remove later too if that's easier

2022-11-04 23:30 UTC, saskiad approved these changes

2022-11-05 00:04 UTC, dyf approved these changes
yay!

2022-11-05 00:04 UTC, merged