feat-169 adding validators for 'Other'
AllenNeuralDynamics/aind-data-schema pull request #522
Opened 2023-10-09 22:41 UTC by Sun-flow

closes #169 

Adds a validator that checks to ensure there is text in the `notes` field whenever an `enum.OTHER` instance is passed in.

Locations I have found that contain reference to `enum.OTHER` and contain a `notes` field: `procedures.SpecimenProcedure`, `processing.DataProcess`, `session.RewardDelivery`, `behavior_session.RewardDelivery`, `instrument.Instrument`, `mri_session.MRIScan`

2023-10-10 13:28 UTC, dyf commented on src/aind_data_schema/behavior/behavior_session.py
> +    def other_notes(cls, v):
can we call this "validate_other"?

2023-10-10 13:34 UTC, dyf requested changes
A few requests regarding on naming, and such. Please apply everywhere they apply (I stopped typing "ditto" after awhile).

2023-10-10 13:34 UTC, dyf commented on src/aind_data_schema/behavior/behavior_session.py
> +            raise ValueError("Other must be specified in notes")
This message is unclear - maybe, "If reward_solution is "Other", the notes field must be non-empty."

2023-10-10 13:34 UTC, dyf commented on src/aind_data_schema/imaging/instrument.py
> +    def other_notes(cls, v):
same as above, call it "validate_other"

2023-10-10 13:34 UTC, dyf commented on src/aind_data_schema/behavior/behavior_session.py
> +            raise ValueError("Other must be specified in notes")
Let's check for an empty string as well. I think `... and not v.get("notes")` will handle both cases, but please confirm.

2023-10-10 13:34 UTC, dyf commented on src/aind_data_schema/imaging/instrument.py
> +            raise ValueError("Instrument Type: Other must be specified in notes")
same comment from above applies to these two messages and string checks.

2023-10-10 13:34 UTC, dyf commented on src/aind_data_schema/imaging/mri_session.py
> +    def other_notes(cls, v):
ditto for this one

2023-10-10 13:34 UTC, dyf commented on tests/test_imaging.py
> +        with self.assertRaises(ValidationError):
add a test for `notes=""` for at least one of these

2023-10-11 06:24 UTC, saskiad commented on src/aind_data_schema/behavior/behavior_session.py
> +            raise ValueError("Other must be specified in notes")
While we can only test that the notes is not empty, I think the instructions we want to give people is to provide what the Other is in the notes. But I do like having an error message that points people to where the problem is. So maybe something like "reward_solution of "Other" must be specified in the notes"

2023-10-11 06:25 UTC, saskiad reviewed
Ditto David's comments

2023-10-14 15:48 UTC, dyf approved these changes

2023-10-14 15:49 UTC, merged