fix: updates union types
AllenNeuralDynamics/aind-data-schema pull request #525
Opened 2023-10-10 20:01 UTC by jtyoung84

Closes #518 

- Fixes issues with de-serializing fields with Union types
- Updates test_examples to output more informative error message

2023-10-11 21:21 UTC, mekhlakapoor commented on examples/procedures.json
when I add a newline at the end of file, it fails coverage tests

2023-10-12 11:59 UTC, dyf requested changes

2023-10-12 11:59 UTC, dyf commented on src/aind_data_schema/session.py
> +            List[Union[Laser, LightEmittingDiode]],
It is confusing, but here `Laser` and `LightEmittingDiode` are not from `device.py`.  They are actually device configuration classes. We need to add `device_type` to `Laser` and `LightEmittingDiode` in this file.  

I'm going to create an issue to make this less confusing in a subsequent PR, but for the time being let's just add `device_type` to the models above.

2023-10-12 17:09 UTC, jtyoung84 commented on src/aind_data_schema/session.py
> +            List[Union[Laser, LightEmittingDiode]],
Added device_type to those classes

2023-10-12 17:44 UTC, merged