Feat 500 add Analysis Description
AllenNeuralDynamics/aind-data-schema pull request #535
Opened 2023-10-12 19:43 UTC by Sun-flow

closes #500 

Implements a class similar to RawDataDescription, for the use of Analysis. 

Name format: `<project-abbreviation>_<analysis-name>_<date>_<time>`

2023-10-12 20:06 UTC, Sun-flow commented
@dyf do you think this is the right way to ensure no hyphens are in the name? 

I don't see any examples of the string being checked to exclude certain characters, unless it is hidden in the Regex in a way I don't notice. I see the `NO_UNDERSCORES` Regex, but it's not used for name checking only for field input.

2023-10-18 21:17 UTC, jtyoung84 commented on src/aind_data_schema/data_description.py
> +    ANALYZED = (
We probably should use re.compile to precompile the regex patterns.

2023-10-18 21:19 UTC, jtyoung84 commented on src/aind_data_schema/data_description.py
> +    def __init__(self, analysis_name, **kwargs):
It's probably tech-debt that needs to be cleaned up elsewhere also, but we should avoid writing custom constructors on pydantic models. You can just override the project_name field to make it mandatory instead of doing the check here. This information doesn't get serialized into the json_schema. I'll leave it up to @dyf as to whether we should fix it as a tech-debt ticket.

2023-10-19 12:19 UTC, dyf requested changes

2023-10-19 12:19 UTC, dyf commented on src/aind_data_schema/data_description.py
> +    ANALYZED = (
https://github.com/AllenNeuralDynamics/aind-data-schema/issues/545

2023-10-19 12:19 UTC, dyf commented on src/aind_data_schema/data_description.py
> +    def __init__(self, analysis_name, **kwargs):
Agree with @jtyoung84 . Go ahead and override `project_name` here and make it required instead of optional.

2023-10-19 19:09 UTC, Sun-flow commented on src/aind_data_schema/data_description.py
> +    def __init__(self, analysis_name, **kwargs):
The only reason I can see that it might still be useful is that we are constructing custom label fields, which differ between models. Should I just not have a custom label?

2023-10-19 19:22 UTC, jtyoung84 commented on src/aind_data_schema/data_description.py
> +    def __init__(self, analysis_name, **kwargs):
You can make it a property like:
```
@property
def label(self):
  return f"{self.project_name}_{self.analysis_name}"
```
or if you want it to be a part of the schema, you'll need to use a `validator` or `root_validator`

2023-10-24 16:55 UTC, dyf approved these changes

2023-10-24 16:56 UTC, dyf commented
@Sun-flow I didn't mean to approve this before the tests were passing.  Go ahead and fix those and then we can merge.

2023-10-25 18:14 UTC, dyf requested changes

2023-10-25 18:14 UTC, dyf commented on src/aind_data_schema/schema_upgrade/data_description_upgrade.py
> +            project_name=self._get_or_default(self.old_data_description_model, "projectname", kwargs),
I think this should still have an underscore in it?

2023-10-27 17:00 UTC, Sun-flow commented on src/aind_data_schema/schema_upgrade/data_description_upgrade.py
> +            project_name=self._get_or_default(self.old_data_description_model, "projectname", kwargs),
The problem is that we have made `"_"` an invalid character for project name.

2023-10-27 17:01 UTC, Sun-flow commented on src/aind_data_schema/schema_upgrade/data_description_upgrade.py
> +            project_name=self._get_or_default(self.old_data_description_model, "projectname", kwargs),
oh this is for a getter, so maybe you're right

2023-10-27 17:03 UTC, Sun-flow commented on src/aind_data_schema/schema_upgrade/data_description_upgrade.py
> +            project_name=self._get_or_default(self.old_data_description_model, "projectname", kwargs),
no, leaving the underscore causes validation errors. I could use a hyphen, if you prefer

2023-11-01 15:07 UTC, dyf approved these changes

2023-11-01 15:08 UTC, merged