Feat 344 slap
AllenNeuralDynamics/aind-data-schema pull request #544
Opened 2023-10-18 11:32 UTC by saskiad

closes #344
closes #346
closes #347

2023-10-18 11:34 UTC, saskiad commented
@KasparP Trying to get these finished - we revamped the rig/session schema overall so now I'm adding in the slap2 stuff. I still have some questions about the devices - and what are stable parameters (rig schema) and what are variable parameters (session schema). For now, take a look at this and see if anything jumps out to you. I'll find some time when we can sit down and look at it when I'm back in town.

2023-10-31 22:23 UTC, KasparP approved these changes
All changes look good. We will work on translating metadata to this format in coming months, which will probably require further changes of this type.

2023-11-01 15:33 UTC, dyf requested changes
A few small suggestions.

2023-11-01 15:33 UTC, dyf commented on src/aind_data_schema/device.py
> +    speed_unit: str = Field("Rotations per minute", title="Speed unit")
should this be a unit in units.py?

2023-11-01 15:33 UTC, dyf commented on src/aind_data_schema/device.py
> +    on_time: Decimal = Field(..., title="On time (fraction of cycle)")
add "fraction of cycle" as unit?

2023-11-01 15:33 UTC, dyf commented on src/aind_data_schema/session.py
> +class SlapType(Enum):
`SlapSessionType`?

2023-11-01 15:33 UTC, dyf commented on src/aind_data_schema/session.py
> +    slap_fovs: Optional[Slap] = Field(None, title="Slap2 field of view")
Can we rename `Slap` -> `SlapFieldOfView`? We have `Slap` as a modality and that would make the distinction clear.

2023-11-02 00:08 UTC, saskiad commented on src/aind_data_schema/device.py
> +    speed_unit: str = Field("Rotations per minute", title="Speed unit")
I don't expect us to use it in other places, so I'm not sure it makes sense to do that. But we can if you think we should

2023-11-02 00:08 UTC, saskiad commented on src/aind_data_schema/device.py
> +    on_time: Decimal = Field(..., title="On time (fraction of cycle)")
it's technically unitless

2023-11-02 00:08 UTC, saskiad commented on src/aind_data_schema/device.py
> +    on_time: Decimal = Field(..., title="On time (fraction of cycle)")
or I guess that could be the unit... like percent... okay I'll do that

2023-11-02 05:23 UTC, dyf approved these changes

2023-11-02 16:20 UTC, merged