external links
AllenNeuralDynamics/aind-data-schema pull request #559
Opened 2023-10-24 21:29 UTC by mekhlakapoor

closes #555

2023-10-24 23:04 UTC, dyf requested changes

2023-10-24 23:04 UTC, dyf commented on src/aind_data_schema/metadata.py
> +    CODEOCEAN = "CodeOcean"
small tweak, let's use `Code Ocean` with a space, unless @jtyoung84 you think we should snake- or camel-case things.

2023-10-24 23:26 UTC, jtyoung84 commented on src/aind_data_schema/metadata.py
> +    CODEOCEAN = "CodeOcean"
`Code Ocean` is fine with me

2023-10-25 18:12 UTC, dyf approved these changes

2023-10-25 18:27 UTC, merged