Feat 588 daq validator
AllenNeuralDynamics/aind-data-schema pull request #607
Opened 2023-11-15 21:38 UTC by Sun-flow

closes #588 

Adds validators to rig and session schema for DAQ channels to ensure that if a DAQ is connected, the port it is connected to is a named and existing device in the schema.

2023-11-17 21:15 UTC, saskiad commented on src/aind_data_schema/rig.py
> +        objectives = values.get("objectives")
we can probably remove objectives, filter, lens as I can't imagine a way that they can connect to the daq. Probably a few more too. 
At the same time, there's sometimes value in being overcomplete.

2023-11-17 21:18 UTC, saskiad commented on src/aind_data_schema/rig.py
> +        for device_type in [daqs, stimulus_devices, light_sources, patch_coords,detectors, objectives, filters, lenses, digital_micromirror_devices, polygonal_scanners, pockels_cells, additional_devi
is there a reason to build this around device_type? Can we not have this be 
`for device in [stimulus_devices, light sources]...`
maybe that won't iterate properly ... because we want each device within each of these classes of device_types... is that right?

2023-11-17 21:19 UTC, saskiad commented on src/aind_data_schema/rig.py
> +        ephys_assemblies = values.get("ephys_assemblies")
I think we want to remove the assemblies, assemblies consist of specific devices and it would be the device that is connected to the daq

2023-11-17 21:20 UTC, saskiad commented on src/aind_data_schema/rig.py
> +                device_names += [camera.camera.name for camera in camera_device]
this confuses me - why isn't it device.name?

2023-11-17 21:20 UTC, saskiad commented on src/aind_data_schema/rig.py
> +                device_names += [camera.camera.name for camera in camera_device]
ditto below

2023-11-17 21:24 UTC, Sun-flow commented on src/aind_data_schema/rig.py
> +        for device_type in [daqs, stimulus_devices, light_sources, patch_coords,detectors, objectives, filters, lenses, digital_micromirror_devices, polygonal_scanners, pockels_cells, additional_devi
what you are describing is what this loop does.

I grouped all fields that have a list of devices nested inside of them, so the first loop moves through each larger class, and the second loop (the list comprehension) iterates through each device in the nested structure.

2023-11-17 21:25 UTC, saskiad commented on src/aind_data_schema/rig.py
> +        if mouse_platform is not None:
why isn't mouse_platform in line 126?

2023-11-17 21:25 UTC, Sun-flow commented on src/aind_data_schema/rig.py
> +        if mouse_platform is not None:
Mouse platform does not require iteration, it is just a single element

2023-11-17 21:26 UTC, saskiad requested changes
looks close - a few questions

2023-11-22 00:09 UTC, saskiad commented on src/aind_data_schema/imaging/instrument.py
> +        optical_tables = values.get("optical_tables")
let's remove optical table, enclosure, lenses and fluorescence filters. None of them can be connected to a daq

2023-11-22 00:11 UTC, saskiad commented on tests/test_imaging.py
> +from aind_data_schema.rig import NeuropixelsBasestation
it's a little weird to use the NeuropixelsBasestation in the imaging example since NeuropixelsBasestation cannot be used in an imaging context. Is it possible to use a different DAQ device? I'm willing to write this test if that would help. lmk.

2023-11-22 00:13 UTC, saskiad commented on tests/test_imaging.py
> +from aind_data_schema.rig import NeuropixelsBasestation
My recommendation would to be to use the DAQ from the exaspim example in this test - you don't need all the channels, but if you want to just copy the whole thing you can do that too.

2023-11-27 16:58 UTC, merged