Feat 628 improve datadesc upgrader
AllenNeuralDynamics/aind-data-schema pull request #635
Opened 2023-12-01 16:16 UTC by Sun-flow

closes #628 

Updates to `DataDescriptionUpgrader`, `DataDescription`, and `ModalityUpgrader`.

`map_modality` function added to `data_description_upgrade.py` to convert outdated modalities to modern ones.

similar lookup added to `DataDescription` for `DataLevel` validation.

Error handling for funding if funding does not exist.

2023-12-01 16:22 UTC, dyf requested changes
couple small things, but otherwise looks okay

2023-12-01 16:22 UTC, dyf commented on src/aind_data_schema/schema_upgrade/data_description_upgrade.py
> +        if funding_source is not None:
let's move this logic all into a new `FundingUpgrade.upgrade_funding_source`. this line would turn into:

`funding_source = FundingUpgrade.upgrade_funding_source(funding_source)`.

2023-12-01 16:22 UTC, dyf commented on tests/test_schema_upgrade.py
> +            'platform': Platform('SMARTSPIM'),
```
`platform`: Platform.SMARTSPIM
```
 is simpler, I think?

2023-12-13 21:38 UTC, jtyoung84 commented
@Sun-flow I incorporated this into the V2 upgrade. Can you verify that it's there and whether this can be closed?

2024-01-08 16:54 UTC, closed without merging