changed injection materials, update example and test
AllenNeuralDynamics/aind-data-schema pull request #657
Opened 2023-12-15 00:32 UTC by saskiad

closes #626

2023-12-15 16:09 UTC, dyf commented on src/aind_data_schema/core/procedures.py
> +    virus_TARS_id: Optional[str] = Field(None, title="Virus ID, usually beings 'AiV'")
I don't particularly like putting an Allen-internal thing at the top level here. An alternative is to just have `identifiers: List[VirusIdentifier]`, and then:

```python
class VirusIdentifier(BaseModel):
   virus_id: str
   plasmid_id: str
   registry: VirusRegistry # <-- "TARS" goes here
```
addgene could be one of those?

I don't feel too strongly about this.

2023-12-15 16:09 UTC, dyf commented on src/aind_data_schema/core/procedures.py
> +class OtherInjectionMaterial(Reagent):
I'm not clear why `OtherInjectionMaterial` is a `Reagent` but `ViralMaterial` is not.

2023-12-15 16:10 UTC, dyf commented on src/aind_data_schema/core/procedures.py
> +class OtherInjectionMaterial(Reagent):
maybe because we need to use the work `titer` instead of `concentration`?

2023-12-15 17:32 UTC, saskiad commented on src/aind_data_schema/core/procedures.py
> +    virus_TARS_id: Optional[str] = Field(None, title="Virus ID, usually beings 'AiV'")
we want both Addgene and TARS information for viruses. But I agree that we move the TARS info into a subclass.

2023-12-15 17:34 UTC, saskiad commented on src/aind_data_schema/core/procedures.py
> +class OtherInjectionMaterial(Reagent):
The problem is that non-viral injection materials and viral injection materials use an orthogonal set of fields and it is really confusing for people to have a bunch of irrelevant fields morphed together like that. This provides clarity.
I agree on name - wasn't thrilled to call it other.

2023-12-15 23:38 UTC, saskiad commented on src/aind_data_schema/core/procedures.py
> +    virus_TARS_id: Optional[str] = Field(None, title="Virus ID, usually beings 'AiV'")
because TARS isn't public facing I'm reluctant to make it a Registry

2023-12-18 18:59 UTC, dyf requested changes
couple questions

2023-12-18 18:59 UTC, dyf commented on src/aind_data_schema/core/procedures.py
> +class TarsIds(AindModel):
Let's call this `TarsVirusIdentifiers` in case we need other stuff from TARS in the future?

2023-12-18 18:59 UTC, dyf commented on src/aind_data_schema/core/procedures.py
>      prep_date: Optional[date] = Field(
should `pred_date` and `prep_protocol` be on `ViralMaterial`? I can imagine wanting to know these for non-TARS viruses.

Also wondering if `prep_lot_number` is a generally useful field, not TARS-specific.

2023-12-18 21:45 UTC, saskiad commented on src/aind_data_schema/core/procedures.py
>      prep_date: Optional[date] = Field(
I don't think we'll know `prep_date` and `prep_protocol` for viral prep lots that we don't make ourselves.

same for `prep_lot_number`. I can try to ask - that is one that might be more likely to have - but I'm guessing when we get viruses ready to inject we don't have that information...

2023-12-19 17:07 UTC, dyf commented
@saskiad and I discussed pausing this one to get confirmation from AIBS that this is a good way to describe viruses.

2024-01-04 23:38 UTC, saskiad commented
@dyf I just went over the `ViralMaterial`  and related classes with Bosiljka and she was happy with how this is organized. I might have forgotten some questions we had but I'd like to get this wrapped up so remind me if there are other things

2024-01-05 23:02 UTC, dyf approved these changes

2024-01-05 23:02 UTC, merged