ci: modifies actions workflow for uploading schemas
AllenNeuralDynamics/aind-data-schema pull request #666
Opened 2023-12-18 23:30 UTC by yosefmaru

Closes #532 

- An inline policy was added to the AWS role that gives permission to write to the schema bucket (old)

2023-12-18 23:41 UTC, jtyoung84 requested changes
We can probably just stop publishing to the old bucket all together

2023-12-18 23:41 UTC, jtyoung84 commented on .github/workflows/publish_prod.yml
> +      AWS_BUCKET_OLD: ${{ vars.AWS_BUCKET_OLD }}
Can't we just stop publishing to the old bucket?

2023-12-18 23:50 UTC, yosefmaru commented on .github/workflows/publish_prod.yml
> +      AWS_BUCKET_OLD: ${{ vars.AWS_BUCKET_OLD }}
Yeah, we can.

2023-12-19 17:43 UTC, jtyoung84 approved these changes

2023-12-19 17:44 UTC, merged