feat: updates tagged unions
AllenNeuralDynamics/aind-data-schema pull request #671
Opened 2023-12-19 22:52 UTC by jtyoung84

Merges the recent changes to the main branch.

The Annotated Union fields needed updated. The tests highlighted issues related to classes missing the required Literal fields needed for them to be used in tagged Union fields. I created a "class_tag" field that should be renamed to something else. Since there is already a "procedure_type" being used in the generic SpecimenProcedure class, then either the "class_tag" field needs to be called something other than "procedure_type" or the "procedure_type" field in the SpecimenProcedure class needs to be called something else.

2023-12-20 01:19 UTC, dyf requested changes
- rename `class_tag` -> `procedure_class`
- hard-code `procedure_class` and `procedure_type` for `SpecimenProcedure` subclasses
- add new values to `SpecimenProcedureName` as needed

2023-12-20 01:32 UTC, jtyoung84 commented
Is immunostaining and immunolabeling the same thing?

2023-12-20 19:29 UTC, dyf commented
Immunostaining is a kind/subset of immunolabeling, I believe.

2023-12-21 06:33 UTC, dyf approved these changes

2023-12-21 06:33 UTC, merged