adding olfactometer and stimulus
AllenNeuralDynamics/aind-data-schema pull request #678
Opened 2024-01-02 19:16 UTC by saskiad

closes #615

2024-01-02 20:46 UTC, dyf approved these changes
I think we need a generic stimulation model - lots of somewhat confusing overlap going on here.

2024-01-02 20:47 UTC, bruno-f-cruz requested changes

2024-01-02 20:47 UTC, bruno-f-cruz commented on src/aind_data_schema/models/devices.py
> +    position: Optional[RelativePosition] = Field(None, title="Relative position of the olfactometer")
I am a bit confused about this. Is there an example of another device with a position? In this case, this is the position of the odor tube end not the olfactometer itself. Similar to a Valve / Reward spout.

2024-01-02 20:47 UTC, bruno-f-cruz commented on src/aind_data_schema/models/devices.py
> +    flow_range_unit: str = Field("mL/min", title="Flow range unit")
`channel_type` should have a default of `Odor`
`flow_range` should only allow two values: 0-100 or 0-1000 ml/min (make 0-100 default)
`flow_range_unit` - Can this be a const?

`odor_vial_volume` and `odorant_volume`: should be nullable, since for carrier type, these settings will not apply

2024-01-02 20:47 UTC, bruno-f-cruz commented on src/aind_data_schema/models/devices.py
> +    flow_range_unit: str = Field("mL/min", title="Flow range unit")
Should there not be a cross-reference between `OlfactometerChannelConfig` and `OlfactometerChannel`?

2024-01-02 20:47 UTC, bruno-f-cruz commented on src/aind_data_schema/models/stimulus.py
> +    channel_index: int = Field(..., title="Channel index")
Wouldnt it make more sense to have the reference to the `OlfactometerChannel` object, instead of the arbitrary index?

2024-01-02 20:49 UTC, bruno-f-cruz commented
> I think we need a generic stimulation model - lots of somewhat confusing overlap going on here.

I think this goes back to one of my initial questions of why not implement abstract base classes in the schemas?

Should we not have:

```python
Stimulation(AindModel):
    pass
BehaviorStimulation(Stimulation)
    pass
```

It would also make extending the current schemas much easier

2024-01-02 20:51 UTC, saskiad commented on src/aind_data_schema/models/devices.py
> +    position: Optional[RelativePosition] = Field(None, title="Relative position of the olfactometer")
pretty much all devices have relative position. eg. monitor etc. 
But yes, we don't care where the olfactometer is - we care where the odor tube is. And we don't actually have any information about the odor tube in the schema at all...

2024-01-02 20:52 UTC, saskiad commented on src/aind_data_schema/models/devices.py
> +    flow_range_unit: str = Field("mL/min", title="Flow range unit")
The index serves as the cross-reference

2024-01-02 20:52 UTC, bruno-f-cruz commented on src/aind_data_schema/models/devices.py
> +    position: Optional[RelativePosition] = Field(None, title="Relative position of the olfactometer")
The easiest would be to change the property name to something more explicit. Maybe `odor_tube_position`?

2024-01-02 20:52 UTC, saskiad commented on src/aind_data_schema/models/stimulus.py
> +    channel_index: int = Field(..., title="Channel index")
oh, maybe...

2024-01-02 20:53 UTC, saskiad commented
> I think we need a generic stimulation model - lots of somewhat confusing overlap going on here.

issue #679

2024-01-02 22:38 UTC, saskiad commented on src/aind_data_schema/models/stimulus.py
> +    channel_index: int = Field(..., title="Channel index")
I don't think it can do this when the OlfactometerChannel is in a different schema

2024-01-03 04:55 UTC, bruno-f-cruz commented on src/aind_data_schema/models/devices.py
> +    port_index: Optional[int] = Field(None, title="Port index")
I think this should go back to being a string. I can see several cases where this index will not be an integer. Examples include: COM ports, Ip addresses and hashes.

2024-01-03 04:55 UTC, bruno-f-cruz commented on src/aind_data_schema/models/devices.py
> +    LOW = "0-100 ml/min"
This should be a Set instead of an Enum. It will make it future proof. You can even call it max range or capacity, if you want to have MaxRange/MaxCapacity: Set[float]

2024-01-03 04:55 UTC, bruno-f-cruz commented on src/aind_data_schema/models/devices.py
> +    flow_range: FlowRange = Field(..., title="Flow range")
I think it is fair for flow_range can have default 100, has most of the channels are odor channels and will most of the times have this setting. Also, all channels can be set to max 100, but not all channels can be set to 1000.

2024-01-03 04:55 UTC, bruno-f-cruz commented on src/aind_data_schema/models/devices.py
> +    odor_vial_volume: Optional[Decimal] = Field(None, title="Odor vial volume")
I am still a bit confused as to why the vial volume and odorant volume are part of the device and not of the stimuli. I don't see the distinction between these properties and, for instance, dilution percentage. Can you clarify? 

In general, I would reserve OlfactometerChannels (and this should probably inherit from an abstract Channel class) for specifying hardware (mostly electronics) I/O-related specs. In my mind, specifying the vial volume is akin to specifying the impedance of a BNC cable we connect to a nidaq board, which I don't see anywhere in the schema either. Seems like adding a bit too much detail at this point, IMO.

Regardless, if you do feel strongly about adding it I would ask to move it to the respective Stimulus class.

2024-01-03 16:46 UTC, saskiad commented on tests/test_rig.py
> +                        harp_device_version="1",
that's going to be addressed in a separate PR. Issue #632

2024-01-03 16:47 UTC, saskiad commented on src/aind_data_schema/models/devices.py
> +    port_index: Optional[int] = Field(None, title="Port index")
this isn't part of this PR

2024-01-03 16:47 UTC, bruno-f-cruz commented on tests/test_rig.py
> +                        harp_device_version="1",
Makes sense!

2024-01-03 16:51 UTC, saskiad commented on src/aind_data_schema/models/devices.py
> +    odor_vial_volume: Optional[Decimal] = Field(None, title="Odor vial volume")
I did this because this is what we decided in our meeting in November. If that's not what you want, we should probably just delete the issue and start over.

2024-01-03 17:00 UTC, bruno-f-cruz commented on src/aind_data_schema/models/devices.py
> +    port_index: Optional[int] = Field(None, title="Port index")
Not sure I follow. The diff tracker shows that the typing changed from a string to an integer. Sorry for the confusion.

2024-01-03 17:43 UTC, bruno-f-cruz commented on src/aind_data_schema/models/devices.py
> +    odor_vial_volume: Optional[Decimal] = Field(None, title="Odor vial volume")
After talking with @cindypoo, we agreed on dropping both the vial volume and odorant volume.

2024-01-04 19:03 UTC, saskiad commented on src/aind_data_schema/models/devices.py
> +    port_index: Optional[int] = Field(None, title="Port index")
I'm confused by this - I didn't touch this part of the code. But I'll do the harp device PR next that we discussed with Sonya so I'll get that cleaned up.

2024-01-04 21:20 UTC, bruno-f-cruz commented on src/aind_data_schema/models/devices.py
> +    flow_range: set = Field(default={0, 100}, title="Flow range")
Sorry I shoulda have made this point clearer! By set I meant something like:
replace:
``` python
flow_range: set = Field(default={0, 100}, title="Flow range")
```
with
 
``` python
flow_capacity: Literal[100, 1000] = Field(default=100, title="Flow range")
```
This way we don't have to conform to an Enumerator with predefined string values (i.e. Low and High) and we allow additional values to be added to the list if needed later.

2024-01-04 23:43 UTC, saskiad commented on src/aind_data_schema/models/devices.py
> +    flow_range: set = Field(default={0, 100}, title="Flow range")
ah, I see.

2024-01-05 04:17 UTC, bruno-f-cruz approved these changes
lgtm! thanks

2024-01-05 17:08 UTC, merged