exclude reward delivery from standard device validation
AllenNeuralDynamics/aind-data-schema pull request #683
Opened 2024-01-04 04:12 UTC by mochic

Attempts to address #674

2024-01-04 18:47 UTC, saskiad commented
I'd prefer to solve this by removing the `device_type` field from `RewardDelivery` (since it's not a device) and adding `name` that can have a default value of "Reward Delivery"

2024-01-04 22:59 UTC, mochic commented
@saskiad does this look ok? `device_type` appears to be required by STIMULUS_DEVICES which uses it as a discriminator.

2024-01-11 16:09 UTC, dyf commented
If you exclude delivery you won't be able to include reward delivery devices in the DAQ, e.g. the bottom of this:

https://github.com/AllenNeuralDynamics/aind-data-schema/pull/702

2024-01-12 00:32 UTC, saskiad commented
I think we need to rework the validator so that stimulus devices isn't listed in standard devices and is handles separately.

2024-01-12 00:37 UTC, saskiad commented on src/aind_data_schema/models/devices.py
> +    name: str = "Reward delivery"
if we're keeping the device_type then don't add the name.

2024-01-12 00:38 UTC, saskiad requested changes
If we're keeping device_type for the Reward delivery then don't add the name

2024-01-12 00:39 UTC, saskiad commented
> @saskiad If you exclude delivery from validation you won't be able to include reward delivery subdevices (spouts, solenoids) in the DAQ, e.g. the bottom of this:
> 
> #702

Agreed, removing it completely from validation is not an option. We can rework the validation to handle it better though.

2024-01-12 00:41 UTC, saskiad commented on src/aind_data_schema/models/devices.py
> +    name: str = "Reward delivery"
Oh, nevermind. We need the name. I'd still prefer to change the validation than to add this, but that will take time.

2024-01-24 23:58 UTC, closed without merging