in Subject schema removing MgiAlleleId in favor of PIDName
AllenNeuralDynamics/aind-data-schema pull request #696
Opened 2024-01-08 21:39 UTC by Sun-flow

closes #621 

Converts field `Subject.mgi_allele_ids` from taking `MgiAlleleId` to taking `PIDName`, and adds `MouseGenomeInformatics` to `Registry`

2024-01-09 16:32 UTC, dyf reviewed
@saskiad can approve, but j/w - what would these values be for something like?
https://www.informatics.jax.org/allele/MGI:3819121

`registry_identififer="MGI:3819121"`
and
`name="Ath30"`
?

2024-01-09 23:59 UTC, saskiad commented
> @saskiad can approve, but j/w - what would these values be for something like? https://www.informatics.jax.org/allele/MGI:3819121
> 
> `registry_identififer="MGI:3819121"` and `name="Ath30"` ?

we want that to be `name="Ath30"`, `registry="MGI"`, `registry_identifier="3819121"`

2024-01-10 04:34 UTC, saskiad commented on src/aind_data_schema/core/subject.py
> +    mgi_allele_ids: List[PIDName] = Field(default=[], title="MGI allele ids")
let's call this `alleles` (both field name and title) and add a description that says "Allele names and persitent IDs"

2024-01-10 04:34 UTC, saskiad requested changes
one small change, otherwise great!

2024-01-19 21:07 UTC, saskiad approved these changes

2024-01-19 21:07 UTC, merged