feat: added ophys_procedure py and json
AllenNeuralDynamics/aind-data-schema pull request #700
Opened 2024-01-09 23:51 UTC by micahwoodard

closes #660 

- Added ophys_procedure .py and ophys_procedure.json

2024-01-10 18:04 UTC, micahwoodard commented
Oh wait no I'm not done yet this is still just a draft! I need to get info from Kenta or Bryan about how to fill in the procedure for the ophys stuff. Right now the ophys_procedure.py is just a copy of procedure.py for reference.

2024-01-11 00:08 UTC, dyf commented
> Oh wait no I'm not done yet this is still just a draft! I need to get info from Kenta or Bryan about how to fill in the procedure for the ophys stuff. Right now the ophys_procedure.py is just a copy of procedure.py for reference.

Ah okay, sorry I jumped the gun :)

2024-01-11 19:14 UTC, micahwoodard commented
Used past procedure json from Bryan and added immunology data 
[procedures_672640 (1) 1.json](https://github.com/AllenNeuralDynamics/aind-data-schema/files/13907384/procedures_672640.1.1.json)

2024-01-13 19:37 UTC, saskiad commented on examples/ophys_procedures.py
> +                    lot_number="GR3361051-16, GR3361051-7, GR3361051-3",
how are there three lot numbers?

2024-01-13 19:38 UTC, saskiad commented on examples/ophys_procedures.py
> +            iacuc_protocol="TO ENTER",
use the same iacuc_protocol number as above. 2109. IACUC protocols usually cover all experiments in a project (or often a group of projects) rather than being procedure specific

2024-01-13 19:43 UTC, saskiad commented on examples/ophys_procedures.py
> +                                virus_tars_id="Addgene 62723-AAV5",
this is not a tars id. This is the addgene_id - there is a separate filed for that. (the 62723-AAV5, not the "addgene") - though note that this is addgene id does not match the name above. We can live with it, but just a heads up that we have a real virus name and a real addgene id that are for different things.

2024-01-13 19:44 UTC, saskiad commented on examples/ophys_procedures.py
> +            anaesthesia=Anaesthetic(type="Isoflurane", duration=3, level=1.5),
duration units default to minutes. It's impossible this surgery was 3 minutes long. I assume this is hours? So it needs to be converted to minutes, or you need to specify the units to be hours.

2024-01-13 19:44 UTC, saskiad commented on examples/ophys_procedures.py
> +            anaesthesia=Anaesthetic(type="Isoflurane", duration=3, level=1.5),
given that the second surgery is 30 minutes (which seems reasonable for a perfusion) I'd suggest making this one minutes too.

2024-01-13 19:49 UTC, saskiad commented on examples/ophys_procedures.py
> +                    rrid=PIDName(name="Chicken polyclonal to GFP(ab13970)", abbreviation="Anti-GFP antibody"),
ah - this might be unclear in how the schema is written. The rrid is a Research Resource Identifier. So the name should be the name of the name should be the name of the registry (ResearchResourceIdentifier) - if you use the registry class it will give you the name/abbreviation. And the registry_identify is the identifer for this particular antibody. "ab13970". And I'd recommend removing to from the name since it's provided here and makes it all clearer.

2024-01-13 19:51 UTC, saskiad commented on examples/ophys_procedures.py
> +                ),
Is there really only one immunolabeling step? I would expect this to be followed by a secondary immunolabeling step. This might be a question for someone else though...

2024-01-13 19:52 UTC, saskiad requested changes
Great start! There are a few places where things are in wonky places. Let me know if you have questions.

2024-01-16 22:27 UTC, micahwoodard commented on examples/ophys_procedures.py
> +                    rrid=PIDName(name="Chicken polyclonal to GFP(ab13970)", abbreviation="Anti-GFP antibody"),
I'm still a bit confused on this one. How Bryan had laid it out, it seemed like it should be like this?
rrid=PIDName(name="Chicken polyclonal to GFP", abbreviation= "Anti-GFP antibody", registry_identifier= "ab13970")
I'm a little confused by how you are saying it is supposed to be set up

2024-01-16 22:33 UTC, micahwoodard commented on examples/ophys_procedures.py
> +                    rrid=PIDName(name="Chicken polyclonal to GFP(ab13970)", abbreviation="Anti-GFP antibody"),
Oh wait I see the registry class so maybe something closer to this?
rrid=PIDName(name="Chicken polyclonal to GFP", abbreviation= "Anti-GFP antibody",registry = Registry.RRID, registry_identifier= "ab13970")

2024-01-16 22:36 UTC, micahwoodard commented on examples/ophys_procedures.py
> +                    rrid=PIDName(name="Chicken polyclonal to GFP(ab13970)", abbreviation="Anti-GFP antibody"),
Oh wait okay final comment is it that using the registry class takes care of the name and abbreviation so all you need is to fill in registry and registry_identifier? So something like this?
rrid=PIDName(registry = Registry.RRID, registry_identifier= "ab13970")

2024-01-16 22:54 UTC, micahwoodard commented
I believe I correctly changed some of the wonky things to make more sense. The only thing I'm not sure on is how to correctly format the rrid field of antibody class

2024-01-17 03:58 UTC, saskiad commented on examples/ophys_procedures.py
> +                    rrid=PIDName(name="Chicken polyclonal to GFP(ab13970)", abbreviation="Anti-GFP antibody"),
yes, that last one is what we're looking for!

2024-01-22 16:13 UTC, micahwoodard commented
@saskiad Is this any better or still not exactly how to use Registry.RRID? I ran into requirement issues with rrid=PIDName(registry = Registry.RRID, registry_identifier= "ab13970")

2024-01-23 19:10 UTC, saskiad commented on examples/ophys_procedures.py
> +                    rrid=PIDName(name="Chicken polyclonal to GFP(ab13970)", abbreviation="Anti-GFP antibody"),
the name should be the name of the thing we are providing a RRID for. So in this case:
name="Chicken polyclonal to GFP", registry=Registry.RRID, registry_identifier="XXXX"

2024-01-23 19:16 UTC, saskiad commented on examples/ophys_procedures.py
> +                    rrid=PIDName(name="Chicken polyclonal to GFP(ab13970)", abbreviation="Anti-GFP antibody"),
ah, I see the problem. we end up with too many names that say the same thing. What if  (and this is a suggestion, so feel free to disagree)
What if we make 
`class Reagent(PIDName):
"""""
source = str {and this should really be Institution ... I think there's a separate issue/PR on this though)
lot_number = ...
experation_date = ...`

2024-01-23 19:18 UTC, saskiad commented
> @saskiad Is this any better or still not exactly how to use Registry.RRID? I ran into requirement issues with rrid=PIDName(registry = Registry.RRID, registry_identifier= "ab13970")

see comments in thread above this.  (Also as a note, I get so many github notifications in my inbox that I rarely see real ones, so maybe ping me on teams if there is something you need me to look at)

2024-01-25 22:24 UTC, jtyoung84 approved these changes

2024-01-25 22:39 UTC, saskiad commented on examples/ophys_procedures.json
> +                        "registry": null,
the registry needs to be Addgene

2024-01-25 22:40 UTC, saskiad commented on examples/ophys_procedures.py
> +                                name="62723-AAV5",
this is missing a Registry - needs to be Addgene

2024-01-25 22:40 UTC, saskiad requested changes
couple of places missing Registry

2024-01-25 22:41 UTC, saskiad commented on examples/ophys_procedures.py
> +                                name="62723-AAV5",
ah, it's the same thing - but this is the place to fix it

2024-01-26 01:27 UTC, saskiad approved these changes

2024-01-26 02:10 UTC, merged