Feat 632 harp
AllenNeuralDynamics/aind-data-schema pull request #705
Opened 2024-01-12 04:09 UTC by saskiad

closes #632

2024-01-12 04:12 UTC, saskiad commented
I think we're going to want a tool for mapping or validating that whoAmI values to harp_device_types so that people don't get them wrong.

2024-01-12 16:10 UTC, bruno-f-cruz requested changes
First review. We can iterate Thanks!!!

2024-01-12 23:33 UTC, saskiad commented on src/aind_data_schema/models/devices.py
We currently have serial number, firmware version, hardware version. So I need to add Core version and Tag version? What's a tag version? (And I guess what's a core version too - I think I have an idea, but I'm not 100% sure)

2024-01-12 23:34 UTC, saskiad commented on src/aind_data_schema/models/devices.py
I wonder if we want to make an enum that includes both the Harp Device Type and the whoamI so that people who don't know the four number whoami but do know it's a olfactometer can make that easier?

2024-01-12 23:39 UTC, bruno-f-cruz commented on src/aind_data_schema/models/devices.py
Thats what I suggested above. I should have formated it sorry!

```python
DeviceWhoAmI(strEnum):
	Behavior: 1234
	LoadCells: 1235
	Lickometer: 1235
```

2024-01-12 23:43 UTC, bruno-f-cruz commented on src/aind_data_schema/models/devices.py
> We currently have serial number, firmware version, hardware version. So I need to add Core version and Tag version? What's a tag version? (And I guess what's a core version too - I think I have an idea, but I'm not 100% sure)

The firmware version seems overcomplicated tho, cant it simply be a string? We just need a major and minor versions.

Core version is the version of the harp core that the device is running. I.e. the Device has an application firmware and core protocol implementation, they are both versioned.

Tag is a concept that we don't yet have in Harp devices but we are reviewing the current version of the protocol to include it soon. It is basically a short string that can be used to `Tag` a release with additional information (e.g. pre-release, github hash that gave rise to it, etc...). I believe we discussed this with Sonya last time.

2024-01-18 18:01 UTC, saskiad commented
why does it say versions aren't updated and then when you update them it gives a merge conflict? That doesn't make any sense to me

2024-01-18 18:17 UTC, bruno-f-cruz requested changes

2024-01-18 18:17 UTC, bruno-f-cruz commented on src/aind_data_schema/models/harp_types.py
If we are going down the route of adding a class per device, can we then please add a generic device?
```python
class GenericHarpDevice(_HarpDeviceType):
    whoami: int = Field(..., ge=0, le=9999)
```

2024-01-18 18:17 UTC, bruno-f-cruz commented on src/aind_data_schema/models/devices.py
>      # required fields
If we are not ready to consider #708 , can we add this extra field to this class?

2024-01-18 18:17 UTC, bruno-f-cruz commented on src/aind_data_schema/models/devices.py
> +    firmware: Optional[Software] = Field(None, title="Firmware")
Any chance we can simplify the Firmware field? I am not sure what would I even enter under the required field "name". JUst trying to understand why would firmware and hardware versions be defined differently

2024-01-18 18:21 UTC, bruno-f-cruz requested changes
Check comments above. I got two review requests for some reason...

2024-01-18 21:38 UTC, saskiad commented on src/aind_data_schema/models/harp_types.py
Are there really generic harp devices? This contradicts my understanding of them.

2024-01-18 21:39 UTC, saskiad commented on src/aind_data_schema/models/devices.py
> +    firmware: Optional[Software] = Field(None, title="Firmware")
sure - this was what we had decided together in our original plan but easy to change.

2024-01-18 21:41 UTC, bruno-f-cruz commented on src/aind_data_schema/models/harp_types.py
I am worried that we dont have a way to annotate prototype devices and makes us extremely reliant on the data-schemas being updated. Remeber we want to use this to instantiate a task not only to annotate after the fact. @poofjunior might have some thoughts on this too.

2024-01-18 21:43 UTC, bruno-f-cruz commented on src/aind_data_schema/models/devices.py
> +    firmware: Optional[Software] = Field(None, title="Firmware")
Ooops sorry I didnt check the data type you suggested back then. My bad!

2024-01-18 21:51 UTC, Poofjunior commented on src/aind_data_schema/models/harp_types.py
@saskiad it is possible to create a harp device "ad hoc" by just uploading some firmware to a [Pi Pico](https://www.raspberrypi.com/documentation/microcontrollers/raspberry-pi-pico.html) board. 

We have done this before, and we will plan to do it more frequently to prototype more long-term devices that will later replace them. If useful, here are some promises that I can make about these ad hoc prototypes:
* they will have their own repository
  * example: [harp.pico.ephys-sync](https://github.com/AllenNeuralDynamics/harp.pico.ephys-sync)
  * example: [harp.pico.cam-trigger](https://github.com/AllenNeuralDynamics/harp.pico.cam-trigger)
* they will run a version of Harp Protocol which will enable us to poll for information about its firmware

Here are a couple options for annotating them.
* we call them a "generic harp device."
* we call them a "prototype harp device."
Since these devices will "speak Harp protocol" and have their own repository, most of the remaining fields can be filled in normally.

LMK what you think, or if I can clarify anything!

2024-01-18 21:58 UTC, bruno-f-cruz commented on src/aind_data_schema/models/harp_types.py
I would just leave it as a generic device and not tie it to the Pico. You never know what kind of devices we might need to spin in the future. Regarding the documentation of the devices, it should go elsewhere and not into this class. AFAIK this class is just a glorified enumerator of existing (known) harp devices.

2024-01-19 04:47 UTC, saskiad commented
closes #708

2024-01-20 13:55 UTC, bruno-f-cruz requested changes

2024-01-20 13:55 UTC, bruno-f-cruz commented on src/aind_data_schema/models/harp_types.py
> +class HarpDeviceType:
GenericHarpDevice wont validate against the discriminator

2024-01-22 18:27 UTC, saskiad commented on src/aind_data_schema/models/harp_types.py
> +class HarpDeviceType:
my guess is that we need to have a constant whoami for the generic harp device.

2024-01-22 18:31 UTC, bruno-f-cruz commented on src/aind_data_schema/models/harp_types.py
> +class HarpDeviceType:
Not sure I follow. Why do you need a const WhoAmI? The discriminator takes a 'name' not WhoAmI.
I think all we need is to add a line to HarpDeviceType that establishes a default whoami for the generic device

```python
GENERIC_HARP_DEVICE= GenericHarpDevice(whoami=0)
```

Wouldnt this work?

2024-01-22 18:38 UTC, saskiad commented on src/aind_data_schema/models/harp_types.py
> +class HarpDeviceType:
I don't know why. I know that when I removed the whoami field as literal that it created a whole slew of errors. You're welcome to hunt it down, but my guess is that the whoami for the generic needs to be a literal

2024-01-23 04:55 UTC, bruno-f-cruz commented on src/aind_data_schema/models/harp_types.py
> +class HarpDeviceType:
Submitted a PR with a possible solution. Not sure if you are ok with it?

2024-01-23 19:07 UTC, bruno-f-cruz requested changes

2024-01-23 19:07 UTC, bruno-f-cruz commented on ephys_rig.json
This should probably be discarded before merging to main?

2024-01-23 19:07 UTC, bruno-f-cruz commented on examples/ephys_rig.json
> +         "name": "ThermistorPrototypeBoard",
I used this is a placeholder to test the code, I think the previous default makes more sense!

2024-01-23 19:07 UTC, bruno-f-cruz commented on examples/ephys_rig.py
> +    name="ThermistorPrototypeBoard",
Same as above, change the default name so people don't get confused.

2024-01-24 21:21 UTC, bruno-f-cruz approved these changes
Check the comment on the rogue json file

2024-01-24 21:21 UTC, bruno-f-cruz commented on ephys_rig.json
I really think you want to delete this but I will approve :p

2024-01-24 21:22 UTC, saskiad commented on ephys_rig.json
which file?

2024-01-24 21:23 UTC, saskiad commented on ephys_rig.json
I see it

2024-01-24 21:25 UTC, merged