return procedure name to SpecimenProcedure
AllenNeuralDynamics/aind-data-schema pull request #714
Opened 2024-01-17 21:11 UTC by Sun-flow

SpecimenProcedure.procedure_name was erroneously removed in a prior PR. We are reinstating it.

also changing SpecimenProcedureName -> SpecimenProcedureType for clarity.

2024-01-17 21:27 UTC, dyf requested changes

2024-01-17 21:27 UTC, dyf commented on src/aind_data_schema/core/procedures.py
> +    procedure_type: SpecimenProcedureType = Field(..., title="Procedure name")
Please update the title on this one.

2024-01-17 21:31 UTC, saskiad commented on src/aind_data_schema/core/procedures.py
> +    procedure_type: SpecimenProcedureType = Field(..., title="Procedure name")
+1

2024-01-17 21:33 UTC, Sun-flow commented on src/aind_data_schema/core/procedures.py
> +    procedure_type: SpecimenProcedureType = Field(..., title="Procedure name")
fixed now

2024-01-17 21:47 UTC, saskiad commented on src/aind_data_schema/core/procedures.py
> +    procedure_name: Optional[str] = Field(None, title="Procedure name")
it might be helpful to have a description for this that says "Name of specific procedure used" or something like that. Not necessary

2024-01-17 21:47 UTC, saskiad submitted a review, later dismissed
yep, just David's comment and one small suggestion

2024-01-18 16:50 UTC, dyf approved these changes
I went ahead and added a description per Saskia's comment, merging now.

2024-01-18 16:51 UTC, merged