Species Upgrades & validators
AllenNeuralDynamics/aind-data-schema pull request #716
Opened 2024-01-18 00:25 UTC by Sun-flow

`Subject.source` optional -> REQUIRED
Breeding info removed from `Subject`, added to new class `BreedingInfo`

Add validators:
- `Subject.genotype` required for mouse subjects
- `Subject.breeding_info` required when `Subject.source == Allen Institute`

2024-01-18 01:11 UTC, Sun-flow commented on tests/test_metadata.py
> +        d1 = Metadata(name="ecephys_655019_2023-04-03_18-17-09", location="bucket", subject=Subject.model_construct()) #errors
@jtyoung84 Can you look at this and give me input on solving it? `Subject.model_construct()` is not valid because it lacks required fields, and im not sure how I should manifest the same test goal here.

2024-01-18 01:15 UTC, saskiad commented on src/aind_data_schema/core/subject.py
> +                raise ValueError("Genotype should be provided for mouse subjects")
can you make the error say "Full genotype must be provided for mouse subjects"

2024-01-18 01:15 UTC, saskiad commented on tests/test_metadata.py
> +            source=Institution.AIND,
make the Institute.AI

2024-01-18 01:17 UTC, saskiad commented on tests/test_metadata.py
>              genotype="Emx1-IRES-Cre;Camk2a-tTA;Ai93(TITL-GCaMP6f)",
this is not actually a full genotype. which I know is subtle, and maybe not necessary for a test, but it's good for us to use it properly. Full genotype has two copies of each allele. So it might be "Emx1-IRES-Cre/wt;Camk2a-tTA/Camk2a-tTA; Ai93(TITL..)/wt" for each allele there needs to be a slash and either the same thing or a wt

2024-01-18 01:17 UTC, saskiad commented on tests/test_metadata.py
> +            source=Institution.AIND,
Institution.AI

2024-01-18 01:17 UTC, saskiad commented on tests/test_metadata.py
>              genotype="Emx1-IRES-Cre;Camk2a-tTA;Ai93(TITL-GCaMP6f)",
ditto above

2024-01-18 01:18 UTC, saskiad reviewed
great start - a few small comments

2024-01-18 01:25 UTC, jtyoung84 commented on src/aind_data_schema/core/subject.py
> +
You need the model_validator annotation here. Although using a field_validator on breeding_info might be more appropriate

2024-01-18 01:26 UTC, jtyoung84 commented on src/aind_data_schema/core/subject.py
> +            if self.breeding_info is None:
Most style guides recommend avoiding nested if statements if it can be avoided. You can group this into one.

2024-01-18 01:27 UTC, jtyoung84 commented on src/aind_data_schema/core/subject.py
> +    breeding_info: Optional[BreedingInfo] = Field(None, title="Breeding Info")
Since all of the fields in BreedingInfo are defaulted to None, as an alternative we could consider just
```
breeding_info: BreedingInfo = Field(BreedingInfo(), title="Breeding Info")
```
but it isn't a huge deal

2024-01-18 01:27 UTC, Sun-flow commented on src/aind_data_schema/core/subject.py
> +
If i used a field validator, I don't think I could check the source field for it's value? or could i?

2024-01-18 01:28 UTC, Sun-flow commented on src/aind_data_schema/core/subject.py
> +            if self.breeding_info is None:
will do

2024-01-18 01:28 UTC, jtyoung84 commented on src/aind_data_schema/core/subject.py
> +
If you do use a model_validator, it requires a `return self`

2024-01-18 01:28 UTC, jtyoung84 commented on tests/test_metadata.py
> +        d1 = Metadata(name="ecephys_655019_2023-04-03_18-17-09", location="bucket", subject=Subject.model_construct()) #errors
I'll look into it

2024-01-18 01:29 UTC, Sun-flow commented on src/aind_data_schema/core/subject.py
> +    breeding_info: Optional[BreedingInfo] = Field(None, title="Breeding Info")
I am waiting on @saskiad to give input on what our defaults for that class should be. I would not expect it to be default empty ultimately, I think some/all of the fields would be required. Just a dummy for now so she can have thoughts

2024-01-18 01:30 UTC, jtyoung84 commented on src/aind_data_schema/core/subject.py
> +
You can inspect other fields using a field validator as long as they are listed above the field in the fields list

2024-01-18 01:31 UTC, Sun-flow commented on tests/test_metadata.py
> +        d1 = Metadata(name="ecephys_655019_2023-04-03_18-17-09", location="bucket", subject=Subject.model_construct()) #errors
The error is showing up again, with my most recent round of edits.

2024-01-18 01:32 UTC, jtyoung84 commented on src/aind_data_schema/models/institutions.py
> +    SUBJECT_SOURCES = Annotated[Union[AI, JAX], Field(discriminator="name")]
This need to be the actual classes and not the instances. So something like
`Annotated[Union[AllenInstitute, JacksonLabs], Field(discriminator="name")]`

2024-01-18 01:33 UTC, Sun-flow commented on src/aind_data_schema/core/subject.py
> +
so there is a hierarchy based on order , okay. if we were using the default `validator(cls, v)` import method, would i find those fields in `cls.field`?

2024-01-18 01:34 UTC, jtyoung84 commented on src/aind_data_schema/models/institutions.py
> +    SUBJECT_SOURCES = Annotated[Union[AI, JAX], Field(discriminator="name")]
Let me know if this fixes the error downstream

2024-01-18 01:36 UTC, jtyoung84 commented on src/aind_data_schema/core/subject.py
> +
The function signature looks like (cls, v: (Some input type like str), info: ValidationInfo) -> expected output type

There is an example here: https://docs.pydantic.dev/latest/concepts/validators/#field-validators

2024-01-18 01:37 UTC, jtyoung84 commented on src/aind_data_schema/core/subject.py
> +
There is also an example for the  "notes" fields in a few classes here: https://github.com/AllenNeuralDynamics/aind-data-schema/blob/main/src/aind_data_schema/core/session.py

2024-01-18 01:40 UTC, Sun-flow commented on src/aind_data_schema/models/institutions.py
> +    SUBJECT_SOURCES = Annotated[Union[AI, JAX], Field(discriminator="name")]
Ok, all other errors are resolved, the error I tagged on originally still exists. I think it will continue to exist as long as we are generating an invalid model for subject.

2024-01-18 01:46 UTC, jtyoung84 commented on src/aind_data_schema/models/institutions.py
> +    SUBJECT_SOURCES = Annotated[Union[AllenInstitute(), JacksonLaboratory()], Field(discriminator="name")]
With the parentheses, just
```
SUBJECT_SOURCES = Annotated[Union[AllenInstitute, JacksonLaboratory], Field(discriminator="name")]
```

2024-01-18 01:57 UTC, jtyoung84 commented on tests/test_metadata.py
> +        d1 = Metadata(name="ecephys_655019_2023-04-03_18-17-09", location="bucket", subject=Subject.model_construct()) #errors
I have a rough idea of why it's breaking. I'll add a fix tomorrow. Converting to field validators might help.

2024-01-18 05:34 UTC, saskiad commented on src/aind_data_schema/core/subject.py
> +    breeding_info: Optional[BreedingInfo] = Field(None, title="Breeding Info")
all these fields should be required for the `BreedingInfo` class

2024-01-18 05:36 UTC, saskiad commented on src/aind_data_schema/models/institutions.py
> +    SUBJECT_SOURCES = Annotated[Union[AllenInstitute(), JacksonLaboratory()], Field(discriminator="name")]
I'd prefer we not limit the Institutions we can use and have a validator to exclude AIBS and AIND.

2024-01-19 17:11 UTC, saskiad commented on src/aind_data_schema/models/institutions.py
> +    SUBJECT_SOURCES = Annotated[Union[AllenInstitute(), JacksonLaboratory()], Field(discriminator="name")]
Mice that are bred at the institute should have Allen Institute as a source and not Allen Institute for Neural Dynamics or Allen Institute for Brain Science.

2024-01-19 17:23 UTC, jtyoung84 commented on src/aind_data_schema/models/institutions.py
> +    SUBJECT_SOURCES = Annotated[Union[AllenInstitute(), JacksonLaboratory()], Field(discriminator="name")]
The main drawback of using validators is that users won't know which Institutions are allowed for that field until after they've already tried constructing the model. For example, unless we maintain the same list in the metadata-entry-app, the user will see the full list of Institutions in a dropdown menu, and only after they have tried saving the json will they get an error saying that the institution they selected isn't valid.

2024-01-19 18:37 UTC, Sun-flow commented on src/aind_data_schema/models/institutions.py
> +    SUBJECT_SOURCES = Annotated[Union[AllenInstitute(), JacksonLaboratory()], Field(discriminator="name")]
@saskiad lets sort out what our ideal implementation is here. I am lightly on Jon's side for this one, as it will make the GUI make most sense. If there was a way to do an exclusive union (ie, all of these items except these items, @jtyoung84), this would be really easy to do without needing to update a list when we add new institutions. Otherwise, i will just make a long list of all of them except AIND and AIBS.

2024-01-19 21:10 UTC, saskiad commented on src/aind_data_schema/models/institutions.py
> +    SUBJECT_SOURCES = Annotated[Union[AllenInstitute(), JacksonLaboratory()], Field(discriminator="name")]
Maintaining lists becomes a bottleneck. The reality is most Allen users aren't writing the subject metadata themselves and are pulling it from the service. It's collaborators and external users that are going to need this changed.

2024-01-19 21:59 UTC, jtyoung84 commented on src/aind_data_schema/models/institutions.py
> +    SUBJECT_SOURCES = Annotated[Union[AllenInstitute(), JacksonLaboratory()], Field(discriminator="name")]
> @saskiad lets sort out what our ideal implementation is here. I am lightly on Jon's side for this one, as it will make the GUI make most sense. If there was a way to do an exclusive union (ie, all of these items except these items, @jtyoung84), this would be really easy to do without needing to update a list when we add new institutions. Otherwise, i will just make a long list of all of them except AIND and AIBS.

It's simple enough to create a list from another list with a couple of items excluded though

2024-01-19 22:53 UTC, jtyoung84 commented on src/aind_data_schema/models/institutions.py
> +    SUBJECT_SOURCES = Annotated[Union[AllenInstitute(), JacksonLaboratory()], Field(discriminator="name")]
Oh, I think I get what you're saying. This is only for validating that if a mouse isn't bred in-house, then we want to check the institution?

2024-01-20 00:56 UTC, saskiad commented on src/aind_data_schema/models/institutions.py
> +    SUBJECT_SOURCES = Annotated[Union[AllenInstitute(), JacksonLaboratory()], Field(discriminator="name")]
The list of Institutions will grow, and each time we add to it we will need to update this enum as well. The validation is that people like to put "AIND" instead of "AI" but our mouse breeding is "AI" and not "AIND". So internal mice need to have the source as "AI". Presumably, json will be generated by the service for these data, which should be doing it correctly, but it would be good to have a validator to make sure if someone does make it by hand they don't do it wrong.
When there are mice from other sources, the service will not be making the json, and people need to specify the Institution that the mouse is from, and if the list of possible Institutions they can enter for this field isn't up to date, it will be a problem for them.

2024-01-20 01:27 UTC, dyf commented on src/aind_data_schema/models/institutions.py
> +    SUBJECT_SOURCES = Annotated[Union[AllenInstitute(), JacksonLaboratory()], Field(discriminator="name")]
It is annoying to have two lists, but if we handle this in a validator then the metadata UI won't know about it.

2024-01-23 19:03 UTC, saskiad commented on src/aind_data_schema/models/institutions.py
> +    SUBJECT_SOURCES = Annotated[Union[AllenInstitute(), JacksonLaboratory()], Field(discriminator="name")]
I recommend we not have a list then and let people make this mistake. I really don't want to maintain extra lists if we can avoid it and the reality is most Allen subject will be generated using the service that can be made to avoid this mistake.

2024-01-24 23:32 UTC, saskiad commented on src/aind_data_schema/core/subject.py
> +    mgi_allele_ids: List[MgiAlleleId] = Field(default=[], title="MGI allele ids")
I'd like to keep the field name as alleles and I'd like to continue using a PIDName structure where the MGI is the registry that is being used.

2024-01-24 23:32 UTC, saskiad commented on src/aind_data_schema/core/subject.py
> +    mgi_id: str = Field(..., title="MGI ID")
Does this need a class? Can't we use PIDName?

2024-01-24 23:33 UTC, Sun-flow commented on src/aind_data_schema/core/subject.py
> +    mgi_allele_ids: List[MgiAlleleId] = Field(default=[], title="MGI allele ids")
Hmm,  Ithink this came from when someone pushed to my branch........... frustrating. I'll try to track down what our new implementation should be.

2024-01-24 23:34 UTC, saskiad requested changes
I think you're undoing the recent changes we made to using PIDNames for alleles, and I don't want to undo that. See PR #696

2024-01-24 23:36 UTC, saskiad commented on src/aind_data_schema/core/subject.py
> +    mgi_allele_ids: List[MgiAlleleId] = Field(default=[], title="MGI allele ids")
PR #696

2024-01-25 00:31 UTC, saskiad commented on src/aind_data_schema/core/subject.py
> +    breeding_group: str = Field(None, title="Breeding Group")
make all these fields required within this class. That manes in needs to have `Field(..., title="")`. If the default is `None` then it's not actually required.

2024-01-25 00:33 UTC, saskiad commented on src/aind_data_schema/core/subject.py
> +    alleles: List[PIDName] = Field(default=[], title="MGI allele ids")
teeny edit for the alleles:
`title="Alleles", description="Allele names and persistent IDs"

2024-01-25 00:34 UTC, saskiad requested changes
we want the fields within BreedingInfo to be required. (the presence/absence of the word Optional is not actually what determines if a field is required or optional ... that's something I've learned recently)

2024-01-30 18:14 UTC, saskiad commented on src/aind_data_schema/core/subject.py
> +    source: Organization.ONE_OF = Field(
make this
'source: Organization.SUBJECT_SOURCES'

this is a sublist of possible sources

2024-01-30 18:18 UTC, saskiad reviewed
one small edit since we did add a sublist in the Organization class for possible sources for mouse, let's use that.

2024-01-30 18:21 UTC, saskiad approved these changes

2024-01-30 18:22 UTC, merged