feat: added protocol id to acquisition and session
AllenNeuralDynamics/aind-data-schema pull request #720
Opened 2024-01-22 16:41 UTC by micahwoodard

#641 
- Added protocol id to acquisition and session
- updated versions and examples

2024-01-23 19:05 UTC, saskiad commented on src/aind_data_schema/core/acquisition.py
> +    protocol_id: Optional[str] = Field(None, title="Protocol ID", description="DOI for protocols.io")
let's make this an optional List - I expect there will be situations where we need to provide a couple protocols.

2024-01-23 19:05 UTC, saskiad commented on src/aind_data_schema/core/session.py
> +    protocol_id: Optional[str] = Field(None, title="Protocol ID", description="DOI for protocols.io")
ditto here - make this a list.

2024-01-23 19:06 UTC, saskiad requested changes
minor change: let's have the protocol_id be a List so that we can have multiple protocols listed when necessary. Otherwise looks good!

2024-01-23 19:15 UTC, micahwoodard commented
Alright made it into list!

2024-01-23 19:25 UTC, jtyoung84 commented on src/aind_data_schema/core/acquisition.py
> +    protocol_id: Optional[list] = Field(None, title="Protocol ID", description="DOI for protocols.io")
We've been leaning towards using empty collections as defaults instead of Optional. So the type should be:
```
protocol_id: List[str] = Field([], title="Protocol ID", description="DOI for protocols.io")
```
If we really want an Optional type though, the field should be:
```
protocol_id: Optional[List[str]] = Field(None, title="Protocol ID", description="DOI for protocols.io")
```

2024-01-25 17:41 UTC, micahwoodard commented
Okay fixed with jon's suggestion

2024-01-25 22:20 UTC, jtyoung84 approved these changes

2024-01-25 22:42 UTC, saskiad approved these changes

2024-01-26 00:51 UTC, merged