ci: adds workflow to store latest version of schemas in a folder
AllenNeuralDynamics/aind-data-schema pull request #749
Opened 2024-01-30 19:10 UTC by yosefmaru

Closes #670

2024-02-01 22:41 UTC, jtyoung84 requested changes
I just realized that this might  need be done in the tag workflow since the tag job needs to run after all things have been committed

2024-02-01 23:27 UTC, yosefmaru commented
> I just realized that this might need be done in the tag workflow since the tag job needs to run after all things have been committed

That makes sense. I moved update_schemas job to the tag workflow. The tag job will need update_docs and update_schemas.

2024-02-02 01:47 UTC, jtyoung84 approved these changes

2024-02-02 01:48 UTC, jtyoung84 commented
@dyf @saskiad This pull request will automatically build and save the latest schemas to a folder called schemas in the root level of the project directory

2024-02-02 17:16 UTC, jtyoung84 commented on .github/workflows/tag.yml
> +          python -m pip install -e .
You may need a line to remove the contents of the old directory

2024-02-02 17:16 UTC, jtyoung84 requested changes
You may need a line to remove the contents of the old directory

2024-02-06 22:23 UTC, jtyoung84 approved these changes

2024-02-06 23:56 UTC, merged