metadata validator for smartspim
AllenNeuralDynamics/aind-data-schema pull request #752
Opened 2024-01-31 00:30 UTC by mekhlakapoor

closes #547

2024-01-31 18:35 UTC, saskiad commented on src/aind_data_schema/core/metadata.py
> +            raise ValueError("Procedures is missing injection materials.")
do all SmartSpim procedures involve injections? Would it be better to hinge this warning on if there is an Injection procedure in the list of subject procedures?

2024-01-31 18:52 UTC, mekhlakapoor commented on src/aind_data_schema/core/metadata.py
> +            raise ValueError("Procedures is missing injection materials.")
The injection materials check is based on the 2nd acceptance criteria here: https://github.com/AllenNeuralDynamics/aind-data-schema/issues/547 , but let me know if we should update that criteria.

2024-01-31 18:57 UTC, mekhlakapoor commented on src/aind_data_schema/core/metadata.py
> +
Also was not in the acceptance criteria but I can add that if we want. Should we move this to discussions thread?

2024-01-31 20:17 UTC, jtyoung84 commented on src/aind_data_schema/core/metadata.py
> +
I think it should be easy enough to add that check in this PR if we want that

2024-02-03 00:53 UTC, saskiad commented on src/aind_data_schema/core/metadata.py
> +                isinstance(surgery, BrainInjection) and getattr(surgery, "injection_materials", []) == []
ditto

2024-02-03 00:54 UTC, saskiad requested changes
I think we're better off using `Injection` rather than `BrainInjection`. Otherwise I think it looks good.

2024-02-03 01:05 UTC, saskiad approved these changes

2024-02-03 01:08 UTC, merged