feat: can have space in project name
AllenNeuralDynamics/aind-data-schema pull request #773
Opened 2024-02-14 21:22 UTC by micahwoodard

fixes #761 
- allow project name to have spaces

2024-02-14 21:26 UTC, micahwoodard commented
I changed the NO_SPECIAL_CHARS to allow spaces but can create new variable if that is what's needed

2024-02-14 21:52 UTC, saskiad approved these changes

2024-02-14 21:59 UTC, micahwoodard commented
Changed to have an additional variable in DataRegex to allow no special characters but space

2024-02-15 02:18 UTC, jtyoung84 commented on src/aind_data_schema/core/data_description.py
> +    NO_SPECIAL_CHARS_EXCEPT_SPACE = '^[^<>:;"/|? \\_]+$'
This is the same regex pattern as the line above

2024-02-15 02:20 UTC, jtyoung84 requested changes
Can you add a couple of unit tests that test the regex patterns are doing what's expected? You don't need to create entire models; you can pull the regex patterns by `DataDescription.NO_SPECIAL_CHARS`, etc.

2024-02-26 15:46 UTC, micahwoodard commented
Added some test for the different patterns but may need to add or change to better test

2024-02-28 23:48 UTC, jtyoung84 approved these changes

2024-02-28 23:48 UTC, merged