feat: automates schema version bump
AllenNeuralDynamics/aind-data-schema pull request #777
Opened 2024-02-16 18:56 UTC by yosefmaru

Closes #735

2024-02-26 17:37 UTC, jtyoung84 commented on examples/aind_smartspim_instrument.json
> +   "schema_version": "0.10.11",
Should this file be changed?

2024-02-26 17:43 UTC, jtyoung84 requested changes
The examples aren't being saved to the correct location

2024-02-26 18:17 UTC, yosefmaru commented on examples/aind_smartspim_instrument.json
> +   "schema_version": "0.10.11",
The instrument.py model is on version 0.10.11. I think the mismatch in version number is causing the CI check to fail. I needed to regenerate the json example file for the CI to pass.

2024-02-26 19:27 UTC, jtyoung84 approved these changes

2024-02-28 20:23 UTC, dyf approved these changes

2024-02-28 23:04 UTC, merged