791 add fields to fieldofview in session
AllenNeuralDynamics/aind-data-schema pull request #795
Opened 2024-02-26 18:40 UTC by arielleleon

Added new fields to the FieldOfView session object required for multiplane sessions.

2024-02-29 00:11 UTC, jtyoung84 commented on src/aind_data_schema/core/session.py
> +    power_unit: Optional[PowerUnit] = Field(PowerUnit.MW, title="Power unit")
I think we've been keeping the Unit fields as non-Optional and set with a default

2024-02-29 00:11 UTC, jtyoung84 commented on src/aind_data_schema/core/session.py
> +    scanfield_z_unit: Optional[SizeUnit] = Field(None, title="Z stage position unit")
I think we've been keeping the Unit fields as non-Optional and set with a default

2024-02-29 00:11 UTC, jtyoung84 requested changes
The examples in the examples folder may need to be updated

2024-03-04 23:52 UTC, arielleleon commented on src/aind_data_schema/core/session.py
> +    scanfield_z_unit: Optional[SizeUnit] = Field(None, title="Z stage position unit")
@jtyoung84  Got it and fixed

2024-03-05 03:24 UTC, arielleleon commented
@jtyoung84 Examples have been added

2024-03-05 18:50 UTC, jtyoung84 approved these changes

2024-03-06 04:19 UTC, arielleleon commented
After meeting with @saskiad , I fixed / added the following:

- using coupled_fov_index
- removed scanimage_resolution for the provided fov_scale_factor
- default power for fov set to PERCENT by default

2024-03-06 04:25 UTC, saskiad commented on examples/multiplane_ophys_session.py
> +                    fov_scale_factor_unit=SizeUnit.UM,
fov_scale_factor_unit should be um/pixel, correct?

2024-03-06 04:28 UTC, saskiad requested changes
Minor thing with the `fov_scale_factor_unit`

2024-03-06 05:23 UTC, arielleleon commented on examples/multiplane_ophys_session.py
> +                    fov_scale_factor_unit=SizeUnit.UM,
Good catch - this is fixed now

2024-03-06 17:09 UTC, saskiad approved these changes

2024-03-07 22:15 UTC, merged