use model validator instead
AllenNeuralDynamics/aind-data-schema pull request #805
Opened 2024-02-27 22:35 UTC by mochic

Addresses #804

2024-02-28 20:39 UTC, dyf requested changes

2024-02-28 20:39 UTC, dyf commented on src/aind_data_schema/core/rig.py
> +    rig_axes: Optional[List[Axis]] = Field(None, title="Rig axes", min_length=3, max_length=3)
any reason your are changing the default here?

2024-02-29 04:22 UTC, mochic commented on src/aind_data_schema/core/rig.py
> +    rig_axes: Optional[List[Axis]] = Field(None, title="Rig axes", min_length=3, max_length=3)
Yeah. Sorry this is included in this pr and also not in it's own commit. I think that the current default is incorrect and causes future deserialization issues. It is a list that doesn't match the min length requirement for the field. I can remove it as it is out of the scope of this pr.

2024-02-29 05:02 UTC, mochic commented on src/aind_data_schema/core/rig.py
> +    rig_axes: Optional[List[Axis]] = Field(None, title="Rig axes", min_length=3, max_length=3)
Resolved in 1ce710e but I think that this change needs to occur at some point to allow for models to be serialized with the default and then be deserialized with later issues.

2024-03-01 22:43 UTC, mochic commented
@dyf I added a new test to supplement the loss of coverage but it does bother me that this change is significant enough that what was covering this in the past no longer is.

2024-03-01 23:55 UTC, closed without merging

2024-03-11 17:33 UTC, dyf commented
@mochic I was just looking at this issue - is there a reason you closed it?

2024-03-11 19:37 UTC, mochic commented
@dyf I think that the bug I was experiencing was related to something else on my end. It's possible that model validators are more "correct" but I don't think we get anything out of it.