feat:injection materials is optional list
AllenNeuralDynamics/aind-data-schema pull request #806
Opened 2024-02-28 16:00 UTC by micahwoodard

fixes #765 
- injection material optional 
- if list, the list needs to have at list one item

2024-02-29 01:46 UTC, jtyoung84 commented on src/aind_data_schema/core/procedures.py
> +    ] = Field(None, title="Injection material", min_length=1)
Is there a unit test that verifies these validate under a few conditions. We should check that the Injection model should:
 - Pass if injection_materials is None
 - Fail if injection_materials is an empty list []
 - Pass if injection_materials is a list with at list one ViralMaterial or NonViralMaterial item

2024-02-29 01:46 UTC, jtyoung84 requested changes
It might be helpful to add a unit test to check some validations

2024-02-29 16:34 UTC, micahwoodard commented
I added tests for None and empty list. It seemed like there was already a test checking the a list with at list one ViralMaterial or NonViralMaterial item, but I can add one in if you were thinking of something in

2024-02-29 17:55 UTC, jtyoung84 approved these changes

2024-02-29 21:19 UTC, saskiad commented
For the record: in the long run we don't want injection_materials to be optional. If an injection is performed, we need to know what was injected. If we need to make it optional temporarily because we don't have the systems yet, we can do that, but we will need to revert this in the future

2024-03-06 00:35 UTC, saskiad approved these changes

2024-03-07 22:15 UTC, merged