timezones required for times
AllenNeuralDynamics/aind-data-schema pull request #831
Opened 2024-03-13 15:49 UTC by micahwoodard

fixes #484 
- replace datetime fields with AwareDatetime
- requires .astimezone() for datetime inputs

2024-03-13 16:55 UTC, jtyoung84 commented on examples/ephys_rig.py
> +    calibration_date=datetime(2023, 10, 2, 10, 22, 13, tzinfo=timezone.utc).astimezone(tz=timezone.utc),
Does it work if we just do:
```python
calibration_date=datetime(2023, 10, 2, 10, 22, 13, tzinfo=timezone.utc)
```
I think as long as it get's stored with an offset, we should be good.

2024-03-13 17:00 UTC, micahwoodard commented on examples/ephys_rig.py
> +    calibration_date=datetime(2023, 10, 2, 10, 22, 13, tzinfo=timezone.utc).astimezone(tz=timezone.utc),
oh so leave out the astimezone? I'm not sure I'll check

2024-03-13 17:13 UTC, micahwoodard commented on examples/ephys_rig.py
> +    calibration_date=datetime(2023, 10, 2, 10, 22, 13, tzinfo=timezone.utc).astimezone(tz=timezone.utc),
Yep that works. Changing accordingly

2024-03-14 04:10 UTC, saskiad commented on examples/bergamo_ophys_session.json
> +   "session_start_time": "2022-07-12T07:00:00Z",
This is probably my ignorance, but I don't understand the Z nomenclature. How does this indicate the timezone?

2024-03-14 04:10 UTC, saskiad reviewed
I'm just confused about how this works - the code looks fine to me, but I want to understand before merging.

2024-03-14 17:04 UTC, jtyoung84 commented
> I'm just confused about how this works - the code looks fine to me, but I want to understand before merging.

We can add a step to use the locale of the user's computer settings as a default, as per the discussion yesterday. With the current implementation, a user will need to supply the timezone information whenever they create a datetime object, otherwise an error will be raised.
```python
from datetime import datetime, timezone

# Current implementation doesn't add any tzinfo
session_start_time=datetime(2023, 10, 2, 10, 22, 13)

# After this gets merged, a user will need to add this line to get the timezone of their os settings
session_start_time=datetime(2023, 10, 2, 10, 22, 13).astimezone()

# We can add that "astimezone()" as a default if a user just defines
# a datetime object as above. Users shouldn't need to change anything
# in that case. 

# Alternatively, a user can supply a timezone if they know it
session_start_time=datetime(2023, 10, 2, 10, 22, 13, tzinfo=timezone.utc)

# We may need to update the metadata-entry app to add timezone information
```

2024-03-14 18:39 UTC, saskiad commented
Can we update the examples to use this to help make it clear?
`session_start_time=datetime(2023, 10, 2, 10, 22, 13).astimezone()`

2024-03-15 15:24 UTC, dyf commented
> The main issue is that the unit tests will use different timezone settings when run locally vs. in github actions, which can cause discrepancies in the example.json files if we don't specify a timezone in the example.py files. We can modify the unit tests to ignore the datetime fields if we want though.

IMO having the examples always use UTC will be fine.

2024-03-19 16:25 UTC, saskiad approved these changes

2024-03-19 16:34 UTC, jtyoung84 requested changes
Add AwareDatetime with Default

2024-03-21 16:09 UTC, jtyoung84 approved these changes

2024-03-22 00:25 UTC, merged