Feat 751 more validators for other
AllenNeuralDynamics/aind-data-schema pull request #853
Opened 2024-03-21 20:21 UTC by Sun-flow

closes #751 

Adding Validators for Rig and Instrument and subclasses which check for the existence of `Other` fields and confirms that they are described in the notes.

2024-03-22 16:01 UTC, dyf requested changes

2024-03-26 20:00 UTC, saskiad commented on src/aind_data_schema/core/rig.py
> +                        f"Describe the camera ({camera_assembly.camera_assembly_name}) in the notes field"
like wise "Notes cannot be empty if a camera target contains ..."

2024-03-26 20:19 UTC, saskiad commented on src/aind_data_schema/models/devices.py
> +            raise ValueError("Notes cannot be empty if side is Other. Describe the spout side in the notes field.")
if spout side is Other

2024-03-26 20:20 UTC, saskiad commented on src/aind_data_schema/models/devices.py
> +            raise ValueError("Notes cannot be empty if type is Other. Describe the imaging type in the notes field.")
... if Imaging Device Type is Other. Describe the Imaging device in the notes field.

2024-03-26 20:20 UTC, saskiad requested changes
just some minor phrasing stuff for the warnings.

2024-04-02 17:34 UTC, Sun-flow commented on src/aind_data_schema/models/devices.py
> +            raise ValueError("Notes cannot be empty if type is Other. Describe the imaging type in the notes field.")
This one is weird because the field name is `type`, so maybe we should change that to `imaging_device_type` for clarity

2024-04-03 02:54 UTC, saskiad approved these changes

2024-04-03 03:00 UTC, merged