Feat 847 sessionmri
AllenNeuralDynamics/aind-data-schema pull request #883
Opened 2024-04-03 22:43 UTC by saskiad

closes #847

2024-04-03 22:43 UTC, saskiad commented
this will impact the mri ingest function slightly - just needs to point it to `Session` and add a few extra fields

2024-04-22 20:23 UTC, dyf requested changes

2024-04-22 20:23 UTC, dyf commented on src/aind_data_schema/core/session.py
> +    mri_scanner: Optional[Scanner] = Field(None, title="MRI scanner")
Do we actually need `Scanner` here? Should that not instead be part of a `Rig`?

2024-04-22 20:53 UTC, saskiad commented on src/aind_data_schema/core/session.py
> +    mri_scanner: Optional[Scanner] = Field(None, title="MRI scanner")
I don't think it makes sense to make a rig.json for a Scanner.

2024-04-23 16:21 UTC, jtyoung84 commented on examples/mri_session.json
> +               "echo_time": "3.4199999999999999289457264239899814128875732421875",
This happens when using floats directly instead of `Decimal("3.42")` when constructing these fields

2024-04-24 18:33 UTC, saskiad commented on examples/session.json
I'm confused by this file - let's keep the mri example as mri_session.py. I don't think we want a generic session example as there are some many different variants on the sessions.

2024-04-24 18:50 UTC, Sun-flow commented on examples/mri_session.json
> +               "echo_time": "3.4199999999999999289457264239899814128875732421875",
This is weird because it is using Decimal. It is not using decimal as a string? Would that be the issue? `Decimal(3.42)`

2024-04-24 19:37 UTC, saskiad commented on examples/mri_session.json
> +               "echo_time": "3.4199999999999999289457264239899814128875732421875",
yeah, I think that's what Jon means. If you feed Decimal a string it won't have that floating point error.

2024-04-29 17:58 UTC, jtyoung84 approved these changes

2024-04-29 18:36 UTC, saskiad commented on src/aind_data_schema/core/session.py
> +    mri_scanner: Optional[Scanner] = Field(None, title="MRI scanner")
@Sun-flow let's move the mri_scanner to the `MRIScan` field and then it can be a required field and we don't need a validator for it.

2024-04-30 20:21 UTC, Sun-flow commented on src/aind_data_schema/core/session.py
> +    mri_scanner: Optional[Scanner] = Field(None, title="MRI scanner")
Let's move this into MRIScan

2024-04-30 22:06 UTC, Sun-flow approved these changes

2024-05-02 19:58 UTC, dyf approved these changes

2024-05-02 19:58 UTC, dyf commented
@Sun-flow go ahead and resolve these merge conflicts and you can merge

2024-05-03 15:32 UTC, merged