Convert all `device_type`s to sentence casing
AllenNeuralDynamics/aind-data-schema pull request #936
Opened 2024-05-15 19:52 UTC by Sun-flow

closes #923 

Changed all `device_type` fields that were not using sentence casing to use sentence casing.

2024-05-16 23:28 UTC, dyf requested changes

2024-05-16 23:28 UTC, dyf commented on src/aind_data_schema/core/session.py
> +    device_type: Literal["Light Emitting Diode"] = "Light Emitting Diode"
should probably be "Light emitting diode"

2024-05-17 20:50 UTC, Sun-flow commented on src/aind_data_schema/core/session.py
> +    device_type: Literal["Light Emitting Diode"] = "Light Emitting Diode"
edit: "changed all `device_type` fields (except one) that were not using sentence casing to use sentence casing."

2024-05-18 13:24 UTC, saskiad commented on src/aind_data_schema/components/devices.py
> +    device_type: Literal["Open ephys acquisition board"] = "Open ephys acquisition board"
Since Open Ephys is an organization, let's have it be "Open Ephys acquisition board"

2024-05-18 13:26 UTC, saskiad requested changes
one small fix. Otherwise looks good.

2024-05-21 22:58 UTC, saskiad approved these changes

2024-05-22 17:48 UTC, saskiad approved these changes

2024-05-22 19:44 UTC, dyf approved these changes

2024-05-22 19:44 UTC, merged