feat: contributor guidelines
AllenNeuralDynamics/aind-data-schema pull request #942
Opened 2024-05-21 21:54 UTC by mekhlakapoor

closes #857

2024-05-29 19:27 UTC, dyf requested changes
can you migrate relevant things from the "Contributing" section from README.md here and add a README.md -> CONTRIBUTION.md link?

2024-05-30 17:47 UTC, saskiad commented on CONTRIBUTING.md
> +- Use **flake8** to check that code is up to standards (no unused imports, etc.):
Is there a link that we can point people to as to what the standards are?

2024-05-30 17:48 UTC, saskiad commented on CONTRIBUTING.md
> +If you'd like to propose a large change or addition, or generally have a question about how things work, head start a new [Discussion](https://github.com/AllenNeuralDynamics/aind-data-schema/discussi
remove the work "head" ?

2024-05-30 17:50 UTC, saskiad commented on CONTRIBUTING.md
> +Feature requests and bug reports are all welcome as [issues](https://github.com/AllenNeuralDynamics/aind-data-schema/issues). Please use the provided [templates](https://github.com/AllenNeuralDynamic
Can we ask people to not assign people in their tickets. Maybe say something about the process - eg. create a ticket and we will review it and address it in our sprint. If they want to grab someone's attention, they can tag us in the issue. But there are people who have been assigning tickets and it disrupts the process (imo).

2024-05-30 17:50 UTC, saskiad commented on CONTRIBUTING.md
> +If you'd like to propose a large change or addition, or generally have a question about how things work, head start a new [Discussion](https://github.com/AllenNeuralDynamics/aind-data-schema/discussi
I might phrase this as "If you have a broader suggestion or a question about how things work"

2024-05-30 17:54 UTC, saskiad commented on CONTRIBUTING.md
> +Feature requests and bug reports are all welcome as [issues](https://github.com/AllenNeuralDynamics/aind-data-schema/issues). Please use the provided [templates](https://github.com/AllenNeuralDynamic
'Feature request' means something to SWE that might not be the same as many of the scientists in our org. Is there a way to explain the scope of what a reasonable feature request is?

2024-05-30 17:56 UTC, saskiad commented on CONTRIBUTING.md
> +This repository defines the schemas needed to ingest and validate metadata. As a core service, it is used across multiple teams and services. Therefore, any contributions must follow certain rules to
"ingest" isn't really right here... This isn't ingesting metadata, it's defining the schema for the metadata. 
"This repository defines the metadata schema used to document our data assets." Maybe? It does also validate... but I worry that saying ingest will imply that this repo is doing the mapping, which it is not.

2024-05-31 17:57 UTC, dyf approved these changes

2024-05-31 17:57 UTC, merged