Remove software
AllenNeuralDynamics/aind-data-schema pull request #948
Opened 2024-05-28 15:57 UTC by micahwoodard

fixes #892 
- removed recording_software from Detector class 
- removed encoder_firmware from Disc class
-  removed software  and script from StimulusEpoch

2024-06-01 03:06 UTC, saskiad commented on src/aind_data_schema/core/session.py
> -    software: Optional[List[Software]] = Field(
don't remove the software/script from the session. Thanks!

2024-06-01 03:06 UTC, saskiad requested changes
let's not remove software, etc, from the session class.

2024-06-10 15:42 UTC, micahwoodard commented on src/aind_data_schema/core/session.py
> -    software: Optional[List[Software]] = Field(
Okay added back in!

2024-07-29 18:07 UTC, closed without merging

2024-07-29 18:07 UTC, jtyoung84 commented
Decided not to remove this software field