Ephys Improvements
AllenNeuralDynamics/aind-data-schema pull request #979
Opened 2024-06-17 20:31 UTC by Sun-flow

closes #971

`Anaesthetic.level` -> `Optional`
`Session.reward_consumed_unit` -> new default: mL

2024-06-21 17:13 UTC, saskiad commented on src/aind_data_schema/core/procedures.py
> +    level: Optional[Decimal] = Field(..., title="Level (percent)", ge=1, le=5)
default needs to be None for optional

2024-06-21 17:13 UTC, saskiad requested changes
fix the default!

2024-07-03 15:19 UTC, dyf requested changes
accidentally approved before, see comment above

2024-07-05 16:55 UTC, saskiad commented on src/aind_data_schema/core/procedures.py
> +    level: Optional[Decimal] = Field(None, title="Level (percent)", ge=1, le=5)
add the default= here as well

2024-07-05 16:56 UTC, saskiad requested changes
we want the default= in all the places that there's a default value. It improves the understandability of the schema.

2024-07-05 22:43 UTC, saskiad approved these changes

2024-07-05 23:36 UTC, dyf approved these changes

2024-07-05 23:37 UTC, merged