rig id validator
AllenNeuralDynamics/aind-data-schema pull request #985
Opened 2024-07-02 21:28 UTC by mekhlakapoor

closes #970

2024-07-03 15:17 UTC, dyf requested changes

2024-07-03 15:17 UTC, dyf commented on src/aind_data_schema/core/rig.py
> +RIG_ID_PATTERN = r"^\d{3}_[a-zA-Z0-9-]+_\d{8}$"
I don't think we should restrict room names to 3 digits (I know this was ambiguous in the original issue). That's very 615-Westlake-specific.

I think it it should be any string of alphanumeric characters. @saskiad ?

2024-07-03 17:10 UTC, saskiad commented on src/aind_data_schema/core/rig.py
> +RIG_ID_PATTERN = r"^\d{3}_[a-zA-Z0-9-]+_\d{8}$"
Yeah, our room names are 3 digits, but I think any string of numbers is fine.

2024-07-03 17:12 UTC, mekhlakapoor commented on src/aind_data_schema/core/rig.py
> +RIG_ID_PATTERN = r"^\d{3}_[a-zA-Z0-9-]+_\d{8}$"
Should it be a string of digits (any length) or should it be alphanumeric

2024-07-05 21:30 UTC, dyf requested changes

2024-07-05 21:30 UTC, dyf commented on src/aind_data_schema/core/rig.py
> +    @field_validator("rig_id", mode="after")
on second though, I think you can do this with `Field(..., pattern='blah')` instead of needing to write a field_validator.  And then it will make it into the jsonschema.

2024-07-05 21:38 UTC, mekhlakapoor commented on src/aind_data_schema/core/rig.py
> +    @field_validator("rig_id", mode="after")
just changed it to use the pattern constraint! It throws a validation error with this error message: 

`String should match pattern '^[a-zA-Z0-9]+_[a-zA-Z0-9-]+_\d{8}$' [type=string_pattern_mismatch, input_value='123', input_type=str]`

2024-07-05 21:45 UTC, dyf approved these changes

2024-07-05 22:07 UTC, merged