moved QC into current schema
AllenNeuralDynamics/aind-data-schema pull request #999
Opened 2024-07-24 19:16 UTC by saskiad

2024-07-25 18:43 UTC, saskiad commented
still don't understand these error messages. Most of them are for files this PR doesn't touch. The one about this is uninterpretable.

2024-07-25 21:32 UTC, saskiad commented
TODO: remove
MANUAL_ANNOTATION = "Manual annotation"
QUALITY_CONTROL_AND_ASSESSMENT = "Quality control and assessment"
from ProcessName Model in aind-data-schema-models

2024-08-06 03:18 UTC, dyf requested changes

2024-08-06 04:24 UTC, saskiad commented on src/aind_data_schema/core/quality_metrics.py
> +    evaluation_date: date = Field(..., title="Evaluation date")
I think date.

2024-08-06 04:24 UTC, saskiad commented on src/aind_data_schema/core/quality_metrics.py
> +    overall_status_date: date = Field(..., title="Date of status")
I still think date.

2024-08-06 04:27 UTC, saskiad commented on src/aind_data_schema/core/quality_metrics.py
> +    UNKNOWN = "Unknown"
I expect we're going to add a bunch of other options to this.

2024-08-08 17:42 UTC, dyf commented
@jtyoung84  I am good with this for now, it will change. But it's a new core schema so want your eyes on it.

2024-08-08 17:45 UTC, dyf approved these changes

2024-08-08 17:52 UTC, jtyoung84 commented on src/aind_data_schema/core/quality_metrics.py
> +class Status(Enum):
We can make this `class Status(str, Enum)` to be able to use some helpful string enum methods

2024-08-08 17:55 UTC, jtyoung84 commented on src/aind_data_schema/core/quality_metrics.py
> +    stage_status: Status = Field(..., title="Stage status")
Since this a required field, do we want an `Unknown` option? Will it always be Pass/Fail?

2024-08-08 17:57 UTC, jtyoung84 commented on tests/test_quality_metrics.py
> +        now = datetime.datetime.now()
It's better to avoid using values that change each run in unit tests. Can we use a fixed datetime?

2024-08-08 17:58 UTC, jtyoung84 commented
Do you want to add this in the core.Metadata class also? It won't show up in DocDB otherwise.

2024-08-08 17:59 UTC, jtyoung84 commented
Should we also add something in the examples folder?

2024-08-08 17:59 UTC, dyf commented
> Do you want to add this in the core.Metadata class also? It won't show up in DocDB otherwise.

Yes

2024-08-08 18:00 UTC, dyf commented
> Should we also add something in the examples folder?

yes

2024-08-08 18:02 UTC, saskiad commented on src/aind_data_schema/core/quality_metrics.py
> +    stage_status: Status = Field(..., title="Stage status")
you'll need to duke that out with @dyf - he removed the `Unknown` option. My hunch is that we're going to end up with a handful of Status options very quickly, but I don't think we want one to be Unknown.

2024-08-08 18:05 UTC, jtyoung84 commented on src/aind_data_schema/core/quality_metrics.py
> +    stage_status: Status = Field(..., title="Stage status")
My worry is, that since it's required, if we ever upgrade old metadata records, we'll just fall back to using `QCEvaluation.model_construct()` everywhere, which is frustrating.

2024-08-12 22:10 UTC, jtyoung84 approved these changes

2024-08-13 00:12 UTC, merged